Document: audioconversor
Title: Debian audioconversor Manual
Author: <insert document author here>
Abstract: This manual describes what audioconversor is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/audioconversor/audioconversor.sgml.gz

Format: postscript
Files: /usr/share/doc/audioconversor/audioconversor.ps.gz

Format: text
Files: /usr/share/doc/audioconversor/audioconversor.text.gz

Format: HTML
Index: /usr/share/doc/audioconversor/html/index.html
Files: /usr/share/doc/audioconversor/html/*.html


