Document: kademar-kde3
Title: Debian kademar-kde3 Manual
Author: <insert document author here>
Abstract: This manual describes what kademar-kde3 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/kademar-kde3/kademar-kde3.sgml.gz

Format: postscript
Files: /usr/share/doc/kademar-kde3/kademar-kde3.ps.gz

Format: text
Files: /usr/share/doc/kademar-kde3/kademar-kde3.text.gz

Format: HTML
Index: /usr/share/doc/kademar-kde3/html/index.html
Files: /usr/share/doc/kademar-kde3/html/*.html

  
