Document: kademar-khronos
Title: Debian kademar-khronos Manual
Author: <insert document author here>
Abstract: This manual describes what kademar-khronos is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/kademar-khronos/kademar-khronos.sgml.gz

Format: postscript
Files: /usr/share/doc/kademar-khronos/kademar-khronos.ps.gz

Format: text
Files: /usr/share/doc/kademar-khronos/kademar-khronos.text.gz

Format: HTML
Index: /usr/share/doc/kademar-khronos/html/index.html
Files: /usr/share/doc/kademar-khronos/html/*.html


