#!/bin/bash
### BEGIN INIT INFO
# Provides:             kademar-installed
# Required-Start:    $local_fs $remote_fs
# Required-Stop:     $local_fs $remote_fs
# Default-Start:     2 3
# Default-Stop:     
# Short-Description:    Set kademar configurations
# Description:      Search changes on display graphic card and load sl-modem if found
### END INIT INFO

#
# Adonay Sanz per la kademar  -  Octubre 2005
# Adonay Sanz per la kademar  -  Febrer 2006
# Adonay Sanz per la kademar  -  Maig 2008
# Adonay Sanz per la kademar  -  Febrer 2009
# Adonay Sanz per la kademar  -  Maig 2010
# Adonay Sanz per la kademar  -  Gener 2011
#

#Check Graphic-Card Change
sh /usr/share/kademar/scripts/engegada/grafica-comprova

# hack to fix possible errors on desktop start
#  due a start apps with sudo command
rm -f /home/*/.ICEauthority 2>/dev/null


#managed by kademarcenter
# if [ ! -e /usr/share/kademar/Sistema.txt ]; then
# 	#Restore default volumes
#     # execute once
# 	sh /usr/share/kademar/scripts/engegada/volums >/dev/null 2>&1
# 	sh /usr/share/kademar/utils/instalador/scripts/install-usuaris-fix-permissions & 
# fi


#Win-Modems  Detection - Now on Udev Rules
# [ -n "`lsmod | grep slamr`" -o -n "`lsmod | grep slusb`" ] && /etc/init.d/sl-modem-daemon start


#Pmount Permissions
# ( chmod ugo+x /usr/bin/pmount ; chmod ugo+x /usr/bin/pumount ) &