#!/bin/bash

#################################################
# Script per instalar el GRUB com a boot-loader #
#         -------------------------             #
#    Parcialment extret dels Burnix-Scripts     #
#    Preparat per la kademar 5.0 - 04 Mai 2008  #
#    Preparat per la kademar 4.2 - 14 Mai 2005  #
#    Preparat per la kademar 4.0 - 3 Nov 2005   #
#    Llicenciat Sota GNU/GPL 2.0 o Superiors    #
#################################################

#MODE TO CALL IT
# install-bootloader
. /tmp/instalador-environment

#Assignem el parametre 1 al dispositiu
DEV="$mbr_dev"
#Assignem una variable amb el dispositiu sense numero
DEV_SENSE_NUMERO=${DEV%[1-9]}

#Assignem el parametre 2 al desti
# DESTI="$3"
#Si no n'hem assignat cap, assignem el per defecte en la kademar 4.0
# [ -z "$DESTI" -o "$DESTI" = "0" ] && DESTI="/instalador/desti"



#Versiï¿œ del Kernel
if [ -z "$cadi" ]; then
     kernel="`uname -r`"
else
     cd $DESTI/boot
     kernel=$(for i in `ls -1 vmlinuz* | sed s/vmlinuz-//g`; do echo $i; break ; done) 
fi

#Borrem una possible carpeta grub anterior, i la tornem a crear
rm -fr $DESTI/boot/grub 
mkdir -p $DESTI/boot/grub

#Suport a gfxboot-grub 
cp /boot/grub/message.* $DESTI/boot/grub 2>/dev/null

#Copiem propiament el grub en la seva carpeta
[ -e $DESTI/lib/grub/i386-pc/ ] && cp $DESTI/lib/grub/i386-pc/* $DESTI/boot/grub/
[ -e $DESTI/usr/lib/grub/i386-pc/ ] && cp $DESTI/usr/lib/grub/i386-pc/* $DESTI/boot/grub/
[ -e $DESTI/lib/grub/x86_64-pc/ ] && cp $DESTI/lib/grub/x86_64-pc/* $DESTI/boot/grub/
[ -e $DESTI/usr/lib/grub/x86_64-pc/ ] && cp $DESTI/usr/lib/grub/x86_64-pc/* $DESTI/boot/grub/
  

#Borrem l'arxiu de configuraciï¿œ del grub en cas de que existeixi
[ -e $DESTI/boot/grub/menu.lst ] && rm -f $DESTI/boot/grub/menu.lst
[ -e $DESTI/boot/grub/device.map ] && rm -f $DESTI/boot/grub/device.map

#Borrem el mtab
rm -f  $DESTI/etc/mtab
#I creem una entrada estandar per l'instalador
echo "/dev/$DEV / $fsparticioarrel defaults 0 0" > $DESTI/etc/mtab


# Search for grub version
if [ -z "`dpkg -l | grep -i grub-pc | grep -i ii`" ]; then
#grub 1
    echo *** Grub Version 1 ***
    grubver=1
else
# grub2
    echo *** Grub Version 2 ***
    grubver=2
fi

#Creem el Device.map amb la informacio dels dispositius
if [ -n "`which grub-mkdevicemap`" ]; then
# grub2 normally  and  grub 1 tunned installations
    grub-mkdevicemap --no-floppy --device-map=$DESTI/boot/grub/device.map
else
#grub 1
    echo quit \
      | grub --batch --no-floppy --device-map=$DESTI/boot/grub/device.map
fi


#chroot $DESTI sed -i "s~# kopt.*~# kopt=root=$DESTI_ROOT $DEF_BOOTPARMS~g" /boot/grub/menu.lst 

#TODO find a way to not have to do that twice
#chroot $DESTI update-grub -y  

#Si no s'ha definit que NO volem mbr, instala'l
if [ "$mbr" != "no" ]; then
    #Si el mbr es "automatic", fem que es busqui la vida, sino el sobreecrivim
    if [ "$mbr" = "auto" ]; then
        MBR_SENSE_NUMERO=`cat $DESTI/boot/grub/device.map | grep '(hd0)' | sed s:/dev/::g | awk ' { print $2 } '`
    else
        MBR_SENSE_NUMERO=`echo $mbr | awk ' { print $1 } ' | sed s:/dev/::g`
    fi

    #support to new grubs
    if [ "$grubver" = 2 ]; then
        lba=""
    else
        lba="--force-lba"
    fi

    grub-install --no-floppy $lba --root-directory=$DESTI /dev/$MBR_SENSE_NUMERO

    echo "grub-install --no-floppy $lba --root-directory=$DESTI /dev/$MBR_SENSE_NUMERO"

fi

# Si el initrd esta marcat per crear-lo
if [ "$make_initrd" = "yes" ]; then
    # Mirem quin es el creador de initrd que volem
    #Creem l'initrd per el kernel
    if [ -e /usr/sbin/mkinitrd ]; then
        chroot $DESTI mkinitrd -r $DEV -o /boot/initrd.img-$kernel $kernel
    else
        if [ -e /usr/sbin/mkinitramfs ]; then
            chroot $DESTI mkinitramfs -o /boot/initrd.img-$kernel $kernel
        else
            chroot $DESTI yaird -o /boot/initrd.img-$kernel $kernel
        fi
    fi
fi


# chroot $DESTI update-grub -y

# rm -f $DESTI/boot/grub/menu.lst

#if [ -f /cdrom/boot/grub/bootlogo ] ; then
	#echo "${BLUE}Copying  ${GREEN}gfxboot${NORMAL}"
	#cp /cdrom/boot/grub/bootlogo $DESTI/boot/grub
	#mv $DESTI/boot/grub/menu.lst $DESTI/boot/grub/menu.lst.ori
	#echo "gfxmenu = /boot/grub/bootlogo" > $DESTI/boot/grub/menu.lst
	#cat $DESTI/boot/grub/menu.lst.ori >> $DESTI/boot/grub/menu.lst
	#rm $DESTI/boot/grub/menu.lst.ori
#fi

#echo "${BLUE}Boot parms: ${GREEN}$DEF_BOOTPARMS${NORMAL}"

#Borrem l'entrada genï¿œrica del mtab
# rm -f $DESTI/etc/mtab
#Restaurem l'entrada original del mtab
# ln -s /proc/mounts $DESTI/etc/mtab
