Document: kademar-base
Title: Debian kademar-base Manual
Author: <insert document author here>
Abstract: This manual describes what kademar-base is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/kademar-base/kademar-base.sgml.gz

Format: postscript
Files: /usr/share/doc/kademar-base/kademar-base.ps.gz

Format: text
Files: /usr/share/doc/kademar-base/kademar-base.text.gz

Format: HTML
Index: /usr/share/doc/kademar-base/html/index.html
Files: /usr/share/doc/kademar-base/html/*.html


