#!/bin/bash
list="kdemar-base kdemar-base-desktop kdemarcenter-deb_creator cadi-deb_creator kdemar-kde kdemar-lyra kdemar-leo kdemar-core kdemar-core-kde4 kdemar-csic audioconversor-deb_creator "

for i in `ls`
do
	if [ -e $i/trunk ]; then
        cd $i/trunk
	    debuild -r fakeroot
	    cd ../..
     fi
done

echo "enter folder where copy .deb files"
read folder

if [ -n "$folder" ]; then
    mkdir -p "$folder"
fi

mv */*.deb "$folder"
