#!/bin/bash
# Script per crear els enllaços als dispositius en /mnt i /Pc
# set -x
#Modificat 05-09-06 Adonay Sanz Alsina
#Modificat 28.02.07 Adonay Sanz Alsina
#Modificat 06.03.08 Adonay Sanz Alsina - Compatible amb kademarcenter

# $1 = /dev/sdb
# $2 = anything  - to disable warn msg, and disable eject

if [ -n "$1" -a "$1" != "0" ]; then
	
	echo "BORRANT  $1"

	ruta_pc="/Pc"
	ruta_mnt="/mnt"
	
	hd="`echo $1 | sed s:/dev/::g`" #Treiem el /dev residual  (/dev/sdb1 -> sdb1)
	unitat_sense_dev=${hd%%[0-9]*}  #Treiem el Numero residual  (sdb1 -> sdb)


####################################
# REAL DEVICE FORCED DESCONNECTION #
####################################



#Si hi ha un error al desconnectar, vol dir que ja s'havien extret, sense desmuntar-lo. Avisa k no s'ha de fer 
# 	rm -f /tmp/kademar_error_umount
	echo "Force Umount"
	#Si hi ha hagut algún error, FORÇA desmunta
	for i in  `grep /dev/$unitat_sense_dev /proc/mounts | awk ' { print $2 } '`
	do
		umount $i || umount $i || umount -l $i
	done


	# 	Expulsem el dispositiu - si no es un cdrom!!!
	if [ -z "$2" ]; then
		for i in `ls $1*`
		do
			eject $i
		        hd="`echo $i | sed s:/dev/::g`" #Treiem el /dev residual  (/dev/sdb1 -> sdb1)
				
			if [ -z "`grep $hd /proc/mounts`" ]; then
				#Borrem l'enllaç del /Pc
				rm -fr $ruta_pc/*$hd*
				rm -fr $ruta_mnt/*$hd*
				rm -fr $ruta_mnt/*$i*
				rm -fr $ruta_pc/*$i*
			fi
		done
                eject  /dev/$unitat_sense_dev
	
	fi



fi
