#!/bin/bash
# Script per crear els enllaços als dispositius en /mnt i /Pc
# set -x
#Modificat 05-09-06 Adonay Sanz Alsina
#Modificat 28.02.07 Adonay Sanz Alsina
#Modificat 06.03.08 Adonay Sanz Alsina - Compatible amb kademarcenter

# $1 = /dev/sdb
# $2 = anything  - to disable warn msg, and disable eject

if [ -n "$1" -a "$1" != "0" ]; then
	
	echo "BORRANT  $1"

	ruta_pc="/Pc"
	ruta_mnt="/mnt"
	
	hd="`echo $1 | sed s:/dev/::g`" #Treiem el /dev residual  (/dev/sdb1 -> sdb1)
	unitat_sense_dev=${hd%%[0-9]*}  #Treiem el Numero residual  (sdb1 -> sdb)


#############################
# REAL DEVICE DESCONNECTION #
#############################

	cd /dev/
	sync
	#Desmuntem els dispositius, per si encara hi són (INTENT - si no existeix pq el dispositiu ja s'ha borrat, donarà un error
	for i in  `grep /dev/$unitat_sense_dev /proc/mounts | awk ' { print $2 } '`
	do
		pumount $i || pumount $i || umount $i || umount $i || error=si
	done


	#Desmuntem els enllaços en el media
# 	umount /media/$hd?
# 	umount /mnt/$hd*

# 	[ -z "`grep $hd /proc/mounts`" ] && rm -fr /media/$hd*

# 	Expulsem el dispositiu - si no es un cdrom!!!
	if [ -z "$error" ]; then
		if [ -z "$2" ]; then
			for i in `ls $1*` /dev/$unitat_sense_dev
			do
				eject $i
			done
			
			#Borrem l'enllaç del /Pc i /mnt
			. /usr/share/kademar/utils/kademarcenter/scripts.py
			$remove_links $1
		
		fi
# 	Si hi ha hagut un error
	else
# 		si es un cdrom i hi ha hagut un error, force umount
		if [ -z "$2" ]; then
			/usr/share/kademar/utils/kademarcenter/scripts/umount_device_forced $1
		fi
# 		I avisa a kademarcenter que hi ha hagut un error 
		echo "ERROR"
	fi
fi
