 
post_install() {
  update_files
}

post_upgrade() {
  update_files
}

post_remove(){
    #remove desktop-selector packages
    rm -fr /usr/share/desktop-selector/
}

update_files() {
  if chrooted; then

    mkdir -p /usr/share/desktop-selector/pacmandb /usr/share/desktop-selector/drivers
    rm /var/cache/pacman/pkg/*catalyst* /var/cache/pacman/pkg/nvidia-* 2>/dev/null
    pacman --dbpath /usr/share/desktop-selector/pacmandb --cachedir /usr/share/desktop-selector/drivers/nvidia --noconfirm -Sy 
    pacman --dbpath /usr/share/desktop-selector/pacmandb --cachedir /usr/share/desktop-selector/drivers/nvidia --noconfirm -Swdd nvidia-libgl nvidia nvidia-utils opencl-nvidia libcl libxv
    pacman --dbpath /usr/share/desktop-selector/pacmandb --cachedir /usr/share/desktop-selector/drivers/nvidia-legacy --noconfirm -Swdd nvidia-304xx nvidia-304xx-utils opencl-nvidia-304xx libcl
    pacman --dbpath /usr/share/desktop-selector/pacmandb --cachedir /usr/share/desktop-selector/drivers/catalyst --noconfirm -Swdd catalyst-dkms catalyst-utils opencl-catalyst netkit-bsd-finger dkms patch xinetd make
    [ "$(uname -m)" != "i686" ] && pacman --dbpath /usr/share/desktop-selector/pacmandb --cachedir /usr/share/desktop-selector/drivers/nvidia --noconfirm -Swdd lib32-nvidia-libgl lib32-nvidia-utils lib32-libxvmc lib32-zlib lib32-libxdmcp lib32-libxau lib32-libx11 lib32-libxext lib32-libxv lib32-libxcb
    [ "$(uname -m)" != "i686" ] && pacman --dbpath /usr/share/desktop-selector/pacmandb --cachedir /usr/share/desktop-selector/drivers/nvidia-legacy --noconfirm -Swdd lib32-nvidia-304xx-utils lib32-libxvmc lib32-zlib lib32-libxdmcp lib32-libxau lib32-libx11 lib32-libxext lib32-libxv lib32-libxcb
    [ "$(uname -m)" != "i686" ] && pacman --dbpath /usr/share/desktop-selector/pacmandb --cachedir /usr/share/desktop-selector/drivers/catalyst --noconfirm -Swdd lib32-catalyst-utils
    rm -fr /usr/share/desktop-selector/pacmandb

    #systemctl enable desktop-selector
#    if [ ! -e '/etc/systemd/system/display-manager.service' ]; then
 #     ln -s /usr/lib/systemd/system/desktop-selector.service '/etc/systemd/system/display-manager.service'
 #   fi
  
  if [ ! -e /etc/kademar/desktop-selector.ini ]; then
     [ ! -e /etc/kademar ] && mkdir -p /etc/kademar
     /bin/cp /usr/share/desktop-selector/desktop-selector.ini /etc/kademar
  fi
  
  fi




}

#Udev Stolen Function :-[
chrooted() {
  if [ "$(stat -c %d/%i /)" = "$(stat -Lc %d/%i /proc/1/root 2>/dev/null)" ];
  then
    # the devicenumber/inode pair of / is the same as that of /sbin/init's
    # root, so we're *not* in a chroot and hence return false.
    return 1
  fi
  echo " * Live-CD Creation environment detected. Doing file changes"
  return 0
}
