Document: kademar-core
Title: Debian kademar-core Manual
Author: <insert document author here>
Abstract: This manual describes what kademar-core is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/kademar-core/kademar-core.sgml.gz

Format: postscript
Files: /usr/share/doc/kademar-core/kademar-core.ps.gz

Format: text
Files: /usr/share/doc/kademar-core/kademar-core.text.gz

Format: HTML
Index: /usr/share/doc/kademar-core/html/index.html
Files: /usr/share/doc/kademar-core/html/*.html
