#!/bin/sh
set -e
#Udev Stolen Function :-[

# Automatically added by dh_installmodules
if [ "$1" = "configure" ]; then

    if [ ! -e /usr/bin/kdesu -a -e /usr/bin/kdesudo ]; then
        ln -s kdesudo /usr/bin/kdesu
    fi
 
    #graphics raster render engine
    dpkg-divert --package kademar-kde4-core --add --divert /usr/share/autostart/bkp/plasma-desktop.desktop.orig --rename /usr/share/autostart/plasma-desktop.desktop
    [ ! -e /usr/share/autostart/plasma-desktop.desktop ] && ln -s /usr/share/autostart/bkp/plasma-desktop-kademar.desktop /usr/share/autostart/plasma-desktop.desktop

    #Desactivate Nepomuk & Strigi & Virtuoso - wins 200 mb
    dpkg-divert --package kademar-kde4-core --add --divert /usr/share/autostart/bkp/kaddressbookmigrator.desktop.orig --rename /usr/share/autostart/kaddressbookmigrator.desktop
    dpkg-divert --package kademar-kde4-core --add --divert /usr/share/autostart/bkp/nepomukserver.desktop.orig --rename /usr/share/autostart/nepomukserver.desktop


    #removes device-notifier applet ANOYING mode
    [ ! -e /usr/share/kde4/services/old ] && mkdir -p /usr/share/kde4/services/old 
    dpkg-divert --package kademar-kde4-core --add --divert /usr/share/kde4/services/old/plasma-applet-devicenotifier.desktop --rename /usr/share/kde4/services/plasma-applet-devicenotifier.desktop

    [ ! -e /usr/lib/kde4/old ] && mkdir -p /usr/lib/kde4/old
    dpkg-divert --package kademar-kde4-core --add --divert /usr/lib/kde4/old/plasma_applet_devicenotifier.so --rename /usr/lib/kde4/plasma_applet_devicenotifier.so


    [ ! -e /etc/kde4/kdm/kdmrc.orig ] && dpkg-divert --package kademar-kde4-core --add --divert /etc/kde4/kdm/kdmrc.orig --rename /etc/kde4/kdm/kdmrc
    [ ! -e /etc/kde4/kdm/kdmrc ] && ln -s /etc/kde4/kdm/kdmrc.kademar /etc/kde4/kdm/kdmrc
    [ ! -e /etc/kde4/kdm/backgroundrc.orig ] && dpkg-divert --package kademar-kde4-core --add --divert /etc/kde4/kdm/backgroundrc.orig --rename /etc/kde4/kdm/backgroundrc
    [ ! -e /etc/kde4/kdm/backgroundrc ] && ln -s /etc/kde4/kdm/backgroundrc.kademar /etc/kde4/kdm/backgroundrc

    exit 0

fi
# End automatically added section
