#!/bin/sh
set -e
# Automatically added by dh_installmodules

case "$1" in
    purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
	
        if [ remove = "$1" ]; then
		#remove raster render engine KDE4
                rm -f /usr/share/autostart/plasma-desktop.desktop
                dpkg-divert --package kademar-kde4-core --remove --divert /usr/share/autostart/bkp/plasma-desktop.desktop.orig --rename /usr/share/autostart/plasma-desktop.desktop

                #Recover original .desktop files on autostart    
                dpkg-divert --package kademar-kde4-core --remove --divert /usr/share/autostart/bkp/kaddressbookmigrator.desktop.orig --rename /usr/share/autostart/kaddressbookmigrator.desktop
                dpkg-divert --package kademar-kde4-core --remove --divert /usr/share/autostart/bkp/nepomukserver.desktop.orig --rename /usr/share/autostart/nepomukserver.desktop


		#remove hack of anoying applet  devicenotifier
                dpkg-divert --package kademar-kde4-core --remove --divert /usr/share/kde4/services/old/plasma-applet-devicenotifier.desktop --rename /usr/share/kde4/services/plasma-applet-devicenotifier.desktop
                dpkg-divert --package kademar-kde4-core --remove --divert /usr/lib/kde4/old/plasma_applet_devicenotifier.so --rename /usr/lib/kde4/plasma_applet_devicenotifier.so
                rm -fr /usr/share/kde4/services/old /usr/lib/kde4/old

		rm -f /etc/kde4/kdm/backgroundrc /etc/kde4/kdm/kdmrc
                dpkg-divert --package kademar-kde4-core --remove --divert /etc/kde4/kdm/kdmrc.orig --rename /etc/kde4/kdm/kdmrc
                dpkg-divert --package kademar-kde4-core --remove --divert /etc/kde4/kdm/backgroundrc.orig --rename /etc/kde4/kdm/backgroundrc


        fi

    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
