#!/bin/bash

#script to start orca
 
fstartorca(){
# Older compiz versions start gtk-window-decorator only if GNOME_DESKTOP_SESSION_ID is set.
[ -n "$GNOME_DESKTOP_SESSION_ID" ] || export GNOME_DESKTOP_SESSION_ID="LXDE"
export SAL_USE_VCLPLUGIN="gtk" GTK_MODULES="gail:atk-bridge"
startorca ; sleep 10 

# Orca, for some reason, ruins Alt_R on the german keyboard.
# This is a workaround to fix it.
# (
#  for ((i=0; i<30; i++)); do
#   sleep 2
#   xmodmap | grep -q 'mod1.*ISO_Level3_Shift' && xmodmap -e "remove mod1 = ISO_Level3_Shift"
#  done
# ) &

}


#Orca Screenread Support
[ -n "`grep orca /proc/cmdline`" ] && fstartorca # ORCA support
