Document: kademar-extra-themes-ksplash
Title: Debian kademar-extra-themes-ksplash Manual
Author: <insert document author here>
Abstract: This manual describes what kademar-extra-themes-ksplash is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/kademar-extra-themes-ksplash/kademar-extra-themes-ksplash.sgml.gz

Format: postscript
Files: /usr/share/doc/kademar-extra-themes-ksplash/kademar-extra-themes-ksplash.ps.gz

Format: text
Files: /usr/share/doc/kademar-extra-themes-ksplash/kademar-extra-themes-ksplash.text.gz

Format: HTML
Index: /usr/share/doc/kademar-extra-themes-ksplash/html/index.html
Files: /usr/share/doc/kademar-extra-themes-ksplash/html/*.html


