Document: kademar-audacious-skins
Title: Debian kademar-audacious-skins Manual
Author: <insert document author here>
Abstract: This manual describes what kademar-audacious-skins is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/kademar-audacious-skins/kademar-audacious-skins.sgml.gz

Format: postscript
Files: /usr/share/doc/kademar-audacious-skins/kademar-audacious-skins.ps.gz

Format: text
Files: /usr/share/doc/kademar-audacious-skins/kademar-audacious-skins.text.gz

Format: HTML
Index: /usr/share/doc/kademar-audacious-skins/html/index.html
Files: /usr/share/doc/kademar-audacious-skins/html/*.html


