#!/usr/bin/python2
# Adonay Jonay Sanz Alsina - adonay@kademar.org
# License GNU/GPL 3.0 or higer
# 24 abril 2012

import dbus
import sys

if len(sys.argv)>1:
    #print sys.argv[1]
    pass
else:
    print "Need a parameter HDD to show product info"
    sys.exit(1)

bus = dbus.SystemBus()
ud_manager_obj = bus.get_object("org.freedesktop.UDisks", "/org/freedesktop/UDisks")
ud_manager = dbus.Interface(ud_manager_obj, 'org.freedesktop.UDisks')

for dev in ud_manager.EnumerateDevices():
    device_obj = bus.get_object("org.freedesktop.UDisks", dev)
    #print dev
    device_props = dbus.Interface(device_obj, dbus.PROPERTIES_IFACE)
    devicefile=device_props.Get('org.freedesktop.UDisks.Device', "DeviceFile")
    devicefile=devicefile.strip("/dev/")
    #print devicefile, str(sys.argv[1]).strip("/dev/")

    if str(devicefile)==str(sys.argv[1]).strip("/dev/"):
      
        print device_props.Get('org.freedesktop.UDisks.Device', "DriveModel")
