#!/bin/bash

#################################################
# Script per Configurar la contrassenya de root #
#         -------------------------             #
#    Preparat per la kademar 5.0 - 10 Mar 2012 #
#    Llicenciat Sota GNU/GPL 2.0 o Superiors    #
#################################################

. /tmp/instalador-environment
. /tmp/instalador-environment-passwd #Plantilla de passwords

#I l'executem en el $DESTI, passant-li el parametre del pass de root
echo "$login:$passwd" | /usr/sbin/chpasswd -R "$DESTI"
