#!/bin/bash

#################################################
#    Preparat per la kademar 4.0 - 6 Nov 2005   #
#    Llicenciat Sota GNU/GPL 2.0 o Superiors    #
#################################################

#TODO: Utilitzar al 100% el  os-prober

################################
# BUSCA PARTICIONS ARRANCABLES #
################################

dispositius=`ls /mnt --ignore=cdrom* --ignore=dvd* --ignore=fd* --ignore=disquet* 2>/dev/null`

fitxer="/tmp/particions-arrancables"
rm -f $fitxer*

if [ -n "$dispositius" ]; then
    for i in $dispositius
    do
        if [ -e "/mnt/$i/boot/grub/menu.lst" ]; then
            echo "$i Linux Grub" >> $fitxer
            echo "$i Linux Grub"
            cp /mnt/$i/boot/grub/menu.lst $fitxer\_$i-grub
        else
            if [ -e "/mnt/$i/etc/lilo.conf" ]; then
                echo "$i Linux Lilo" >> $fitxer
                echo "$i Linux Lilo"
                cp /mnt/$i/etc/lilo.conf $fitxer\_$i-lilo
            fi
        fi
    done
fi

####################################
# END BUSCA PARTICIONS ARRANCABLES #
####################################