#!/bin/bash

#################################################
#     Script for configure distro Language      #
#         -------------------------             #
#    Prepared for kademar 4.0 - 3 Nov 2005      #
#        Modified    kademar 4.1 - 20 Feb 2006  #
#        Modified    kademar 4.3 - 5 Set 2006   #
#        Modified    kademar 4.8 - 2 Feb 2009   #
#        Modified    kademar 5.0 - 12 Abr 2012  #
#    Licensed under  GNU/GPL 2.0 o Higher       #
#################################################


# Inspired on knoppix-autoconfig

#Check parameters
[ -z "$1" ] && echo "I need at least a LANG (xx) parameter to work" && exit 1

LANGUAGE="$1"
#echo $LANGUAGE #DEBUG

#Target folder, may change
[ -n "$2" ] && DESTI="$2"

#Load variables
locale_file="$DESTI/etc/rc.conf"

########### //  LOCALE DEFINITION EXTRACTED FROM KNOPPIX \\ #############

case "$LANGUAGE" in
# Catalan version
ca*)
COUNTRY="es"
LANG="ca_ES.UTF-8"
KEYTABLE="es"
LANG_COUNTRY="ca_ES"
XKEYBOARD="es"
KDEKEYBOARD="es"
CHARSET="iso8859-15"
# Additional KDE Keyboards
KDEKEYBOARDS=""
TZ="Europe/Madrid"
OPTIONAL=":ca_ES:ca:es_ES.UTF-8:es_ES:es"
;;
# German version
de*)
COUNTRY="de"
LANG="de_DE.UTF-8"
KEYTABLE="de-latin1-nodeadkeys"
XKEYBOARD="de"
KDEKEYBOARD="de"
CHARSET="iso8859-15"
# Additional KDE Keyboards
KDEKEYBOARDS="us,fr"
TZ="Europe/Berlin"
;;
# Belgian version
be*)
LANGUAGE="be"
COUNTRY="be"
LANG="C"
KEYTABLE="be2-latin1"
XKEYBOARD="be"
KDEKEYBOARD="be"
CHARSET="iso8859-15"
# Additional KDE Keyboards
KDEKEYBOARDS="us,de,fr"
TZ="Europe/Brussels"
;;
# Bulgarian version
bg*)
LANGUAGE="bg"
COUNTRY="bg"
LANG="bg_BG"
KEYTABLE="bg"
XKEYBOARD="bg"
KDEKEYBOARD="bg"
CHARSET="microsoft-cp1251"
# Additional KDE Keyboards
KDEKEYBOARDS="us,de,fr"
TZ="Europe/Sofia"
;;
# Swiss version (basically de with some modifications*)
ch*)
LANGUAGE="de"
COUNTRY="ch"
LANG="de_CH"
KEYTABLE="sg-latin1"
XKEYBOARD="de_CH"
KDEKEYBOARD="de_CH"
CHARSET="iso8859-15"
# Additional KDE Keyboards
KDEKEYBOARDS="de,us,fr"
TZ="Europe/Zurich"
;;
cn*)
# Simplified Chinese version
COUNTRY="cn"
LANG="zh_CN.GB2312"
KEYTABLE="us"
XKEYBOARD="us"
KDEKEYBOARD="us"
CHARSET="gb2312.1980-0"
# Additional KDE Keyboards
KDEKEYBOARDS="us,de,fr"
XMODIFIERS="@im=Chinput"
TZ="Asia/Shanghai"
;;
# Czech version
cs*|cz*)
LANGUAGE="cs"
COUNTRY="cs"
LANG="cs_CZ"
KEYTABLE="cz-lat2"
XKEYBOARD="cs"
KDEKEYBOARD="cs"
CHARSET="iso8859-2"
# Additional KDE Keyboards
KDEKEYBOARDS="us,de,fr"
TZ="Europe/Prague"
CONSOLEFONT="iso02g"
;;
dk*|da*)
# Dansk version
COUNTRY="dk"
LANG="da_DK"
# Workaround: "dk" broken in gettext, use da:da_DK
LANGUAGE="da:da_DK"
# Keytable "dk" is correct.
KEYTABLE="dk"
XKEYBOARD="dk"
KDEKEYBOARD="dk"
CHARSET="iso8859-15"
# Additional KDE Keyboards
KDEKEYBOARDS="dk,de,us,fr"
TZ="Europe/Copenhagen"
;;
es*)
# Spanish version
COUNTRY="es"
LANG="es_ES.UTF-8"
KEYTABLE="es"
LANG_COUNTRY="es_ES"
XKEYBOARD="es"
KDEKEYBOARD="es"
CHARSET="iso8859-15"
# Additional KDE Keyboards
KDEKEYBOARDS="de,us,fr"
TZ="Europe/Madrid"
OPTIONAL=":es_ES:es"
;;
fi*)
# Finnish version, though we may not have the kde-i18n files
COUNTRY="fi"
LANG="fi_FI.UTF-8"
KEYTABLE="fi"
XKEYBOARD="fi"
KDEKEYBOARD="fi"
CHARSET="iso8859-15"
# Additional KDE Keyboards
KDEKEYBOARDS="us"
TZ="Europe/Helsinki"
;;
fr*)
# French version
COUNTRY="fr"
LANG="fr_FR.UTF-8"
KEYTABLE="fr"
XKEYBOARD="fr"
KDEKEYBOARD="fr"
CHARSET="iso8859-15"
# Additional KDE Keyboards
KDEKEYBOARDS="de,us"
TZ="Europe/Paris"
;;
he*|il*)
# Hebrew version
LANGUAGE="he"
COUNTRY="il"
LANG="he_IL"
KEYTABLE="us"
XKEYBOARD="us"
KDEKEYBOARD="il"
CHARSET="iso8859-8"
# Additional KDE Keyboards
KDEKEYBOARDS="us,fr,de"
TZ="Asia/Jerusalem"
;;
ie*)
# Irish (English) version
COUNTRY="ie"
LANG="en_IE.UTF-8"
KEYTABLE="uk"
XKEYBOARD="uk"
KDEKEYBOARD="gb"
CHARSET="iso8859-15"
#Additional KDE Keyboards
KDEKEYBOARDS="us,de,es,fr,it"
TZ="Europe/Dublin"
;;
it*)
# Italian version
COUNTRY="it"
LANG="it_IT.UTF-8"
KEYTABLE="it"
XKEYBOARD="it"
KDEKEYBOARD="it"
CHARSET="iso8859-15"
# Additional KDE Keyboards
KDEKEYBOARDS="fr,us,de"
TZ="Europe/Rome"
;;
ja*)
# (limited) Japanese version
COUNTRY="jp"
LANG="ja_JP"
LANGUAGE="ja"
KEYTABLE="us"
XKEYBOARD="us"
KDEKEYBOARD="us"
CHARSET="iso8859-15"
# Additional KDE Keyboards
KDEKEYBOARDS="fr,us,de"
TZ="Asia/Tokyo"
;;
nl*)
# Dutch version
COUNTRY="nl"
LANG="nl_NL.UTF-8"
KEYTABLE="us"
XKEYBOARD="us"
KDEKEYBOARD="en_US"
CHARSET="iso8859-15"
# Additional KDE Keyboards
KDEKEYBOARDS="nl,de,fr"
TZ="Europe/Amsterdam"
;;
pl*)
# Polish version
COUNTRY="pl"
LANG="pl_PL"
KEYTABLE="pl"
XKEYBOARD="pl"
KDEKEYBOARD="pl"
CHARSET="iso8859-2"
# Additional KDE Keyboards
KDEKEYBOARDS="de,us,fr"
TZ="Europe/Warsaw"
CONSOLEFONT="iso02g"
;;
ru*)
# Russian version
COUNTRY="ru"
LANG="ru_RU.KOI8-R"
KEYTABLE="ru"
XKEYBOARD="ru"
KDEKEYBOARD="ru"
CHARSET="koi8-r"
CONSOLEFONT="Cyr_a8x16"
# Additional KDE Keyboards
KDEKEYBOARDS="de,us,fr"
TZ="Europe/Moscow"
;;
sk*)
# Slovak version (guessed)
COUNTRY="sk"
LANG="sk"
KEYTABLE="sk-qwerty"
XKEYBOARD="sk"
KDEKEYBOARD="sk"
CHARSET="iso8859-2"
# Additional KDE Keyboards
KDEKEYBOARDS="us,de"
TZ="Europe/Bratislava"
CONSOLEFONT="iso02g"
;;
# Slovenian keyboard
sl*)
LANGUAGE="sl"
COUNTRY="si"
LANG="sl_SI"
KEYTABLE="slovene"
XKEYBOARD="sl"
KDEKEYBOARD="si"
CHARSET="iso8859-2"
# Additional KDE Keyboards
KDEKEYBOARDS="us,de"
TZ="Europe/Ljubljana"
CONSOLEFONT="iso02g"
;;
tr*)
# Turkish version (guessed)
COUNTRY="tr"
LANG="tr_TR"
KEYTABLE="tr_q-latin5"
XKEYBOARD="tr"
KDEKEYBOARD="tr"
CHARSET="iso8859-9"
# Additional KDE Keyboards
KDEKEYBOARDS="us,de,fr"
TZ="Europe/Istanbul"
;;
tw*)
# Traditional Chinese version (thanks to Chung-Yen Chang)
COUNTRY="tw"
LANG="zh_TW.Big5"
LANGUAGE="zh_TW.Big5"
KEYTABLE="us"
XKEYBOARD="us"
KDEKEYBOARD="us"
# CHARSET="big5-0"
CHARSET="iso8859-1"
# Additional KDE Keyboards
KDEKEYBOARDS="us"
XMODIFIERS="@im=xcin"
TZ="Asia/Taipei"
;;
uk*)
# British version
COUNTRY="uk"
LANG="en_GB"
LANGUAGE="en"
KEYTABLE="uk"
XKEYBOARD="uk"
KDEKEYBOARD="gb"
CHARSET="iso8859-1"
# Additional KDE Keyboards
KDEKEYBOARDS="us"
TZ="Europe/London"
;;
en|*)
# American version
LANGUAGE="us"
COUNTRY="us"
LANG="en_GB.UTF-8"
KEYTABLE="us"
XKEYBOARD="us"
KDEKEYBOARD="us"
CHARSET="iso8859-1"
# Additional KDE Keyboards
KDEKEYBOARDS="de,fr"
TZ="America/New_York"
;;
esac

################ //  END OF LOCALE DEFINITION  \\  ####################

sed "s~LOCALE=.*~LOCALE=\"$LANG\"~g" -i $DESTI/etc/rc.conf 
sed "s~TIMEZONE=.*~TIMEZONE=\"$TZ\"~g" -i $DESTI/etc/rc.conf 
sed "s~KEYMAP=.*~KEYMAP=\"$KEYTABLE\"~g" -i $DESTI/etc/rc.conf 
sed "s~DAEMON_LOCALE=.*~DAEMON_LOCALE=\"no\"~g" -i $DESTI/etc/rc.conf 


 # UTF-8: Default is "on" in newer kernels, but for practical reasons,
 # individual languages may use latin instead, also on the initial console.
#  case "$LANG" in
#   *UTF-8*) echo "1" > /sys/module/vt/parameters/default_utf8; unicode_start 2>/dev/null ;;
#         *) echo "0" > /sys/module/vt/parameters/default_utf8; unicode_stop  2>/dev/null ;;
#  esac



#  if [ -n "$TZ" ]; then
#   echo "$TZ" > $DESTI/etc/timezone
#   rm -f $DESTI/etc/localtime
#   [ -r $DESTI/usr/share/zoneinfo/"$TZ" ] && { ln -s /usr/share/zoneinfo/"$TZ" $DESTI/etc/localtime; }
#  fi
