#!/bin/bash
#
# Creat per Adonay Sanz per la kademar  -  03-11-06
#
# Preparador de la sessio X que s'engegarà
#

DEPRECATED

#TODO: Restaurar les configuracions

for i in 2 3 4 5
do
	echo "#!/bin/bash
#Start de Xsession
	
sh /usr/share/kademar/scripts/engegada/xsession start &" > /etc/rc$i.d/S99xsession
chmod +x /etc/rc$i.d/S99xsession
done

for i in 0 1 6
do
	ln -s /usr/share/kademar/scripts/engegada/xsession /etc/rc$i.d/K01session
done