#!/bin/bash
#
# Creat per Adonay Sanz per la kademar  -  03-11-06
# Modificat  05-11-06
# Modificat  07-01-07
#
# Fitxer de configuració del Firefox
#

# mode to call it:   common-firefox  [username] [desti]

#Usuari a configurar
if [ -n "$1" ]; then
	user="$1"
else
	user="kademar"
fi

#Desti
if [ -n "$1" ]; then
	DESTI="$1"
else
	DESTI=""
fi


. /etc/environment

case "$LANGUAGE" in
ca*)
	documents=Documents
	desktop=Escriptori
	lang_firefox=ca
;;
es*)
	documents=Documentos
	desktop=Escritorio
	lang_firefox=es
;;
en*)
	documents=Documents
	desktop=Desktop
	lang_firefox=es
;;
esac


#Firefox  pagina d'inici
for i in `( ls -1 $DESTI/home/$user/.mozilla/firefox/ | grep default ) 2>/dev/null`
do
	if [ -e "$DESTI/home/$user/.mozilla/firefox" ]; then
		echo 'user_pref("browser.startup.homepage", "http://www.kademar.org/?lang='$lang_firefox'");
		user_pref("browser.download.dir", "/home/'$user'/'$documents'");' >> "$DESTI/home/$user/.mozilla/firefox/$i/user.js"
	fi
done

#Iceweasel  pagina d'inici
for i in `( ls -1 $DESTI/home/$user/.mozilla/iceweasel/ | grep default ) 2>/dev/null`
do
	if [ -e "$DESTI/home/$user/.mozilla/iceweasel" ]; then
			echo 'user_pref("browser.startup.homepage", "http://www.kademar.org/?lang='$lang_firefox'");
			user_pref("browser.download.dir", "/home/'$user'/'$documents'");' >> "$DESTI/home/$user/.mozilla/iceweasel/$i/user.js"
	fi
done