#!/bin/bash
#
# Creat per Adonay Sanz per la kademar  -  Febrer 2007
#
# Ús total de bash a l'engegada, ideat per la kademar 4.0, 20 dec 2006.
# Posat a la practica completament el febrer 2007

#Script per canviar l'ubicació del home i/o del autostart, canviant el kdeglobals

# set -x #Debug
dirbase="/home"

# comproba si s'ha passat un parametre d'un usuari
if [ -z "$1" ]; then
	#Si no s'especifica res, fes tots els usuaris
	user=`ls /home --ignore=ANONYMOUS --ignore=Pc`
else
	#Si s'especifica un, utilitza'l
	user=$1
fi

#Especifiquem concretament per l'usuari SKEL
if [ "$user" = skel ]; then
	dirbase="/etc"
fi

. /etc/default/locale

fitxer='/.kde3/share/config/kdeglobals'

case "$LANG" in
ca*)
escriptori='Escriptori'
autoengega='.kde3/Autoengega'
;;
es*)
escriptori='Escritorio'
autoengega='.kde3/Autoarranque'
;;
en*|C|*)
escriptori='Desktop'
autoengega='.kde3/Autostart'
;;
esac


#Per cada usuari en el home
for j in $user
do
#ESCRIPTORI
	#Troba la definicio actual del fitxer
	find0=`cat "$dirbase/$j$fitxer" | grep = | grep 'Desktop=$HOME'` 
	#Si no la ha trobat, assegura que no la trobarà (per no provocar accidents)
	[ -z "$find0" ] && find0="AkEsTa Kadena NO La Trobaras Mai"
	#Treu el $HOME de la variable
	desktop_antic=`echo "$find0" | sed s,'$HOME/',,g`
	#treus tot el k hi ha abans del = (variable pelada)
	desktop_antic=`echo "$desktop_antic" | sed s,'Desktop=',,g`

	#Canvia les propietats de l'Escriptori, si hi ha algo a modificar
	if [ "$escriptori" != "$desktop_antic" -a "$find0" != "AkEsTa Kadena NO La Trobaras Mai" ]; then
		#Mou de l'antiga ruta a la nova, si no existeix i no pot sobreesciure
		if [ ! -e "$dirbase/$j/$escriptori" ]; then
			mv "$dirbase/$j/$desktop_antic" "$dirbase/$j/$escriptori"
			#Substitueix la variable vella per la nova
			cat "$dirbase/$j$fitxer" | sed s,"$find0","Desktop=\$HOME/$escriptori",g > "$dirbase/$j$fitxer".tmp
			rm -f "$dirbase/$j$fitxer"
			mv "$dirbase/$j$fitxer".tmp "$dirbase/$j$fitxer"
		fi
	fi
	
#AUTOSTART
	#Troba la definicio actual del fitxer
	find1=`cat "$dirbase/$j$fitxer" | grep = | grep "Autostart="`
	#Si no la ha trobat, assegura que no la trobarà (per no provocar accidents)
	[ -z "$find1" ] && find1="AkEsTa Kadena NO La Trobaras Mai"	
	#Treu el $HOME de la variable
	autostart_antic=`echo "$find1" | sed s,'$HOME',,g`
	#treus tot el k hi ha abans del = (variable pelada)
	autostart_antic=`echo "$autostart_antic" | sed s,'Autostart=',,g`

	#Canvia les propietats de l'Autostart, si hi ha algo a modificar
	if [ "$autoengega" != "$autostart_antic" -a "$find1" != "AkEsTa Kadena NO La Trobaras Mai" ]; then
		#Mou de l'antiga ruta a la nova, si no exiteix la nova i no pot sobreesciure
		if [ -e "$dirbase/$j/$autostart" ]; then
			mv "$dirbase/$j/$autostart_antic" "$dirbase/$j/$autoengega"
			#Substitueix la variable vella per la nova
			cat "$dirbase/$j$fitxer" | sed s,"$find1","Autostart=\$HOME/$autoengega",g > "$dirbase/$j$fitxer".tmp
			rm -f "$dirbase/$j$fitxer"
			mv "$dirbase/$j$fitxer".tmp "$dirbase/$j$fitxer"
		fi
	fi
done