#!/bin/bash
#
# Creat per Adonay Sanz per la kademar  -  Octubre 2005
# Modificat  03-11-06
# Modificat  24-08-07
#
# Configurador del Desktop de KDE
#

deprecated

#TODO: Restaurar les configuracions

user="kademar"
trobat="no"

. /etc/default/locale

crea_kademar_links(){
#HTML Link on Desktop
echo "[Desktop Entry]
Encoding=UTF-8
Exec=konqueror "/usr/share/kademar/html/kademar$2.html"
Icon=tux
Name=kademar
Path='/usr/share/kademar/html/'
StartupNotify=true
Terminal=false
Type=Application
X-KDE-SubstituteUID=false" > $1/kademar.desktop

#HTML Link on /usr/share/kademar
echo "#!/bin/bash
#
# Llicencia GNU/GPL 2.0 i posterior
# # # # # # # # # # # # # # # # #

killall -15 htm 2>/dev/null #mata el proces htm

kfmclient sortDesktop   #organitza les icones de l'escriptori

rm -fr \$HOME/.kde/Auto*/html
rm -fr \$HOME/.kde/Auto*/htm

kfmclient sortDesktop   #organitza les icones de l'escriptori

sh /usr/share/kademar/scripts/engegada/engega_serveis &

konqueror /usr/share/kademar/html/kademar$2.html" > /usr/share/kademar/scripts/html_borra
chmod +x /usr/share/kademar/scripts/html_borra

#Instal Link
echo "[Desktop Entry]
Encoding=UTF-8
Exec=/usr/share/kademar/scripts/engega_instalador
Icon=/usr/share/kademar/icons/kpackage.png
Name=Install kademar on Hard Drive
Name[ca]=Instal·la kademar al disc dur
Name[es]=Instalar kademar en el disco duro
Name[en]=Install kademar on Hard Drive
StartupNotify=true
Terminal=false
Type=Application
X-KDE-SubstituteUID=false" > $1/Instal.desktop

#Saveconfig Link
# echo "[Desktop Entry]
# Exec=sh /usr/share/kademar/utils/cadi/saveconfig
# Icon=filesave.png
# Name=Guarda la configuració en disquet
# Name[ca]=Guarda la configuració en disquet
# Name[es]=Guardar la configuración personal
# Name[en]=Save configuration on floppy disk
# Terminal=true
# Type=Application" > $1/Config.desktop

#Xscreensaver Link
# echo "[Desktop Entry]
# Exec=xscreensaver -no-splash
# Name=XScreensaver
# Name[ca]=XScreensaver - Salvapantalles
# Name[es]=XScreensaver - Salvapantallas
# StartupNotify=false
# Terminal=false
# Type=Application
# X-KDE-StartupNotify=false
# X-KDE-SubstituteUID=false" > $3/xscreensaver
# chmod +x $3/xscreensaver

}

# #Crea bloqueig de NumLock
# crea_numlock(){
# 	echo "[Desktop Entry]
# Exec=numlockx $resposta_numlock
# Icon=keyboard
# X-KDE-StartupNotify=false
# StartupNotify=false
# Type=Application" > $1/numlock.desktop
# }


if [ "$trobat" = "no" ]; then
	case "$LANG" in
	ca*)
		echo 'Creant Configuracio Personal'
	;;
	es*)
		echo "Creando Configuración Personal"
	;;
	en*)
		echo "Creating Personal Configuration"
	;;
	esac
	if [ -e /var/directhome ]; then #assegura k no es faci 2 vegades
		echo "Home already created - remove /var/directhome if you want to re-create it"
		else
		# Canviar Llengua de KDE, KDM i Audacity
		sh /usr/share/kademar/scripts/engegada/kademar-inici.d-standalone/kde-canvikdeglobals #Canviar llengua
		sh /usr/share/kademar/scripts/engegada/kademar-inici.d-standalone/common-canvillengua
		if [ "`laptop-detect ; echo $?`" != 0 ]; then
			#Si es portatil
			resposta_numlock=1 #Activa
		else	
			#Si no es un portatil
			resposta_numlock=0 #Desactiva
			rm -f /usr/share/autostart/syndock.desktop
		fi
		case "$LANG" in
		ca*)
			crea_kademar_links /home/$user/Escriptori _ca /home/$user/.kde/Autoengega
			ln -s /usr/share/kademar/scripts/html-escriptori /home/$user/.kde/Autoengega/htm
# 			crea_numlock /home/$user/.kde/Autoengega
			#Links al Pc
			ln -s -n /Pc /home/$user/Escriptori/Pc 
			ln -s -n /Pc /home/$user/Pc
			lang_firefox=ca
			documents=Documents
			desktop=Escriptori
			#Link al Desktop
			ln -s /home/$user/$desktop /home/$user/Desktop
		;;
		es*)
			crea_kademar_links /home/$user/Escritorio _es /home/$user/.kde/Autoarranque
			ln -s /usr/share/kademar/scripts/html-escriptori /home/$user/.kde/Autoarranque/htm
# 			crea_numlock /home/$user/.kde/Autoarranque
			#Links al Pc
			ln -s -n /Pc /home/$user/Escritorio/Pc 
			ln -s -n /Pc /home/$user/Pc
			lang_firefox=es
			documents=Documentos
			desktop=Escritorio
			#Link al Desktop
			ln -s /home/$user/$desktop /home/$user/Desktop
		;;
		en*|*)
			crea_kademar_links /home/$user/Desktop _en /home/$user/.kde/Autostart
			ln -s /usr/share/kademar/scripts/html-escriptori /home/$user/.kde/Autostart/htm
# 			crea_numlock /home/$user/.kde/Autostart
			#Links al Pc
			ln -s -n /Pc /home/$user/Desktop/Pc 
			ln -s -n /Pc /home/$user/Pc
			lang_firefox=ca
			documents=Documents
			desktop=Desktop
		;;
		esac
		
		#Crea directori de documents
		sh /usr/share/kademar/scripts/documents $user
	
	fi
fi