post_install() {
  configure_nm_kde
}

post_upgrade() {
  configure_nm_kde
}

post_remove() {
    sed s.NotShowIn=KDE..g -i /etc/xdg/autostart/nm-applet.desktop 2>/dev/null
}

configure_nm_kde() {
  if [ -e "/etc/xdg/autostart/nm-applet.desktop" -a -z "`grep NotShowIn /etc/xdg/autostart/nm-applet.desktop 2>/dev/null | grep -v \#`" ]; then
    echo "NotShowIn=KDE" >> /etc/xdg/autostart/nm-applet.desktop
  fi
}