Document: kademar-kde
Title: Debian kademar-kde Manual
Author: <insert document author here>
Abstract: This manual describes what kademar-kde is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/kademar-kde/kademar-kde.sgml.gz

Format: postscript
Files: /usr/share/doc/kademar-kde/kademar-kde.ps.gz

Format: text
Files: /usr/share/doc/kademar-kde/kademar-kde.text.gz

Format: HTML
Index: /usr/share/doc/kademar-kde/html/index.html
Files: /usr/share/doc/kademar-kde/html/*.html

  
