#!/bin/bash

. /usr/lib/kademar-scripts/sourcables/functions
#Carrega l'idioma
. /etc/environment
case "$LANGUAGE" in
ca*)
	. /usr/lib/kademar-scripts/sourcables/interface_ca
;;
es*)
	. /usr/lib/kademar-scripts/sourcables/interface_es
;;
en*|*)
	. /usr/lib/kademar-scripts/sourcables/interface_en
;;
esac

if [ ! -z "$1" ]; then
	if [ -e "$1" ]; then 
		tip "$load_config_read_profile" ` basename $1 ` "..."
		. "$1"
		ok " done"
		else 
			echo "$load_config_no_exists_profile"
			exit 1
	fi
	else 
		echo "$load_config_no_profile"
fi

#Si no hi ha un directori arrel, assigna el per defecte
[ -z "$ROOT" ] && ROOT="`cat /etc/kademar-scripts/root.conf`"

#Assigna el directori arrel, a una variable que despres utilitzarem
DEVEL_ROOT="$ROOT"

#Carrega la configuracio general de carpetes
. /etc/kademar-scripts/kademar.conf
