#!/bin/bash
#
# Creat per Adonay Sanz per la kademar - 27 oct 2005
#

contador=0
format=jpg

#Escull quin llenguatge te
. /etc/default/locale
case "$LANG" in
ca*)
	fitxer="captura de pantalla"
	missatge="Captura de Pantalla Realitzada"
	missatge_2="El fitxer capturat el pots trobar als teus Fitxers Personals amb el nom de "
	break
;;
es*)
	fitxer="captura de pantalla"
	missatge="Captura de Pantalla Realizada"
	missatge_2="El fichero capturado lo puedes encontrar en tus Ficheros Personales con el nombre de "
	break
;;
en*)
	fitxer="screenshot"
	missatge="Screenshot Succeed"
	missatge_2="Screenshot realized now is placed in your Personal Folder with name "
	break
;;
esac
##################

# Si ja existeix una captura de pantalla amb un 0, fes que posi 1 o el numero que necessiti
while true
do
	if [ ! -e "$HOME/$fitxer $contador.$format" ]; then
		break
	else
		contador=$(($contador + 1))
	fi
done

#Captura la pantalla
xwd -root -screen > "$HOME/$fitxer $contador"

#Canviali el format de imatge (per defecte  .xwd
mogrify -format $format "$HOME/$fitxer $contador"

#Borra la captura amb .xwd
rm -f "$HOME/$fitxer $contador"


kdialog --title "          $missatge:          " --passivepopup "$missatge_2  \"$fitxer $contador.$format\"" 5
