#!/bin/bash

#use parameter as DESTI
[ -n "$1" ] && DESTI="$1"

#Check capability to check if it's a normal or panoramic display
var="$(echo `xrandr -q 2>/dev/null | grep \* | awk ' { print $1 } ' | sed s.x.\/.g` | bc -l)"

#if resolution detected
if [ -n "$var" ]; then
  #if it's 1,3 it's a normal monitor
    if [ "$var" = 1.33333333333333333333 ]; then
        echo "monitor=normal" > "$DESTI/etc/kademar/monitor"
    else
  #it's a panoramic one
        echo "monitor=panoramic" > "$DESTI/etc/kademar/monitor"
    fi

else
#if not detected, use normal monitor
    echo "monitor=normal" > "$DESTI/etc/kademar/monitor"
fi 
