#!/bin/bash
### BEGIN INIT INFO
# Provides:          startlivecd-2ndstage
# Required-Start:    
# Required-Stop:     
# Default-Start:     1
# Default-Stop:      
# Short-Description: start & configure livecd - part 2
# Description:       Second start
### END INIT INFO
# Engegada i configuració de la kademar en la fase de INIT 2
# (C) Adonay Sanz <adonay@kademar.org> 2006
# Llicenciat sota GNU/GPL 2.0 o superior
#
# És el primer Script que s'executa després del rcS.d  - Configuració Modular

# engegada de live-cd

#Si existeix el configurador modular, executa'l

#Detection of what kind of start  live-cd or USB w/o changes  OR  USB with changes
if [ -n "`grep changes /proc/cmdline`" -a -e /var/kademar/live-USB ]; then
   #start from a USB - livecd (saving changes)
   #   USB with changes

	sh /usr/share/kademar/scripts/engegada/kademar-inici.d-ng/common-base
	sh /usr/share/kademar/scripts/engegada/kademar-inici.d-ng/common-powersaved

else
   #real live-CD start
   #   live-cd or USB w/o changes
   #     if exists a second-stage
        mkdir -p /var/kademar/
	touch /var/kademar/live-USB  #and make a mark to only start services next time you boot as  live USB
	if [ -e /usr/share/kademar/scripts/engegada/kademar-inici_second-stage_config ]; then
		. /usr/share/kademar/scripts/engegada/kademar-inici_second-stage_config
	fi
fi