#!/bin/bash
### BEGIN INIT INFO
# Provides:          startlivecd-2ndstage
# Required-Start:    
# Required-Stop:     
# Default-Start:     1
# Default-Stop:      
# Short-Description: start & configure livecd - part 2
# Description:       Second start
### END INIT INFO
# Engegada i configuració de la kademar en la fase de INIT 2
# (C) Adonay Sanz <adonay@kademar.org> 2006
# Llicenciat sota GNU/GPL 2.0 o superior
#
# És el primer Script que s'executa després del rcS.d  - Configuració Modular

# engegada de live-cd

#Si existeix el configurador modular, executa'l

#DEPRECATED  NOW ON  kademar-livecd-autoconf
#DEPRECATED
#DEPRECATED
#DEPRECATED
#DEPRECATED


user=kademar

#Detection of what kind of start  live-cd or USB w/o changes  OR  USB with changes
if [ -n "`grep changes /proc/cmdline`" -a -e /etc/kademar/live-USB ]; then
   #start from a USB - livecd (saving changes)
   #   USB with changes
   continue

# 	sh /usr/share/kademar/scripts/engegada/kademar-inici.d-ng/common-base
# 	sh /usr/share/kademar/scripts/engegada/kademar-inici.d-ng/common-powersaved

else
   #real live-CD start
   #   live-cd or USB w/o changes

    #Portàtil
    if [ "`laptop-detect ; echo $?`" != 0 ]; then
        #Si no es portatil
        laptop=no
        rm -f /usr/share/autostart/syndock.desktop #remove syndock if ISN'T a laptop
    else
        #Si es un portatil
        laptop=yes
    fi

    echo $laptop > /etc/kademar/laptop #en usermod


    #KNOPPIX hack, perque el salvapantalles no bloquegi la pantalla
    #mv /usr/bin/kdesktop_lock /usr/bin/kdesktop_lock.orig
    if [ -e /usr/bin/kdesktop_lock ]; then
        rm -f /usr/bin/kdesktop_lock
        cp /usr/share/kademar/scripts/engegada/kdesktop_lock /usr/bin
    fi

    if [ -e /usr/share/kademar/scripts/engegada/kademar-inici_second-stage_config ]; then
        su -c "sh /usr/share/kademar/scripts/engegada/kademar-inici_second-stage_config" $user
    fi


    #Hack pels sudoers en live-cd
    echo "$user ALL=NOPASSWD:ALL" >> /etc/sudoers

    #Hack per esciure la commanda   "su"  i que no et demani pass
    echo "" >> /etc/bash.bashrc
    echo "" >> /etc/profile
    echo "alias su='sudo su'" >> /etc/bash.bashrc
    echo "alias su='sudo su'" >> /etc/profile

	touch /etc/kademar/live-USB  #and make a mark to only start services next time you boot as  live USB
#DEPRECATED, now on /etc/X11/Xsession.d   
# 	if [ -e /usr/share/kademar/scripts/engegada/kademar-inici_second-stage_config ]; then
# 		. /usr/share/kademar/scripts/engegada/kademar-inici_second-stage_config
# 	fi
fi