#!/bin/bash
### BEGIN INIT INFO
# Provides:          xsessionlivecd
# Required-Start:    $local_fs $remote_fs
# Required-Stop:     $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Xsession LiveCD
# Description:       Start desktop on livecd
### END INIT INFO

# Single Xwindow/KDE startup script
# (C) Klaus Knopper Jun 2001

#Modified to use with kademar 4.x - October 2005 - March 2006

USER=kademar

PATH="/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11R6/bin:/usr/local/bin:."
export PATH

umask 022

CRE="
[K"
BLUE="[1;34m"
NORMAL="[1;39m"

## Llenguatge ##
. /etc/default/locale
case "$LANG" in
ca*)
	. /usr/share/kademar/scripts/engegada/xsession-ca
;;
es*)
	. /usr/share/kademar/scripts/engegada/xsession-es
;;
*|en*)
	. /usr/share/kademar/scripts/engegada/xsession-en
;;
esac
##################


# RUNLEVEL5=""
#case "$(runlevel)" in *\ 5) RUNLEVEL5="true" ;; esac
RUNLEVEL5="true"

XMODULE=""
#[ -f /etc/sysconfig/xserver ] && . /etc/sysconfig/xserver
#[ -f /etc/sysconfig/knoppix ] && . /etc/sysconfig/knoppix
xserver_file=/var/xserver
[ -e $xserver_file ] && . $xserver_file

#Variable BACKGROUND agafada del fitxer de configuració (diferents gustos de kademar)
# xsession_background="/usr/share/wallpapers/kademar.jpg"
[ -e /usr/share/kademar/config-livecd ] && . /usr/share/kademar/config-livecd
[ -e /usr/share/kademar/config ] && . /usr/share/kademar/config
[ -z "$xserver" ] && xserver="xorg"

xsesson_commands_file=/var/xsession-commands
xsesson_restart_file=/var/xsession-restart

if [ "$xserver" = "xorg" ]; then
XSERVER=Xorg
XCONFIG="/etc/X11/xorg.conf"
else
XSERVER=XFree86
XCONFIG="/etc/X11/XF86Config-4"
fi

KVER="`uname -r`"


#If image does not exists, make solid black as background
[ ! -e "$xsession_background" ] && 3="-solid black"

# See how we were called.
case "$1" in
start)
	rm -f $xsesson_restart_file
	# Don't start X if brltty is running!
	BPID="$(pidof brltty 2>/dev/null)"
	[ "$?" = "0" ] && exit 0
	
	echo "${CRE}${BLUE}$miss_engegant${NORMAL}"
		# Start daemons.
	REALMEM="$(cat /proc/meminfo | awk '/MemTotal/{print $2}')"
	if [ -n "$REALMEM" -a "$REALMEM" -lt 14000 ]; then
	echo "${BLUE}$miss_memoria${NORMAL}"
	echo "${BLUE}$miss_fi${NORMAL}"
	exit 1
	fi
	
	
	echo ""
	echo "	${NORMAL}$miss_engegant1${NORMAL}"
	
	ACCEL=""
	XOPTIONS=""
	
# 	DPI="-dpi 75"
 	#Utilitza els DPI si estan configurats
	DPI="`grep Xft.dpi: /etc/X11/Xresources/x11-common | sed 's/:/ /g' | awk ' { print $2 } '`"
	#Si no, posa els dpi a 75
	if [ -z "$DPI" ]; then
		DPI="-dpi 75"	
	else
		DPI="-dpi $DPI"
	fi
	
	NORESET=""
	[ -n "$XSERVER" -a -x "/usr/X11R6/bin/$XSERVER" ] && ACCEL="$XSERVER"
	[ -L /etc/X11/X ] && ACCEL="$ACCEL /etc/X11/X"
	
	if [ -n "$XMODULE" ]; then
		# All kernels: Load drm module
		for i in /lib/modules/"$KVER"/kernel/drivers/char/drm/*
		do
			case "$i" in *$XMODULE*) module="${i##*/}"; module="${module%%.*}"; modprobe ${module} >/dev/null 2>&1 ;; esac
		done
	fi
	
	for X in $ACCEL nv radeon ati vesa 
	do
		BPP="-bpp"
		case "$X" in
		*Xorg*)
			XCONFIG="/etc/X11/xorg.conf"
			BPP="-depth"
			NORESET="-noreset"
		;;
		*XFree86*)
			XCONFIG="/etc/X11/XF86Config-4"
			BPP="-depth"
			NORESET="-noreset"
		;;
		vesa|fbdev|nv|radeon|ati)
			echo XMODULE="$X" >> $xserver_file
			echo "${NORMAL}"
			echo -n "${BLUE}$miss_reintentant(${YELLOW}$X${GREEN})${NORMAL} "
			rm -f /etc/X11/xorg.conf /etc/X11/XF86Config-4
			/usr/share/kademar/scripts/engegada/xautoconf >/dev/null 2>&1
			X=Xorg
			[ "$xserver" = "xfree86" ] && X=XFree86
			BPP="-depth"; NORESET="-noreset"; XOPTIONS=""
		;;
		esac
		# Try hwsetup-generated flags first, if present
		$X $NORESET $XOPTIONS $DPI :0 2>/dev/null && break
		# Mostly failsafe probe fallbacks
		# Some cards prefer 16 bit, especially when low on mem or not SVGA,
		# so try this first.
		if $X $NORESET $BPP 16 $DPI :0 2>/dev/null || \
		$X $NORESET $BPP 24 $DPI :0 2>/dev/null || \
		$X $NORESET $BPP 32 $DPI :0 2>/dev/null || \
		$X $NORESET $BPP  8 $DPI :0 2>/dev/null; then break; fi
		echo -n "${BLUE}.${NORMAL}"
	done &
	sleep 2
	# Wait for X-Server startup
	for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20
	do
		found="true"
		# Startup Logo
		# DISPLAY=:0 xloadimage -center -onroot -border black \
		DISPLAY=:0 xloadimage -onroot -fullscreen -shrink -smooth -border black -quiet $xsession_background >/dev/null 2>&1 && break
		found="false"
		sleep 1
	done
	echo ""
	
	if [ "$found" = "false" ]; then
	echo "${RED}$miss_noservidor${NORMAL}"
	exit 1
	fi
	
	# FIXME: Move to others
	
	rm -f $xsesson_commands_file
	touch $xsesson_commands_file
	chown $USER.$USER $xsesson_commands_file
	
	su -c "DISPLAY=:0 exec /usr/share/kademar/scripts/engegada/xsession-xinitrc" - $USER >/dev/null 2>&1
	RC="$?"
	
	XSESSION_COMMAND=$(cat $xsesson_commands_file) # Read in what kde / ... told us.
	
	# After xsession exits, end X-Server
	for i in $ACCEL $X $XSERVER Xorg XFree86
	do
		killall -TERM $i 2>/dev/null && break
	done
	
	echo ""
	echo -n "${CRE}${BLUE}$miss_acabat ${NORMAL}"
	if [ "$RC" = "0" ]; then
		echo "${BLUE}$miss_acabat_sense${NORMAL}"
		NEXT_RUNLEVEL=0
	
		[ "$DESKTOP" = "icewm" ] && NEXT_RUNLEVEL=0
	
		if [ -n "$XSESSION_COMMAND" ]; then
			case "$XSESSION_COMMAND" in
			shutdown*halt*)
				NEXT_RUNLEVEL=0
			;;
			shutdown*reboot*)
				NEXT_RUNLEVEL=6
			;;
			kde_restart)
				[ ! -f $xsesson_restart_file ] && exec $0 start
			;;
			esac
		fi
	
		if [ -n "$RUNLEVEL5" -a ! -f $xsesson_restart_file ]; then
		echo "${BLUE}$miss_apagant${NORMAL}"
			# Play informational sound if soundcore module present
			# (checking /dev/sndstat is unreliable)
			# OGGPLAY=/usr/bin/ogg123
			# PLAY=/usr/bin/wavp
			# [ -x "$PLAY" ] || PLAY=/usr/bin/play-sample
			# [ -x "$PLAY" ] || PLAY=/usr/bin/play
			# if [ -x "$OGGPLAY" -a -f /usr/share/sounds/shutdown.ogg ]; then
			# case "$(lsmod)" in *sound*) { $OGGPLAY -q -p 64 /usr/share/sounds/shutdown.ogg >/dev/null 2>&1 & } ; sleep 7 ;; esac
			# elif [ -f /usr/share/sounds/shutdown.wav -a -x "$PLAY" ]; then
			# case "$(lsmod)" in *sound*) { $PLAY /usr/share/sounds/shutdown.wav >/dev/null 2>&1 & } ; sleep 7 ;; esac
			# fi
			init $NEXT_RUNLEVEL
		fi
	else
		echo "${BLUE}$miss_acabat_amb${NORMAL}"
		echo "${RED}$miss_comprova1 $XCONFIG $miss_comprova2${NORMAL}"
		echo "   $0 start"
	fi
;;
stop)
	# Stop daemons.
	# Don't shutdown if killed by init or manually
	touch $xsesson_restart_file
	for i in $XSERVER; do
	killall -TERM $i 2>/dev/null && echo "${BLUE}$miss_finalitzar${NORMAL}" && break
	done
;;
restart)
	touch $xsesson_restart_file
	( nohup bash -c "$0 stop; sleep 5; $0 start" & )
;;
*)
	echo "${RED}$miss_us${NORMAL}"
	exit 1
;;
esac

exit 0
