Document: kademar-khronos-lite
Title: Debian kademar-khronos-lite Manual
Author: <insert document author here>
Abstract: This manual describes what kademar-khronos-lite is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/kademar-khronos-lite/kademar-khronos-lite.sgml.gz

Format: postscript
Files: /usr/share/doc/kademar-khronos-lite/kademar-khronos-lite.ps.gz

Format: text
Files: /usr/share/doc/kademar-khronos-lite/kademar-khronos-lite.text.gz

Format: HTML
Index: /usr/share/doc/kademar-khronos-lite/html/index.html
Files: /usr/share/doc/kademar-khronos-lite/html/*.html


