#!/bin/sh
#/etc/init.d/festival
#
# Init script for starting Festival as a system-wide server process.
#
# Written by David Huggins-Daines <dhd@cepstral.com>
# LSBINITInfo by Kartik Mistry <kartik.mistry@gmail.com>
# LSB logging functions by David Härdeman <david@hardeman.nu>

### BEGIN INIT INFO
# Provides:          heliox-services
# Required-Start:    $syslog dbus hal
# Required-Stop:     $syslog
# Should-Start:      $local_fs
# Should-Stop:       $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts heliox Accessibility/Screenread services
# Description:       Init script for screenread programs 
#                    system process
### END INIT INFO

NAME=heliox-services

# if [ -z "`grep adriane /proc/cmdline`" -a -z "`grep screenread /proc/cmdline`" ]; then
# 	echo "  *  NO Starting Adriane service (not request on cmdline)"
# 	exit 0
# fi

#speech-dispatcher
rm -fr "/var/log/speech-dispatcher" "/var/run/speech-dispatcher"
mkdir -p "/var/log/speech-dispatcher" "/var/run/speech-dispatcher"
chmod 777 "/var/log/speech-dispatcher" "/var/run/speech-dispatcher"

#user
[ "`ls /home/kademar 2>/dev/null`" ] && user=kademar
[ "`ls /home/Heliox 2>/dev/null`" ] && user=Heliox

[ -z "$user" ] && echo "No user found to start Heliox Services. Exiting " && exit 0


case "$1" in
  start)
  	echo " * Starting Heliox Services"
 	su -c "/etc/init.d/heliox-services.real start" - $user
    ;;
  stop)
  	echo " * Stopping Heliox Services"
	su -c "/etc/init.d/heliox-services.real stop" - $user
    ;;
  restart|reload|force-reload)
   echo " * Restarting Heliox services:"
    su -c "/etc/init.d/heliox-services.real stop" - $user
    sleep 3
    su -c "/etc/init.d/heliox-services.real start" - $user
    ;;
  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart}" >&2
    exit 2
    ;;
esac

exit 0
