#!/bin/bash 

#Elric Milon

# TODO arreglar el mode debug, actualment la ordre debug no la troba
# TODO arreglar el mount del common, dona error 
# TODO fer que funcioni encara que no tinguis el vi, o poguer escollir en el menu una petita interficie de configuracio
# TODO mirar de fer unes sources.list genèriques per no utilitzar les del sistema amfitrió 

##Carrego variables de config
. /usr/lib/kademar-scripts/sourcables/load_config




. /usr/lib/kademar-scripts/sourcables/pre_chroot

echo "


################################################
# ENTRADA AL SISTEMA DE FITXERS DEL CD EN VIU  #
################################################

Totes les modificacions i canvis que es facin
aquí, seran els que quedaràn en el CD.


Tecleja 'exit' per tal de sortir-ne


"

#Entrem en el sistema de fitxers del live-cd amb CHROOT
su - root -c "chroot $BURNIX_ROOT"


. /usr/lib/kademar-scripts/sourcables/post_chroot

date >> $DEVEL_ROOT/changelog
question Please, write log entry:
read LOG_ENTRY
echo $LOG_ENTRY >> $DEVEL_ROOT/changelog

echo "ok, tot correcte"



