#!/bin/bash 

#Elric Milon
#Adonay Sanz

###Carrego variables de config
. /usr/lib/kademar-scripts/sourcables/load_config 

tip Running clean script...

SCRIPT=`basename $CLEAN_SCRIPT`
rm -f $BURNIX_ROOT/root/$SCRIPT 2> /dev/null

if [ ! -z "$SACRED" ]; then 
	tip "This system is sacred, will not clean config files."
	echo "#!/bin/bash" > "$BURNIX_ROOT/root/$SCRIPT"
	echo "SACRED=$SACRED" >> "$BURNIX_ROOT/root/$SCRIPT"
fi

cat $CLEAN_SCRIPT >> $BURNIX_ROOT/root/$SCRIPT || exit 1

#Just in case $BURNIX_ROOT/root/ points to /root
if [ -f "/root/$SCRIPT" ]; then
	error "/root/$SCRIPT exists!!!!"
	errot "exiting just in case \$BURNIX_ROOT is not correctly set..."
	exit 666
fi

chmod +x $BURNIX_ROOT/root/$SCRIPT > /dev/null || exit 2

cd $BURNIX_ROOT


#pwd	
chroot . /root/$SCRIPT > /dev/null || exit 9
rm -f  root/$SCRIPT  > /dev/null


tip "Removing /root folder and replacing by /home/kademar"
rm -fr $BURNIX_ROOT/root/*
rm -fr $BURNIX_ROOT/root/.??*
cp -a  $BURNIX_ROOT/home/kademar/* $BURNIX_ROOT/root/
cp -a  $BURNIX_ROOT/home/kademar/.??* $BURNIX_ROOT/root/
chmod 700 /root
chmod 700 -R /root



if [ ! -z "$SERVICES_TO_REMOVE" ]; then

	tip "Deleting unwanted services"

	for i in $SERVICES_TO_REMOVE
	do	
		tip "	Deleting: $i"
		rm -f $BURNIX_ROOT/etc/rc?.d/???$i  2>/dev/null
	done
fi

ok Done.
