#!/bin/bash 

#Elric Milon
#Adonay Sanz

. /usr/lib/kademar-scripts/sourcables/load_config

#Check if /etc/hosts exists. If it doesn't exist, we create it
if [ ! -e $BURNIX_ROOT/etc/hosts ]; then 
echo "127.0.0.1 $LIVECD_HOST_NAME localhost" > $BURNIX_ROOT/etc/hosts
cat >> $BURNIX_ROOT/etc/hosts << "EOF"

# The following lines are desirable for IPv6 capable hosts
# (added automatically by netbase upgrade)

::1    ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
EOF
fi

#Chmod correct mode to  /usr/bin/sudo
# chmod 4755 $BURNIX_ROOT/usr/bin/sudo
# chown root.root $BURNIX_ROOT/usr/bin/sudo

#Chmod correct user to
#chmod 4710 $BURNIX_ROOT/usr/bin/cdrecord.mmap
#chmod 4710 $BURNIX_ROOT/usr/bin/cdrdao
#chown root.users $BURNIX_ROOT/usr/bin/cdrecord*

# squash variable given from config file
#Support to mksquash-lzma
if [ -e /usr/bin/mksquashfs-lzma ]; then
	if [ "$SQUASH" = lzma ]; then
		SQUASHER=mksquashfs-lzma
	else
		SQUASHER=mksquashfs
	fi
else
	SQUASHER=mksquashfs
fi
if [ -e /usr/bin/mksquashfs-xz ]; then
	if [ "$SQUASH" = xz ]; then
		SQUASHER=mksquashfs-xz
		COMP="-comp xz"
	else
		SQUASHER=mksquashfs
	fi
else
	SQUASHER=mksquashfs
fi


mkdir -p $MASTER_ROOT/kademar/base/

#Define SQUASHIMAGE_PATH variable
SQUASHIMAGE_PATH=$MASTER_ROOT/kademar/base/kademar.lzm

#If SQUASHIMAGE_PATH exists, remove it
[ -e $SQUASHIMAGE_PATH ] && rm -f $SQUASHIMAGE_PATH

#support to block size
[ -n "$SQUASH_BLOCK_SIZE" ] && SQUASH_BLOCK_SIZE="-b $SQUASH_BLOCK_SIZE"

#Warn what's the squasher
tip "Compressing with: $SQUASHER"

#Create squashfs image, with final live-cd filesystem
$SQUASHER $BURNIX_ROOT $SQUASHIMAGE_PATH $SQUASH_BLOCK_SIZE $COMP

