#!/bin/bash

#Elric Milon
#Adonay Sanz

if [ -n "`whereis qemu | sed s/"qemu: "//g`" ]; then
	sudo umount /dev/shm 2>/dev/null
	sudo mount -t tmpfs -o size=144m none /dev/shm
	. /usr/lib/kademar-scripts/sourcables/load_config
	echo "loading: $ISO_DIR/kademar-last.iso in Qemu"
	qemu -cdrom $ISO_DIR/kademar-last.iso
	sudo umount /dev/shm

else
	error "$start_qemu_error"
fi