#!/bin/bash

#Elric Milon
#Adonay Sanz

if [ -n "`which qemu`" ]; then
	sudo umount /dev/shm 2>/dev/null
	sudo mount -t tmpfs -o size=144m none /dev/shm
	. /usr/lib/kademar-scripts/sourcables/load_config
	echo "loading: $ISO_DIR/kademar-last.iso in Qemu"
        [ "`arch`" = "x86_64" ] && arch="-system-x86_64"
	qemu$arch -cdrom $ISO_DIR/kademar-last.iso
	sudo umount /dev/shm

else
	error "$start_qemu_error"
fi
