Document: kademar-scripts
Title: Debian kademar-scripts Manual
Author: <insert document author here>
Abstract: This manual describes what kademar-scripts is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/kademar-scripts/kademar-scripts.sgml.gz

Format: postscript
Files: /usr/share/doc/kademar-scripts/kademar-scripts.ps.gz

Format: text
Files: /usr/share/doc/kademar-scripts/kademar-scripts.text.gz

Format: HTML
Index: /usr/share/doc/kademar-scripts/html/index.html
Files: /usr/share/doc/kademar-scripts/html/*.html

  
