Document: cadi
Title: Debian cadi Manual
Author: <insert document author here>
Abstract: This manual describes what cadi is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/cadi/cadi.sgml.gz

Format: postscript
Files: /usr/share/doc/cadi/cadi.ps.gz

Format: text
Files: /usr/share/doc/cadi/cadi.text.gz

Format: HTML
Index: /usr/share/doc/cadi/html/index.html
Files: /usr/share/doc/cadi/html/*.html


