# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/cadi3.ui'
#
# Created: Sat Dec 26 04:03:33 2009
#      by: PyQt4 UI code generator 4.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_FormCadi(object):
    def setupUi(self, FormCadi):
        FormCadi.setObjectName("FormCadi")
        FormCadi.resize(640,480)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/cadi.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        FormCadi.setWindowIcon(icon)
        self.l_fons = QtGui.QLabel(FormCadi)
        self.l_fons.setGeometry(QtCore.QRect(-1,0,640,480))
        self.l_fons.setPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/bg/cadi.png"))
        self.l_fons.setObjectName("l_fons")
        self.pages = QtGui.QStackedWidget(FormCadi)
        self.pages.setGeometry(QtCore.QRect(150,60,491,421))
        self.pages.setObjectName("pages")
        self.tab_software = QtGui.QWidget()
        self.tab_software.setObjectName("tab_software")
        self.b_synaptic = QtGui.QPushButton(self.tab_software)
        self.b_synaptic.setGeometry(QtCore.QRect(50,100,281,41))
        self.b_synaptic.setObjectName("b_synaptic")
        self.b_preferencies_sistema = QtGui.QPushButton(self.tab_software)
        self.b_preferencies_sistema.setGeometry(QtCore.QRect(50,170,281,41))
        self.b_preferencies_sistema.setObjectName("b_preferencies_sistema")
        self.label_4 = QtGui.QLabel(self.tab_software)
        self.label_4.setGeometry(QtCore.QRect(220,50,91,21))
        self.label_4.setObjectName("label_4")
        self.pages.addWidget(self.tab_software)
        self.tab_hardware = QtGui.QWidget()
        self.tab_hardware.setObjectName("tab_hardware")
        self.label_5 = QtGui.QLabel(self.tab_hardware)
        self.label_5.setGeometry(QtCore.QRect(220,50,91,21))
        self.label_5.setObjectName("label_5")
        self.b_bluetooth = QtGui.QPushButton(self.tab_hardware)
        self.b_bluetooth.setGeometry(QtCore.QRect(50,170,280,41))
        self.b_bluetooth.setObjectName("b_bluetooth")
        self.b_impressores = QtGui.QPushButton(self.tab_hardware)
        self.b_impressores.setGeometry(QtCore.QRect(50,100,281,41))
        self.b_impressores.setObjectName("b_impressores")
        self.b_kinfocenter = QtGui.QPushButton(self.tab_hardware)
        self.b_kinfocenter.setGeometry(QtCore.QRect(50,310,280,41))
        self.b_kinfocenter.setObjectName("b_kinfocenter")
        self.b_teclats_multimedia = QtGui.QPushButton(self.tab_hardware)
        self.b_teclats_multimedia.setGeometry(QtCore.QRect(50,240,280,41))
        self.b_teclats_multimedia.setObjectName("b_teclats_multimedia")
        self.pages.addWidget(self.tab_hardware)
        self.tab_xarxa = QtGui.QWidget()
        self.tab_xarxa.setObjectName("tab_xarxa")
        self.b_wifi = QtGui.QPushButton(self.tab_xarxa)
        self.b_wifi.setGeometry(QtCore.QRect(50,100,281,41))
        self.b_wifi.setObjectName("b_wifi")
        self.b_eth = QtGui.QPushButton(self.tab_xarxa)
        self.b_eth.setGeometry(QtCore.QRect(50,170,281,41))
        self.b_eth.setObjectName("b_eth")
        self.label_6 = QtGui.QLabel(self.tab_xarxa)
        self.label_6.setGeometry(QtCore.QRect(220,50,91,21))
        self.label_6.setObjectName("label_6")
        self.b_gprs = QtGui.QPushButton(self.tab_xarxa)
        self.b_gprs.setGeometry(QtCore.QRect(50,310,280,41))
        self.b_gprs.setObjectName("b_gprs")
        self.b_modem = QtGui.QPushButton(self.tab_xarxa)
        self.b_modem.setGeometry(QtCore.QRect(50,240,281,41))
        self.b_modem.setObjectName("b_modem")
        self.b_adsl = QtGui.QPushButton(self.tab_xarxa)
        self.b_adsl.setGeometry(QtCore.QRect(50,380,280,41))
        self.b_adsl.setObjectName("b_adsl")
        self.pages.addWidget(self.tab_xarxa)
        self.tab_principal = QtGui.QWidget()
        self.tab_principal.setObjectName("tab_principal")
        self.frame = QtGui.QFrame(self.tab_principal)
        self.frame.setGeometry(QtCore.QRect(60,80,351,321))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.l_ver = QtGui.QLabel(self.frame)
        self.l_ver.setGeometry(QtCore.QRect(150,73,91,16))
        self.l_ver.setObjectName("l_ver")
        self.l_tipu = QtGui.QLabel(self.frame)
        self.l_tipu.setGeometry(QtCore.QRect(150,53,81,16))
        self.l_tipu.setObjectName("l_tipu")
        self.l_kdm = QtGui.QLabel(self.frame)
        self.l_kdm.setGeometry(QtCore.QRect(150,33,91,16))
        self.l_kdm.setObjectName("l_kdm")
        self.l_ram = QtGui.QLabel(self.frame)
        self.l_ram.setGeometry(QtCore.QRect(70,250,241,16))
        self.l_ram.setObjectName("l_ram")
        self.label_8 = QtGui.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(20,35,109,85))
        self.label_8.setPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/pc.png"))
        self.label_8.setObjectName("label_8")
        self.l_kern = QtGui.QLabel(self.frame)
        self.l_kern.setGeometry(QtCore.QRect(150,92,121,16))
        self.l_kern.setTextFormat(QtCore.Qt.PlainText)
        self.l_kern.setObjectName("l_kern")
        self.label_9 = QtGui.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(10,240,51,48))
        self.label_9.setPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/mem.png"))
        self.label_9.setObjectName("label_9")
        self.l_cpuinfo = QtGui.QLabel(self.frame)
        self.l_cpuinfo.setGeometry(QtCore.QRect(70,184,241,31))
        self.l_cpuinfo.setObjectName("l_cpuinfo")
        self.l_cpu = QtGui.QLabel(self.frame)
        self.l_cpu.setGeometry(QtCore.QRect(70,164,241,16))
        self.l_cpu.setObjectName("l_cpu")
        self.l_host = QtGui.QLabel(self.frame)
        self.l_host.setGeometry(QtCore.QRect(150,110,91,16))
        self.l_host.setObjectName("l_host")
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10,164,51,48))
        self.label_2.setPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/cpu.png"))
        self.label_2.setObjectName("label_2")
        self.label_10 = QtGui.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(130,13,71,16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.pages.addWidget(self.tab_principal)
        self.tab_sistema = QtGui.QWidget()
        self.tab_sistema.setObjectName("tab_sistema")
        self.b_samba = QtGui.QPushButton(self.tab_sistema)
        self.b_samba.setGeometry(QtCore.QRect(50,150,281,41))
        self.b_samba.setObjectName("b_samba")
        self.label_7 = QtGui.QLabel(self.tab_sistema)
        self.label_7.setGeometry(QtCore.QRect(220,50,91,21))
        self.label_7.setObjectName("label_7")
        self.b_grub = QtGui.QPushButton(self.tab_sistema)
        self.b_grub.setGeometry(QtCore.QRect(50,420,280,41))
        self.b_grub.setObjectName("b_grub")
        self.b_serveis = QtGui.QPushButton(self.tab_sistema)
        self.b_serveis.setGeometry(QtCore.QRect(50,290,280,41))
        self.b_serveis.setObjectName("b_serveis")
        self.pushButton_10 = QtGui.QPushButton(self.tab_sistema)
        self.pushButton_10.setGeometry(QtCore.QRect(50,220,280,41))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtGui.QPushButton(self.tab_sistema)
        self.pushButton_11.setGeometry(QtCore.QRect(50,360,280,40))
        self.pushButton_11.setObjectName("pushButton_11")
        self.b_sistema_grafic = QtGui.QPushButton(self.tab_sistema)
        self.b_sistema_grafic.setGeometry(QtCore.QRect(50,80,281,41))
        self.b_sistema_grafic.setObjectName("b_sistema_grafic")
        self.pages.addWidget(self.tab_sistema)
        self.l_kademar = QtGui.QLabel(FormCadi)
        self.l_kademar.setGeometry(QtCore.QRect(15,7,110,80))
        self.l_kademar.setPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/kademar.png"))
        self.l_kademar.setObjectName("l_kademar")
        self.b_software = QtGui.QPushButton(FormCadi)
        self.b_software.setGeometry(QtCore.QRect(20,140,101,41))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/software.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.b_software.setIcon(icon)
        self.b_software.setIconSize(QtCore.QSize(32,32))
        self.b_software.setObjectName("b_software")
        self.b_hardware = QtGui.QPushButton(FormCadi)
        self.b_hardware.setGeometry(QtCore.QRect(20,190,101,41))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/hardware.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.b_hardware.setIcon(icon)
        self.b_hardware.setIconSize(QtCore.QSize(32,32))
        self.b_hardware.setObjectName("b_hardware")
        self.b_xarxa = QtGui.QPushButton(FormCadi)
        self.b_xarxa.setGeometry(QtCore.QRect(20,240,101,41))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/xarxa.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.b_xarxa.setIcon(icon)
        self.b_xarxa.setIconSize(QtCore.QSize(32,32))
        self.b_xarxa.setObjectName("b_xarxa")
        self.b_sistema = QtGui.QPushButton(FormCadi)
        self.b_sistema.setGeometry(QtCore.QRect(20,290,101,41))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/sistema.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.b_sistema.setIcon(icon)
        self.b_sistema.setIconSize(QtCore.QSize(32,32))
        self.b_sistema.setObjectName("b_sistema")
        self.b_root = QtGui.QPushButton(FormCadi)
        self.b_root.setGeometry(QtCore.QRect(10,420,121,41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.b_root.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/root.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.b_root.setIcon(icon)
        self.b_root.setIconSize(QtCore.QSize(28,28))
        self.b_root.setObjectName("b_root")
        self.label_3 = QtGui.QLabel(FormCadi)
        self.label_3.setGeometry(QtCore.QRect(10,370,101,20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_11 = QtGui.QLabel(FormCadi)
        self.label_11.setGeometry(QtCore.QRect(30,390,91,20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label = QtGui.QLabel(FormCadi)
        self.label.setGeometry(QtCore.QRect(180,20,361,31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(13)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_12 = QtGui.QLabel(FormCadi)
        self.label_12.setGeometry(QtCore.QRect(550,30,61,51))
        self.label_12.setPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/user-password.png"))
        self.label_12.setObjectName("label_12")

        self.retranslateUi(FormCadi)
        self.pages.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(FormCadi)

    def retranslateUi(self, FormCadi):
        FormCadi.setWindowTitle(QtGui.QApplication.translate("FormCadi", "CADI", None, QtGui.QApplication.UnicodeUTF8))
        self.b_synaptic.setText(QtGui.QApplication.translate("FormCadi", "Synaptic - Gestió de programes", None, QtGui.QApplication.UnicodeUTF8))
        self.b_preferencies_sistema.setText(QtGui.QApplication.translate("FormCadi", "Preferències Generals del Sistema", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("FormCadi", "Software", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("FormCadi", "Hardware", None, QtGui.QApplication.UnicodeUTF8))
        self.b_bluetooth.setText(QtGui.QApplication.translate("FormCadi", "Bluetooth", None, QtGui.QApplication.UnicodeUTF8))
        self.b_impressores.setText(QtGui.QApplication.translate("FormCadi", "Impressores", None, QtGui.QApplication.UnicodeUTF8))
        self.b_kinfocenter.setText(QtGui.QApplication.translate("FormCadi", "Informació de Sistema", None, QtGui.QApplication.UnicodeUTF8))
        self.b_teclats_multimedia.setText(QtGui.QApplication.translate("FormCadi", "Teclats Multimèdia", None, QtGui.QApplication.UnicodeUTF8))
        self.b_wifi.setText(QtGui.QApplication.translate("FormCadi", "Sense Fils - Wifi", None, QtGui.QApplication.UnicodeUTF8))
        self.b_eth.setText(QtGui.QApplication.translate("FormCadi", "Tarja de Xarxa", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("FormCadi", "Xarxa", None, QtGui.QApplication.UnicodeUTF8))
        self.b_gprs.setText(QtGui.QApplication.translate("FormCadi", "GPRS", None, QtGui.QApplication.UnicodeUTF8))
        self.b_modem.setText(QtGui.QApplication.translate("FormCadi", "Modem", None, QtGui.QApplication.UnicodeUTF8))
        self.b_adsl.setText(QtGui.QApplication.translate("FormCadi", "ADSL/PPoE", None, QtGui.QApplication.UnicodeUTF8))
        self.l_ver.setText(QtGui.QApplication.translate("FormCadi", "versio", None, QtGui.QApplication.UnicodeUTF8))
        self.l_tipu.setText(QtGui.QApplication.translate("FormCadi", "tipus", None, QtGui.QApplication.UnicodeUTF8))
        self.l_kdm.setText(QtGui.QApplication.translate("FormCadi", "kdm", None, QtGui.QApplication.UnicodeUTF8))
        self.l_ram.setText(QtGui.QApplication.translate("FormCadi", "RAM", None, QtGui.QApplication.UnicodeUTF8))
        self.l_kern.setText(QtGui.QApplication.translate("FormCadi", "kernel", None, QtGui.QApplication.UnicodeUTF8))
        self.l_cpuinfo.setText(QtGui.QApplication.translate("FormCadi", "CPU info", None, QtGui.QApplication.UnicodeUTF8))
        self.l_cpu.setText(QtGui.QApplication.translate("FormCadi", "CPU", None, QtGui.QApplication.UnicodeUTF8))
        self.l_host.setText(QtGui.QApplication.translate("FormCadi", "hostname", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("FormCadi", "Sistema:", None, QtGui.QApplication.UnicodeUTF8))
        self.b_samba.setText(QtGui.QApplication.translate("FormCadi", "Samba - Compartir Fitxers", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("FormCadi", "Sistema", None, QtGui.QApplication.UnicodeUTF8))
        self.b_grub.setText(QtGui.QApplication.translate("FormCadi", "Restauració d\'engegada - GRUB", None, QtGui.QApplication.UnicodeUTF8))
        self.b_serveis.setText(QtGui.QApplication.translate("FormCadi", "Activacio de Serveis", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_10.setText(QtGui.QApplication.translate("FormCadi", "Gestión de los Usuarios", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_11.setText(QtGui.QApplication.translate("FormCadi", "Configuración del Idioma", None, QtGui.QApplication.UnicodeUTF8))
        self.b_sistema_grafic.setText(QtGui.QApplication.translate("FormCadi", "Sistema gràfic", None, QtGui.QApplication.UnicodeUTF8))
        self.b_software.setText(QtGui.QApplication.translate("FormCadi", "Software", None, QtGui.QApplication.UnicodeUTF8))
        self.b_hardware.setText(QtGui.QApplication.translate("FormCadi", "Hardware", None, QtGui.QApplication.UnicodeUTF8))
        self.b_xarxa.setText(QtGui.QApplication.translate("FormCadi", "Xarxa", None, QtGui.QApplication.UnicodeUTF8))
        self.b_sistema.setText(QtGui.QApplication.translate("FormCadi", "Sistema", None, QtGui.QApplication.UnicodeUTF8))
        self.b_root.setText(QtGui.QApplication.translate("FormCadi", "Administrador", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("FormCadi", "Ejecutando en:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("FormCadi", "Modo Usuario", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("FormCadi", "CADI: La Herramienta de Configuración", None, QtGui.QApplication.UnicodeUTF8))

