# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/cadi.ui'
#
# Created: Sat Dec 26 04:03:34 2009
#      by: PyQt4 UI code generator 4.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_FormCadi(object):
    def setupUi(self, FormCadi):
        FormCadi.setObjectName("FormCadi")
        FormCadi.resize(800,602)
        FormCadi.setMinimumSize(QtCore.QSize(800,602))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/cadi.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        FormCadi.setWindowIcon(icon)
        self.l_fons = QtGui.QLabel(FormCadi)
        self.l_fons.setGeometry(QtCore.QRect(0,0,800,600))
        self.l_fons.setPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/bg/cadi.png"))
        self.l_fons.setScaledContents(True)
        self.l_fons.setObjectName("l_fons")
        self.pages = QtGui.QStackedWidget(FormCadi)
        self.pages.setGeometry(QtCore.QRect(240,80,491,481))
        self.pages.setObjectName("pages")
        self.tab_principal = QtGui.QWidget()
        self.tab_principal.setObjectName("tab_principal")
        self.frame = QtGui.QFrame(self.tab_principal)
        self.frame.setGeometry(QtCore.QRect(30,80,441,371))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.l_ver = QtGui.QLabel(self.frame)
        self.l_ver.setGeometry(QtCore.QRect(150,73,271,16))
        self.l_ver.setObjectName("l_ver")
        self.l_tipu = QtGui.QLabel(self.frame)
        self.l_tipu.setGeometry(QtCore.QRect(150,53,271,16))
        self.l_tipu.setObjectName("l_tipu")
        self.l_kdm = QtGui.QLabel(self.frame)
        self.l_kdm.setGeometry(QtCore.QRect(150,33,271,16))
        self.l_kdm.setObjectName("l_kdm")
        self.l_ram = QtGui.QLabel(self.frame)
        self.l_ram.setGeometry(QtCore.QRect(70,250,361,16))
        self.l_ram.setObjectName("l_ram")
        self.label_8 = QtGui.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(20,35,109,85))
        self.label_8.setPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/pc.png"))
        self.label_8.setObjectName("label_8")
        self.l_kern = QtGui.QLabel(self.frame)
        self.l_kern.setGeometry(QtCore.QRect(150,92,281,16))
        self.l_kern.setTextFormat(QtCore.Qt.PlainText)
        self.l_kern.setObjectName("l_kern")
        self.label_9 = QtGui.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(10,240,51,48))
        self.label_9.setPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/mem.png"))
        self.label_9.setObjectName("label_9")
        self.l_cpuinfo = QtGui.QLabel(self.frame)
        self.l_cpuinfo.setGeometry(QtCore.QRect(70,184,361,31))
        self.l_cpuinfo.setObjectName("l_cpuinfo")
        self.l_cpu = QtGui.QLabel(self.frame)
        self.l_cpu.setGeometry(QtCore.QRect(70,164,361,16))
        self.l_cpu.setObjectName("l_cpu")
        self.l_host = QtGui.QLabel(self.frame)
        self.l_host.setGeometry(QtCore.QRect(150,110,281,16))
        self.l_host.setObjectName("l_host")
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(0,150,61,61))
        self.label_2.setPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/cpu.png"))
        self.label_2.setObjectName("label_2")
        self.label_10 = QtGui.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(130,13,71,16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label = QtGui.QLabel(self.tab_principal)
        self.label.setGeometry(QtCore.QRect(30,20,441,31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(15)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pages.addWidget(self.tab_principal)
        self.tab_software = QtGui.QWidget()
        self.tab_software.setObjectName("tab_software")
        self.b_synaptic = QtGui.QPushButton(self.tab_software)
        self.b_synaptic.setGeometry(QtCore.QRect(50,70,351,51))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/synaptic.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.b_synaptic.setIcon(icon)
        self.b_synaptic.setIconSize(QtCore.QSize(32,32))
        self.b_synaptic.setObjectName("b_synaptic")
        self.b_preferencies_sistema = QtGui.QPushButton(self.tab_software)
        self.b_preferencies_sistema.setGeometry(QtCore.QRect(50,150,351,51))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/preferences_system_login.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.b_preferencies_sistema.setIcon(icon)
        self.b_preferencies_sistema.setIconSize(QtCore.QSize(32,32))
        self.b_preferencies_sistema.setObjectName("b_preferencies_sistema")
        self.label_4 = QtGui.QLabel(self.tab_software)
        self.label_4.setGeometry(QtCore.QRect(50,10,341,21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.pages.addWidget(self.tab_software)
        self.tab_hardware = QtGui.QWidget()
        self.tab_hardware.setObjectName("tab_hardware")
        self.label_5 = QtGui.QLabel(self.tab_hardware)
        self.label_5.setGeometry(QtCore.QRect(50,10,341,21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setWeight(75)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.b_bluetooth = QtGui.QPushButton(self.tab_hardware)
        self.b_bluetooth.setGeometry(QtCore.QRect(50,150,351,51))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/bluetooth.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.b_bluetooth.setIcon(icon)
        self.b_bluetooth.setIconSize(QtCore.QSize(32,32))
        self.b_bluetooth.setObjectName("b_bluetooth")
        self.b_impressores = QtGui.QPushButton(self.tab_hardware)
        self.b_impressores.setGeometry(QtCore.QRect(50,70,351,51))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/printer1.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.b_impressores.setIcon(icon)
        self.b_impressores.setIconSize(QtCore.QSize(32,32))
        self.b_impressores.setObjectName("b_impressores")
        self.b_kinfocenter = QtGui.QPushButton(self.tab_hardware)
        self.b_kinfocenter.setGeometry(QtCore.QRect(50,310,351,51))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/system-information.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.b_kinfocenter.setIcon(icon)
        self.b_kinfocenter.setIconSize(QtCore.QSize(32,32))
        self.b_kinfocenter.setObjectName("b_kinfocenter")
        self.b_teclats_multimedia = QtGui.QPushButton(self.tab_hardware)
        self.b_teclats_multimedia.setGeometry(QtCore.QRect(50,230,351,51))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/keyboard.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.b_teclats_multimedia.setIcon(icon)
        self.b_teclats_multimedia.setIconSize(QtCore.QSize(32,32))
        self.b_teclats_multimedia.setObjectName("b_teclats_multimedia")
        self.b_ndiswrapper = QtGui.QPushButton(self.tab_hardware)
        self.b_ndiswrapper.setGeometry(QtCore.QRect(50,390,351,51))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/network-wireless.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.b_ndiswrapper.setIcon(icon)
        self.b_ndiswrapper.setIconSize(QtCore.QSize(32,32))
        self.b_ndiswrapper.setObjectName("b_ndiswrapper")
        self.pages.addWidget(self.tab_hardware)
        self.tab_xarxa = QtGui.QWidget()
        self.tab_xarxa.setObjectName("tab_xarxa")
        self.b_internet = QtGui.QPushButton(self.tab_xarxa)
        self.b_internet.setGeometry(QtCore.QRect(50,90,351,51))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/network.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.b_internet.setIcon(icon)
        self.b_internet.setIconSize(QtCore.QSize(32,32))
        self.b_internet.setObjectName("b_internet")
        self.b_modem = QtGui.QPushButton(self.tab_xarxa)
        self.b_modem.setGeometry(QtCore.QRect(50,170,351,51))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/router.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.b_modem.setIcon(icon)
        self.b_modem.setIconSize(QtCore.QSize(32,32))
        self.b_modem.setObjectName("b_modem")
        self.label_6 = QtGui.QLabel(self.tab_xarxa)
        self.label_6.setGeometry(QtCore.QRect(50,10,351,21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setWeight(75)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.b_pppoe = QtGui.QPushButton(self.tab_xarxa)
        self.b_pppoe.setGeometry(QtCore.QRect(50,250,351,51))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/pppoe.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.b_pppoe.setIcon(icon)
        self.b_pppoe.setIconSize(QtCore.QSize(32,32))
        self.b_pppoe.setObjectName("b_pppoe")
        self.b_gprs = QtGui.QPushButton(self.tab_xarxa)
        self.b_gprs.setGeometry(QtCore.QRect(50,330,351,51))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/gprs.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.b_gprs.setIcon(icon)
        self.b_gprs.setIconSize(QtCore.QSize(32,32))
        self.b_gprs.setObjectName("b_gprs")
        self.pages.addWidget(self.tab_xarxa)
        self.tab_sistema = QtGui.QWidget()
        self.tab_sistema.setObjectName("tab_sistema")
        self.label_7 = QtGui.QLabel(self.tab_sistema)
        self.label_7.setGeometry(QtCore.QRect(50,10,351,21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setWeight(75)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.b_grub = QtGui.QPushButton(self.tab_sistema)
        self.b_grub.setGeometry(QtCore.QRect(50,250,351,51))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/hdd.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.b_grub.setIcon(icon)
        self.b_grub.setIconSize(QtCore.QSize(32,32))
        self.b_grub.setObjectName("b_grub")
        self.b_services = QtGui.QPushButton(self.tab_sistema)
        self.b_services.setGeometry(QtCore.QRect(50,170,351,51))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/services.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.b_services.setIcon(icon)
        self.b_services.setIconSize(QtCore.QSize(32,32))
        self.b_services.setObjectName("b_services")
        self.b_users = QtGui.QPushButton(self.tab_sistema)
        self.b_users.setGeometry(QtCore.QRect(50,400,351,51))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/users.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.b_users.setIcon(icon)
        self.b_users.setIconSize(QtCore.QSize(32,32))
        self.b_users.setObjectName("b_users")
        self.b_language = QtGui.QPushButton(self.tab_sistema)
        self.b_language.setGeometry(QtCore.QRect(50,330,351,51))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/locale.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.b_language.setIcon(icon)
        self.b_language.setIconSize(QtCore.QSize(32,32))
        self.b_language.setObjectName("b_language")
        self.b_display_configuration = QtGui.QPushButton(self.tab_sistema)
        self.b_display_configuration.setGeometry(QtCore.QRect(50,90,351,51))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/display.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.b_display_configuration.setIcon(icon)
        self.b_display_configuration.setIconSize(QtCore.QSize(32,32))
        self.b_display_configuration.setObjectName("b_display_configuration")
        self.pages.addWidget(self.tab_sistema)
        self.l_kademar = QtGui.QLabel(FormCadi)
        self.l_kademar.setGeometry(QtCore.QRect(20,10,90,90))
        self.l_kademar.setPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/kademar.png"))
        self.l_kademar.setScaledContents(True)
        self.l_kademar.setObjectName("l_kademar")
        self.b_software = QtGui.QPushButton(FormCadi)
        self.b_software.setGeometry(QtCore.QRect(20,170,131,41))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/software.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.b_software.setIcon(icon)
        self.b_software.setIconSize(QtCore.QSize(32,32))
        self.b_software.setObjectName("b_software")
        self.b_hardware = QtGui.QPushButton(FormCadi)
        self.b_hardware.setGeometry(QtCore.QRect(20,230,131,41))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/hardware.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.b_hardware.setIcon(icon)
        self.b_hardware.setIconSize(QtCore.QSize(32,32))
        self.b_hardware.setObjectName("b_hardware")
        self.b_xarxa = QtGui.QPushButton(FormCadi)
        self.b_xarxa.setGeometry(QtCore.QRect(20,290,131,41))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/xarxa.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.b_xarxa.setIcon(icon)
        self.b_xarxa.setIconSize(QtCore.QSize(32,32))
        self.b_xarxa.setObjectName("b_xarxa")
        self.b_sistema = QtGui.QPushButton(FormCadi)
        self.b_sistema.setGeometry(QtCore.QRect(20,350,131,41))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/sistema.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.b_sistema.setIcon(icon)
        self.b_sistema.setIconSize(QtCore.QSize(32,32))
        self.b_sistema.setObjectName("b_sistema")
        self.b_root = QtGui.QPushButton(FormCadi)
        self.b_root.setGeometry(QtCore.QRect(20,540,121,41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.b_root.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/root.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.b_root.setIcon(icon)
        self.b_root.setIconSize(QtCore.QSize(28,28))
        self.b_root.setObjectName("b_root")
        self.label_3 = QtGui.QLabel(FormCadi)
        self.label_3.setGeometry(QtCore.QRect(10,460,101,20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_11 = QtGui.QLabel(FormCadi)
        self.label_11.setGeometry(QtCore.QRect(30,480,91,20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.b_sortir = QtGui.QPushButton(FormCadi)
        self.b_sortir.setGeometry(QtCore.QRect(20,540,121,41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.b_sortir.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/exit.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.b_sortir.setIcon(icon)
        self.b_sortir.setIconSize(QtCore.QSize(28,28))
        self.b_sortir.setObjectName("b_sortir")

        self.retranslateUi(FormCadi)
        self.pages.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(FormCadi)

    def retranslateUi(self, FormCadi):
        FormCadi.setWindowTitle(QtGui.QApplication.translate("FormCadi", "CADI", None, QtGui.QApplication.UnicodeUTF8))
        self.l_ver.setText(QtGui.QApplication.translate("FormCadi", "versio", None, QtGui.QApplication.UnicodeUTF8))
        self.l_tipu.setText(QtGui.QApplication.translate("FormCadi", "tipus", None, QtGui.QApplication.UnicodeUTF8))
        self.l_kdm.setText(QtGui.QApplication.translate("FormCadi", "kdm", None, QtGui.QApplication.UnicodeUTF8))
        self.l_ram.setText(QtGui.QApplication.translate("FormCadi", "RAM", None, QtGui.QApplication.UnicodeUTF8))
        self.l_kern.setText(QtGui.QApplication.translate("FormCadi", "kernel", None, QtGui.QApplication.UnicodeUTF8))
        self.l_cpuinfo.setText(QtGui.QApplication.translate("FormCadi", "CPU info", None, QtGui.QApplication.UnicodeUTF8))
        self.l_cpu.setText(QtGui.QApplication.translate("FormCadi", "CPU", None, QtGui.QApplication.UnicodeUTF8))
        self.l_host.setText(QtGui.QApplication.translate("FormCadi", "hostname", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("FormCadi", "Sistema:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("FormCadi", "CADI: The Configuration Center", None, QtGui.QApplication.UnicodeUTF8))
        self.b_synaptic.setText(QtGui.QApplication.translate("FormCadi", "Synaptic - Install/Remove Programs", None, QtGui.QApplication.UnicodeUTF8))
        self.b_preferencies_sistema.setText(QtGui.QApplication.translate("FormCadi", "General System Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("FormCadi", "Software", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("FormCadi", "Hardware", None, QtGui.QApplication.UnicodeUTF8))
        self.b_bluetooth.setText(QtGui.QApplication.translate("FormCadi", "Bluetooth", None, QtGui.QApplication.UnicodeUTF8))
        self.b_impressores.setText(QtGui.QApplication.translate("FormCadi", "Printers", None, QtGui.QApplication.UnicodeUTF8))
        self.b_kinfocenter.setText(QtGui.QApplication.translate("FormCadi", "System Information", None, QtGui.QApplication.UnicodeUTF8))
        self.b_teclats_multimedia.setText(QtGui.QApplication.translate("FormCadi", "Multimedia Keyboards", None, QtGui.QApplication.UnicodeUTF8))
        self.b_ndiswrapper.setText(QtGui.QApplication.translate("FormCadi", "Ndiswrapper - Wifi Not Recognized", None, QtGui.QApplication.UnicodeUTF8))
        self.b_internet.setText(QtGui.QApplication.translate("FormCadi", "Internet and Connectivity", None, QtGui.QApplication.UnicodeUTF8))
        self.b_modem.setText(QtGui.QApplication.translate("FormCadi", "Modem", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("FormCadi", "Network", None, QtGui.QApplication.UnicodeUTF8))
        self.b_pppoe.setText(QtGui.QApplication.translate("FormCadi", "ADSL/PPoE", None, QtGui.QApplication.UnicodeUTF8))
        self.b_gprs.setText(QtGui.QApplication.translate("FormCadi", "GPRS", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("FormCadi", "System", None, QtGui.QApplication.UnicodeUTF8))
        self.b_grub.setText(QtGui.QApplication.translate("FormCadi", "Restauració d\'engegada - GRUB", None, QtGui.QApplication.UnicodeUTF8))
        self.b_services.setText(QtGui.QApplication.translate("FormCadi", "System Services", None, QtGui.QApplication.UnicodeUTF8))
        self.b_users.setText(QtGui.QApplication.translate("FormCadi", "Manage Users", None, QtGui.QApplication.UnicodeUTF8))
        self.b_language.setText(QtGui.QApplication.translate("FormCadi", "System Language Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.b_display_configuration.setText(QtGui.QApplication.translate("FormCadi", "Display Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.b_software.setText(QtGui.QApplication.translate("FormCadi", "Software", None, QtGui.QApplication.UnicodeUTF8))
        self.b_hardware.setText(QtGui.QApplication.translate("FormCadi", "Hardware", None, QtGui.QApplication.UnicodeUTF8))
        self.b_xarxa.setText(QtGui.QApplication.translate("FormCadi", "Xarxa", None, QtGui.QApplication.UnicodeUTF8))
        self.b_sistema.setText(QtGui.QApplication.translate("FormCadi", "Sistema", None, QtGui.QApplication.UnicodeUTF8))
        self.b_root.setText(QtGui.QApplication.translate("FormCadi", "Administrador", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("FormCadi", "Ejecutando en:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("FormCadi", "Modo Usuario", None, QtGui.QApplication.UnicodeUTF8))
        self.b_sortir.setText(QtGui.QApplication.translate("FormCadi", "Exit", None, QtGui.QApplication.UnicodeUTF8))

