# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/cadi2.ui'
#
# Created: Sat Dec 26 04:03:33 2009
#      by: PyQt4 UI code generator 4.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(640,480)
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(-1,0,640,480))
        self.label_2.setPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/bg/instalador.png"))
        self.label_2.setObjectName("label_2")
        self.pageWidget = QtGui.QStackedWidget(Form)
        self.pageWidget.setGeometry(QtCore.QRect(150,0,491,481))
        self.pageWidget.setObjectName("pageWidget")
        self.software = QtGui.QWidget()
        self.software.setGeometry(QtCore.QRect(0,0,491,481))
        self.software.setObjectName("software")
        self.b_synaptic = QtGui.QPushButton(self.software)
        self.b_synaptic.setGeometry(QtCore.QRect(50,80,181,41))
        self.b_synaptic.setObjectName("b_synaptic")
        self.b_preferencies_sistema = QtGui.QPushButton(self.software)
        self.b_preferencies_sistema.setGeometry(QtCore.QRect(270,80,181,41))
        self.b_preferencies_sistema.setObjectName("b_preferencies_sistema")
        self.pushButton_4 = QtGui.QPushButton(self.software)
        self.pushButton_4.setGeometry(QtCore.QRect(270,150,181,41))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_3 = QtGui.QPushButton(self.software)
        self.pushButton_3.setGeometry(QtCore.QRect(50,150,181,41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_6 = QtGui.QPushButton(self.software)
        self.pushButton_6.setGeometry(QtCore.QRect(270,220,181,41))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_5 = QtGui.QPushButton(self.software)
        self.pushButton_5.setGeometry(QtCore.QRect(50,220,181,41))
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_4 = QtGui.QLabel(self.software)
        self.label_4.setGeometry(QtCore.QRect(220,30,91,21))
        self.label_4.setObjectName("label_4")
        self.pageWidget.addWidget(self.software)
        self.hardware = QtGui.QWidget()
        self.hardware.setGeometry(QtCore.QRect(0,0,491,481))
        self.hardware.setObjectName("hardware")
        self.label_5 = QtGui.QLabel(self.hardware)
        self.label_5.setGeometry(QtCore.QRect(220,30,91,21))
        self.label_5.setObjectName("label_5")
        self.b_bluetooth = QtGui.QPushButton(self.hardware)
        self.b_bluetooth.setGeometry(QtCore.QRect(50,150,181,41))
        self.b_bluetooth.setObjectName("b_bluetooth")
        self.pushButton_14 = QtGui.QPushButton(self.hardware)
        self.pushButton_14.setGeometry(QtCore.QRect(50,220,181,41))
        self.pushButton_14.setObjectName("pushButton_14")
        self.b_impressores = QtGui.QPushButton(self.hardware)
        self.b_impressores.setGeometry(QtCore.QRect(50,80,181,41))
        self.b_impressores.setObjectName("b_impressores")
        self.pushButton_16 = QtGui.QPushButton(self.hardware)
        self.pushButton_16.setGeometry(QtCore.QRect(270,220,181,41))
        self.pushButton_16.setObjectName("pushButton_16")
        self.b_kinfocenter = QtGui.QPushButton(self.hardware)
        self.b_kinfocenter.setGeometry(QtCore.QRect(270,150,181,41))
        self.b_kinfocenter.setObjectName("b_kinfocenter")
        self.b_teclats_multimedia = QtGui.QPushButton(self.hardware)
        self.b_teclats_multimedia.setGeometry(QtCore.QRect(270,80,181,41))
        self.b_teclats_multimedia.setObjectName("b_teclats_multimedia")
        self.pageWidget.addWidget(self.hardware)
        self.xarxa = QtGui.QWidget()
        self.xarxa.setGeometry(QtCore.QRect(0,0,491,481))
        self.xarxa.setObjectName("xarxa")
        self.b_wifi = QtGui.QPushButton(self.xarxa)
        self.b_wifi.setGeometry(QtCore.QRect(50,80,181,41))
        self.b_wifi.setObjectName("b_wifi")
        self.b_eth = QtGui.QPushButton(self.xarxa)
        self.b_eth.setGeometry(QtCore.QRect(270,80,181,41))
        self.b_eth.setObjectName("b_eth")
        self.pushButton_22 = QtGui.QPushButton(self.xarxa)
        self.pushButton_22.setGeometry(QtCore.QRect(270,220,181,41))
        self.pushButton_22.setObjectName("pushButton_22")
        self.label_6 = QtGui.QLabel(self.xarxa)
        self.label_6.setGeometry(QtCore.QRect(220,30,91,21))
        self.label_6.setObjectName("label_6")
        self.b_gprs = QtGui.QPushButton(self.xarxa)
        self.b_gprs.setGeometry(QtCore.QRect(50,220,181,41))
        self.b_gprs.setObjectName("b_gprs")
        self.b_modem = QtGui.QPushButton(self.xarxa)
        self.b_modem.setGeometry(QtCore.QRect(50,150,181,41))
        self.b_modem.setObjectName("b_modem")
        self.b_adsl = QtGui.QPushButton(self.xarxa)
        self.b_adsl.setGeometry(QtCore.QRect(270,150,181,41))
        self.b_adsl.setObjectName("b_adsl")
        self.pageWidget.addWidget(self.xarxa)
        self.sistema = QtGui.QWidget()
        self.sistema.setGeometry(QtCore.QRect(0,0,491,481))
        self.sistema.setObjectName("sistema")
        self.b_samba = QtGui.QPushButton(self.sistema)
        self.b_samba.setGeometry(QtCore.QRect(50,150,181,41))
        self.b_samba.setObjectName("b_samba")
        self.label_7 = QtGui.QLabel(self.sistema)
        self.label_7.setGeometry(QtCore.QRect(220,30,91,21))
        self.label_7.setObjectName("label_7")
        self.b_grub = QtGui.QPushButton(self.sistema)
        self.b_grub.setGeometry(QtCore.QRect(270,150,181,41))
        self.b_grub.setObjectName("b_grub")
        self.b_serveis = QtGui.QPushButton(self.sistema)
        self.b_serveis.setGeometry(QtCore.QRect(270,80,181,41))
        self.b_serveis.setObjectName("b_serveis")
        self.pushButton_10 = QtGui.QPushButton(self.sistema)
        self.pushButton_10.setGeometry(QtCore.QRect(50,220,181,41))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtGui.QPushButton(self.sistema)
        self.pushButton_11.setGeometry(QtCore.QRect(270,220,181,41))
        self.pushButton_11.setObjectName("pushButton_11")
        self.b_sistema_grafic = QtGui.QPushButton(self.sistema)
        self.b_sistema_grafic.setGeometry(QtCore.QRect(50,80,181,41))
        self.b_sistema_grafic.setObjectName("b_sistema_grafic")
        self.pageWidget.addWidget(self.sistema)
        self.listWidget = QtGui.QListWidget(Form)
        self.listWidget.setGeometry(QtCore.QRect(20,110,90,351))
        self.listWidget.setFrameShape(QtGui.QFrame.NoFrame)
        self.listWidget.setIconSize(QtCore.QSize(48,48))
        self.listWidget.setMovement(QtGui.QListView.Static)
        self.listWidget.setViewMode(QtGui.QListView.IconMode)
        self.listWidget.setObjectName("listWidget")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/software.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/hardware.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/xarxa.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/sistema.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.label_3 = QtGui.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(15,7,110,80))
        self.label_3.setPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/kademar.png"))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Form)
        self.pageWidget.setCurrentIndex(0)
        self.listWidget.setCurrentRow(-1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.b_synaptic.setText(QtGui.QApplication.translate("Form", "Synaptic - Gestió de programes", None, QtGui.QApplication.UnicodeUTF8))
        self.b_preferencies_sistema.setText(QtGui.QApplication.translate("Form", "Preferències Generals del Sistema", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setText(QtGui.QApplication.translate("Form", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("Form", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_6.setText(QtGui.QApplication.translate("Form", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_5.setText(QtGui.QApplication.translate("Form", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "Software", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "Hardware", None, QtGui.QApplication.UnicodeUTF8))
        self.b_bluetooth.setText(QtGui.QApplication.translate("Form", "Bluetooth", None, QtGui.QApplication.UnicodeUTF8))
        self.b_impressores.setText(QtGui.QApplication.translate("Form", "Impressores", None, QtGui.QApplication.UnicodeUTF8))
        self.b_kinfocenter.setText(QtGui.QApplication.translate("Form", "Informació de Sistema", None, QtGui.QApplication.UnicodeUTF8))
        self.b_teclats_multimedia.setText(QtGui.QApplication.translate("Form", "Teclats Multimèdia", None, QtGui.QApplication.UnicodeUTF8))
        self.b_wifi.setText(QtGui.QApplication.translate("Form", "Sense Fils - Wifi", None, QtGui.QApplication.UnicodeUTF8))
        self.b_eth.setText(QtGui.QApplication.translate("Form", "Tarja de Xarxa", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "Xarxa", None, QtGui.QApplication.UnicodeUTF8))
        self.b_gprs.setText(QtGui.QApplication.translate("Form", "GPRS", None, QtGui.QApplication.UnicodeUTF8))
        self.b_modem.setText(QtGui.QApplication.translate("Form", "Modem", None, QtGui.QApplication.UnicodeUTF8))
        self.b_adsl.setText(QtGui.QApplication.translate("Form", "ADSL/PPoE", None, QtGui.QApplication.UnicodeUTF8))
        self.b_samba.setText(QtGui.QApplication.translate("Form", "Samba - Compartir Fitxers", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form", "Sistema", None, QtGui.QApplication.UnicodeUTF8))
        self.b_grub.setText(QtGui.QApplication.translate("Form", "Restauració d\'engegada - GRUB", None, QtGui.QApplication.UnicodeUTF8))
        self.b_serveis.setText(QtGui.QApplication.translate("Form", "Activacio de Serveis", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_10.setText(QtGui.QApplication.translate("Form", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_11.setText(QtGui.QApplication.translate("Form", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.b_sistema_grafic.setText(QtGui.QApplication.translate("Form", "Sistema gràfic", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.clear()
        item = QtGui.QListWidgetItem(self.listWidget)
        item.setText(QtGui.QApplication.translate("Form", "Software", None, QtGui.QApplication.UnicodeUTF8))
        item.setIcon(icon)
        item1 = QtGui.QListWidgetItem(self.listWidget)
        item1.setText(QtGui.QApplication.translate("Form", "Hardware", None, QtGui.QApplication.UnicodeUTF8))
        item1.setIcon(icon)
        item2 = QtGui.QListWidgetItem(self.listWidget)
        item2.setText(QtGui.QApplication.translate("Form", "Xarxa", None, QtGui.QApplication.UnicodeUTF8))
        item2.setIcon(icon)
        item3 = QtGui.QListWidgetItem(self.listWidget)
        item3.setText(QtGui.QApplication.translate("Form", "Sistema", None, QtGui.QApplication.UnicodeUTF8))
        item3.setIcon(icon)

