# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/display.ui'
#
# Created: Sat Dec 26 04:03:34 2009
#      by: PyQt4 UI code generator 4.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_FormDisplay(object):
    def setupUi(self, FormDisplay):
        FormDisplay.setObjectName("FormDisplay")
        FormDisplay.resize(800,600)
        FormDisplay.setMinimumSize(QtCore.QSize(800,600))
        self.label_2 = QtGui.QLabel(FormDisplay)
        self.label_2.setGeometry(QtCore.QRect(0,0,800,600))
        self.label_2.setPixmap(QtGui.QPixmap("../../../../../../usr/share/kademar/utils/cadi/img/bg/cadi.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.pages = QtGui.QStackedWidget(FormDisplay)
        self.pages.setGeometry(QtCore.QRect(210,70,561,491))
        self.pages.setObjectName("pages")
        self.software = QtGui.QWidget()
        self.software.setObjectName("software")
        self.label_4 = QtGui.QLabel(self.software)
        self.label_4.setGeometry(QtCore.QRect(9,20,471,21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label = QtGui.QLabel(self.software)
        self.label.setGeometry(QtCore.QRect(40,70,411,41))
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.l_logo_blth = QtGui.QLabel(self.software)
        self.l_logo_blth.setGeometry(QtCore.QRect(30,110,100,100))
        self.l_logo_blth.setPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/display.png"))
        self.l_logo_blth.setScaledContents(True)
        self.l_logo_blth.setObjectName("l_logo_blth")
        self.groupBox = QtGui.QGroupBox(self.software)
        self.groupBox.setGeometry(QtCore.QRect(150,110,261,81))
        self.groupBox.setObjectName("groupBox")
        self.l_resolution = QtGui.QLabel(self.groupBox)
        self.l_resolution.setGeometry(QtCore.QRect(20,50,231,20))
        self.l_resolution.setAlignment(QtCore.Qt.AlignCenter)
        self.l_resolution.setObjectName("l_resolution")
        self.sldr_resol = QtGui.QSlider(self.groupBox)
        self.sldr_resol.setGeometry(QtCore.QRect(20,30,231,16))
        self.sldr_resol.setMaximum(2)
        self.sldr_resol.setPageStep(1)
        self.sldr_resol.setProperty("value",QtCore.QVariant(0))
        self.sldr_resol.setOrientation(QtCore.Qt.Horizontal)
        self.sldr_resol.setInvertedAppearance(True)
        self.sldr_resol.setTickPosition(QtGui.QSlider.TicksBelow)
        self.sldr_resol.setObjectName("sldr_resol")
        self.groupBox_2 = QtGui.QGroupBox(self.software)
        self.groupBox_2.setGeometry(QtCore.QRect(170,220,211,81))
        self.groupBox_2.setObjectName("groupBox_2")
        self.cb_depth = QtGui.QComboBox(self.groupBox_2)
        self.cb_depth.setGeometry(QtCore.QRect(30,30,141,25))
        self.cb_depth.setObjectName("cb_depth")
        self.cb_forceResol = QtGui.QCheckBox(self.software)
        self.cb_forceResol.setGeometry(QtCore.QRect(420,120,121,71))
        self.cb_forceResol.setObjectName("cb_forceResol")
        self.groupBox_3 = QtGui.QGroupBox(self.software)
        self.groupBox_3.setGeometry(QtCore.QRect(170,330,211,81))
        self.groupBox_3.setObjectName("groupBox_3")
        self.cb_dpi = QtGui.QComboBox(self.groupBox_3)
        self.cb_dpi.setGeometry(QtCore.QRect(30,30,141,25))
        self.cb_dpi.setObjectName("cb_dpi")
        self.l_logo_blth_2 = QtGui.QLabel(self.software)
        self.l_logo_blth_2.setGeometry(QtCore.QRect(40,225,80,80))
        self.l_logo_blth_2.setPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/color.png"))
        self.l_logo_blth_2.setScaledContents(True)
        self.l_logo_blth_2.setObjectName("l_logo_blth_2")
        self.l_logo_blth_3 = QtGui.QLabel(self.software)
        self.l_logo_blth_3.setGeometry(QtCore.QRect(40,335,80,80))
        self.l_logo_blth_3.setPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/font.png"))
        self.l_logo_blth_3.setScaledContents(True)
        self.l_logo_blth_3.setObjectName("l_logo_blth_3")
        self.pages.addWidget(self.software)
        self.page = QtGui.QWidget()
        self.page.setObjectName("page")
        self.label_5 = QtGui.QLabel(self.page)
        self.label_5.setGeometry(QtCore.QRect(70,70,421,20))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.frame = QtGui.QFrame(self.page)
        self.frame.setGeometry(QtCore.QRect(30,130,511,211))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_6 = QtGui.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(20,20,481,101))
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtGui.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(20,140,391,31))
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.l_seconds = QtGui.QLabel(self.frame)
        self.l_seconds.setGeometry(QtCore.QRect(400,170,91,20))
        self.l_seconds.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.l_seconds.setObjectName("l_seconds")
        self.l_countdown = QtGui.QLabel(self.frame)
        self.l_countdown.setGeometry(QtCore.QRect(340,170,51,20))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setWeight(75)
        font.setBold(True)
        self.l_countdown.setFont(font)
        self.l_countdown.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.l_countdown.setObjectName("l_countdown")
        self.b_ok = QtGui.QPushButton(self.page)
        self.b_ok.setGeometry(QtCore.QRect(280,390,101,30))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/ok.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.b_ok.setIcon(icon)
        self.b_ok.setIconSize(QtCore.QSize(22,22))
        self.b_ok.setObjectName("b_ok")
        self.b_restore = QtGui.QPushButton(self.page)
        self.b_restore.setGeometry(QtCore.QRect(400,390,101,30))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/reload.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.b_restore.setIcon(icon)
        self.b_restore.setIconSize(QtCore.QSize(22,22))
        self.b_restore.setObjectName("b_restore")
        self.pages.addWidget(self.page)
        self.label_3 = QtGui.QLabel(FormDisplay)
        self.label_3.setGeometry(QtCore.QRect(20,10,90,90))
        self.label_3.setPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/kademar.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.b_sortir = QtGui.QPushButton(FormDisplay)
        self.b_sortir.setGeometry(QtCore.QRect(20,440,141,41))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/enrera.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.b_sortir.setIcon(icon)
        self.b_sortir.setIconSize(QtCore.QSize(32,32))
        self.b_sortir.setObjectName("b_sortir")
        self.b_SaX = QtGui.QPushButton(FormDisplay)
        self.b_SaX.setGeometry(QtCore.QRect(20,390,141,41))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/ok.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.b_SaX.setIcon(icon)
        self.b_SaX.setIconSize(QtCore.QSize(32,32))
        self.b_SaX.setObjectName("b_SaX")

        self.retranslateUi(FormDisplay)
        self.pages.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(FormDisplay)

    def retranslateUi(self, FormDisplay):
        FormDisplay.setWindowTitle(QtGui.QApplication.translate("FormDisplay", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("FormDisplay", "Display Config", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("FormDisplay", "You can change your display settings.", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("FormDisplay", "Display Resolution", None, QtGui.QApplication.UnicodeUTF8))
        self.l_resolution.setText(QtGui.QApplication.translate("FormDisplay", "800x600", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("FormDisplay", "Color Depth", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_depth.addItem(QtGui.QApplication.translate("FormDisplay", "24 bit", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_depth.addItem(QtGui.QApplication.translate("FormDisplay", "16 bit", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_forceResol.setText(QtGui.QApplication.translate("FormDisplay", "Force\n"
"Resolution", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("FormDisplay", "General Font Size (DPI)", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_dpi.addItem(QtGui.QApplication.translate("FormDisplay", "Too Large", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_dpi.addItem(QtGui.QApplication.translate("FormDisplay", "Large", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_dpi.addItem(QtGui.QApplication.translate("FormDisplay", "Normal", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_dpi.addItem(QtGui.QApplication.translate("FormDisplay", "Small", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_dpi.addItem(QtGui.QApplication.translate("FormDisplay", "Too Small", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("FormDisplay", "Display Resolution Confirmation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("FormDisplay", "Resolution has been changed.\n"
"If you look this message correctly, press OK.\n"
"\n"
"If you have forced a resolution , you may need to restart the session.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("FormDisplay", "If you don\'t confirm it, resolution will be restored on:", None, QtGui.QApplication.UnicodeUTF8))
        self.l_seconds.setText(QtGui.QApplication.translate("FormDisplay", "Seconds", None, QtGui.QApplication.UnicodeUTF8))
        self.l_countdown.setText(QtGui.QApplication.translate("FormDisplay", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.b_ok.setText(QtGui.QApplication.translate("FormDisplay", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.b_restore.setText(QtGui.QApplication.translate("FormDisplay", "Restore", None, QtGui.QApplication.UnicodeUTF8))
        self.b_sortir.setText(QtGui.QApplication.translate("FormDisplay", "Back", None, QtGui.QApplication.UnicodeUTF8))
        self.b_SaX.setText(QtGui.QApplication.translate("FormDisplay", "Apply", None, QtGui.QApplication.UnicodeUTF8))

