# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/grub_installed.ui'
#
# Created: Sat Dec 26 04:03:34 2009
#      by: PyQt4 UI code generator 4.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_FormGrub(object):
    def setupUi(self, FormGrub):
        FormGrub.setObjectName("FormGrub")
        FormGrub.resize(800,600)
        FormGrub.setMinimumSize(QtCore.QSize(800,600))
        self.label_2 = QtGui.QLabel(FormGrub)
        self.label_2.setGeometry(QtCore.QRect(0,0,800,600))
        self.label_2.setPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/bg/cadi.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.pageWidget = QtGui.QStackedWidget(FormGrub)
        self.pageWidget.setGeometry(QtCore.QRect(230,80,491,481))
        self.pageWidget.setObjectName("pageWidget")
        self.software = QtGui.QWidget()
        self.software.setObjectName("software")
        self.label_4 = QtGui.QLabel(self.software)
        self.label_4.setGeometry(QtCore.QRect(9,10,461,21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label = QtGui.QLabel(self.software)
        self.label.setGeometry(QtCore.QRect(40,70,411,41))
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.l_logo_blth = QtGui.QLabel(self.software)
        self.l_logo_blth.setGeometry(QtCore.QRect(300,210,121,141))
        self.l_logo_blth.setPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/hdd_unmount.png"))
        self.l_logo_blth.setObjectName("l_logo_blth")
        self.b_expert = QtGui.QPushButton(self.software)
        self.b_expert.setGeometry(QtCore.QRect(70,360,151,30))
        self.b_expert.setObjectName("b_expert")
        self.cb_boot = QtGui.QComboBox(self.software)
        self.cb_boot.setGeometry(QtCore.QRect(80,160,341,22))
        self.cb_boot.setObjectName("cb_boot")
        self.label_6 = QtGui.QLabel(self.software)
        self.label_6.setGeometry(QtCore.QRect(40,130,311,16))
        self.label_6.setObjectName("label_6")
        self.frame = QtGui.QFrame(self.software)
        self.frame.setGeometry(QtCore.QRect(40,220,241,91))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.sb_timeout = QtGui.QSpinBox(self.frame)
        self.sb_timeout.setGeometry(QtCore.QRect(90,40,50,22))
        self.sb_timeout.setMinimum(1)
        self.sb_timeout.setObjectName("sb_timeout")
        self.ch_timeout = QtGui.QCheckBox(self.frame)
        self.ch_timeout.setGeometry(QtCore.QRect(20,10,181,21))
        self.ch_timeout.setObjectName("ch_timeout")
        self.label_5 = QtGui.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(150,43,71,16))
        self.label_5.setObjectName("label_5")
        self.pageWidget.addWidget(self.software)
        self.label_3 = QtGui.QLabel(FormGrub)
        self.label_3.setGeometry(QtCore.QRect(20,10,90,90))
        self.label_3.setPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/kademar.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.b_sortir = QtGui.QPushButton(FormGrub)
        self.b_sortir.setGeometry(QtCore.QRect(10,430,131,41))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/enrera.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.b_sortir.setIcon(icon)
        self.b_sortir.setObjectName("b_sortir")
        self.b_SaX = QtGui.QPushButton(FormGrub)
        self.b_SaX.setEnabled(False)
        self.b_SaX.setGeometry(QtCore.QRect(10,380,131,41))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/enrera.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.b_SaX.setIcon(icon)
        self.b_SaX.setObjectName("b_SaX")

        self.retranslateUi(FormGrub)
        self.pageWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(FormGrub)

    def retranslateUi(self, FormGrub):
        FormGrub.setWindowTitle(QtGui.QApplication.translate("FormGrub", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("FormGrub", "Configure Boot Sector - Grub", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("FormGrub", "You may configure Boot Manager here.", None, QtGui.QApplication.UnicodeUTF8))
        self.b_expert.setText(QtGui.QApplication.translate("FormGrub", "Expert Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("FormGrub", "Default Boot Selection", None, QtGui.QApplication.UnicodeUTF8))
        self.ch_timeout.setText(QtGui.QApplication.translate("FormGrub", "Timeout", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("FormGrub", "Seconds", None, QtGui.QApplication.UnicodeUTF8))
        self.b_sortir.setText(QtGui.QApplication.translate("FormGrub", "Back", None, QtGui.QApplication.UnicodeUTF8))
        self.b_SaX.setText(QtGui.QApplication.translate("FormGrub", "Save && Exit", None, QtGui.QApplication.UnicodeUTF8))

