# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/internet.ui-old'
#
# Created: Sat Dec 26 04:03:35 2009
#      by: PyQt4 UI code generator 4.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_FormInternet(object):
    def setupUi(self, FormInternet):
        FormInternet.setObjectName("FormInternet")
        FormInternet.resize(640,480)
        self.label_2 = QtGui.QLabel(FormInternet)
        self.label_2.setGeometry(QtCore.QRect(-1,0,640,480))
        self.label_2.setPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/bg/cadi.png"))
        self.label_2.setObjectName("label_2")
        self.pages = QtGui.QStackedWidget(FormInternet)
        self.pages.setGeometry(QtCore.QRect(150,0,491,481))
        self.pages.setObjectName("pages")
        self.page = QtGui.QWidget()
        self.page.setObjectName("page")
        self.l_img_router = QtGui.QLabel(self.page)
        self.l_img_router.setGeometry(QtCore.QRect(210,96,71,61))
        self.l_img_router.setPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/router.png"))
        self.l_img_router.setScaledContents(True)
        self.l_img_router.setObjectName("l_img_router")
        self.l_img_pc = QtGui.QLabel(self.page)
        self.l_img_pc.setGeometry(QtCore.QRect(50,86,71,71))
        self.l_img_pc.setPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/sistema.png"))
        self.l_img_pc.setObjectName("l_img_pc")
        self.l_img_internet = QtGui.QLabel(self.page)
        self.l_img_internet.setGeometry(QtCore.QRect(370,92,71,70))
        self.l_img_internet.setPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/network.png"))
        self.l_img_internet.setObjectName("l_img_internet")
        self.l_img_diag_router = QtGui.QLabel(self.page)
        self.l_img_diag_router.setGeometry(QtCore.QRect(120,116,91,31))
        self.l_img_diag_router.setPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/search.png"))
        self.l_img_diag_router.setAlignment(QtCore.Qt.AlignCenter)
        self.l_img_diag_router.setObjectName("l_img_diag_router")
        self.b_configure = QtGui.QPushButton(self.page)
        self.b_configure.setGeometry(QtCore.QRect(80,350,291,41))
        self.b_configure.setObjectName("b_configure")
        self.l_title = QtGui.QLabel(self.page)
        self.l_title.setGeometry(QtCore.QRect(70,30,251,20))
        self.l_title.setObjectName("l_title")
        self.l_pc = QtGui.QLabel(self.page)
        self.l_pc.setGeometry(QtCore.QRect(40,160,71,20))
        self.l_pc.setAlignment(QtCore.Qt.AlignCenter)
        self.l_pc.setObjectName("l_pc")
        self.l_hostname = QtGui.QLabel(self.page)
        self.l_hostname.setGeometry(QtCore.QRect(0,182,151,20))
        font = QtGui.QFont()
        font.setItalic(True)
        self.l_hostname.setFont(font)
        self.l_hostname.setAlignment(QtCore.Qt.AlignCenter)
        self.l_hostname.setObjectName("l_hostname")
        self.l_router = QtGui.QLabel(self.page)
        self.l_router.setGeometry(QtCore.QRect(210,160,71,20))
        self.l_router.setAlignment(QtCore.Qt.AlignCenter)
        self.l_router.setObjectName("l_router")
        self.l_internet = QtGui.QLabel(self.page)
        self.l_internet.setGeometry(QtCore.QRect(370,160,71,20))
        self.l_internet.setAlignment(QtCore.Qt.AlignCenter)
        self.l_internet.setObjectName("l_internet")
        self.l_diag = QtGui.QLabel(self.page)
        self.l_diag.setGeometry(QtCore.QRect(30,260,101,20))
        self.l_diag.setObjectName("l_diag")
        self.l_final_diag = QtGui.QLabel(self.page)
        self.l_final_diag.setGeometry(QtCore.QRect(250,260,161,20))
        font = QtGui.QFont()
        font.setItalic(True)
        self.l_final_diag.setFont(font)
        self.l_final_diag.setObjectName("l_final_diag")
        self.l_inet_provider = QtGui.QLabel(self.page)
        self.l_inet_provider.setGeometry(QtCore.QRect(30,290,211,20))
        self.l_inet_provider.setObjectName("l_inet_provider")
        self.l_inet_eth_provider = QtGui.QLabel(self.page)
        self.l_inet_eth_provider.setGeometry(QtCore.QRect(250,290,63,20))
        font = QtGui.QFont()
        font.setItalic(True)
        self.l_inet_eth_provider.setFont(font)
        self.l_inet_eth_provider.setObjectName("l_inet_eth_provider")
        self.l_ip_pc = QtGui.QLabel(self.page)
        self.l_ip_pc.setGeometry(QtCore.QRect(20,205,111,20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.l_ip_pc.setFont(font)
        self.l_ip_pc.setAlignment(QtCore.Qt.AlignCenter)
        self.l_ip_pc.setObjectName("l_ip_pc")
        self.l_ip_router = QtGui.QLabel(self.page)
        self.l_ip_router.setGeometry(QtCore.QRect(190,205,111,20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.l_ip_router.setFont(font)
        self.l_ip_router.setAlignment(QtCore.Qt.AlignCenter)
        self.l_ip_router.setObjectName("l_ip_router")
        self.l_img_diag_internet = QtGui.QLabel(self.page)
        self.l_img_diag_internet.setGeometry(QtCore.QRect(280,116,91,31))
        self.l_img_diag_internet.setPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/search.png"))
        self.l_img_diag_internet.setAlignment(QtCore.Qt.AlignCenter)
        self.l_img_diag_internet.setObjectName("l_img_diag_internet")
        self.pages.addWidget(self.page)
        self.pag1 = QtGui.QWidget()
        self.pag1.setObjectName("pag1")
        self.label_4 = QtGui.QLabel(self.pag1)
        self.label_4.setGeometry(QtCore.QRect(189,30,141,21))
        self.label_4.setObjectName("label_4")
        self.label = QtGui.QLabel(self.pag1)
        self.label.setGeometry(QtCore.QRect(60,110,191,20))
        self.label.setObjectName("label")
        self.list_net_dev = QtGui.QListWidget(self.pag1)
        self.list_net_dev.setGeometry(QtCore.QRect(30,150,421,211))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.list_net_dev.setFont(font)
        self.list_net_dev.setObjectName("list_net_dev")
        self.b_next = QtGui.QPushButton(self.pag1)
        self.b_next.setEnabled(False)
        self.b_next.setGeometry(QtCore.QRect(360,400,71,61))
        self.b_next.setObjectName("b_next")
        self.b_prev = QtGui.QPushButton(self.pag1)
        self.b_prev.setGeometry(QtCore.QRect(60,400,71,61))
        self.b_prev.setObjectName("b_prev")
        self.b_prev_2 = QtGui.QPushButton(self.pag1)
        self.b_prev_2.setGeometry(QtCore.QRect(210,400,71,61))
        self.b_prev_2.setObjectName("b_prev_2")
        self.pages.addWidget(self.pag1)
        self.pag2 = QtGui.QWidget()
        self.pag2.setObjectName("pag2")
        self.label_11 = QtGui.QLabel(self.pag2)
        self.label_11.setGeometry(QtCore.QRect(189,30,141,21))
        self.label_11.setObjectName("label_11")
        self.b_next2 = QtGui.QPushButton(self.pag2)
        self.b_next2.setEnabled(False)
        self.b_next2.setGeometry(QtCore.QRect(360,400,71,61))
        self.b_next2.setObjectName("b_next2")
        self.label_10 = QtGui.QLabel(self.pag2)
        self.label_10.setGeometry(QtCore.QRect(70,70,191,20))
        self.label_10.setObjectName("label_10")
        self.list_net_wifi = QtGui.QListWidget(self.pag2)
        self.list_net_wifi.setGeometry(QtCore.QRect(50,110,381,201))
        self.list_net_wifi.setObjectName("list_net_wifi")
        self.b_prev2 = QtGui.QPushButton(self.pag2)
        self.b_prev2.setGeometry(QtCore.QRect(60,400,71,61))
        self.b_prev2.setObjectName("b_prev2")
        self.l_key = QtGui.QLabel(self.pag2)
        self.l_key.setGeometry(QtCore.QRect(70,360,63,20))
        self.l_key.setObjectName("l_key")
        self.le_key = QtGui.QLineEdit(self.pag2)
        self.le_key.setGeometry(QtCore.QRect(140,360,201,26))
        self.le_key.setEchoMode(QtGui.QLineEdit.Password)
        self.le_key.setObjectName("le_key")
        self.cb_key_type = QtGui.QComboBox(self.pag2)
        self.cb_key_type.setGeometry(QtCore.QRect(350,360,79,25))
        self.cb_key_type.setObjectName("cb_key_type")
        self.b_reload = QtGui.QPushButton(self.pag2)
        self.b_reload.setGeometry(QtCore.QRect(332,60,101,30))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/reload.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.b_reload.setIcon(icon)
        self.b_reload.setIconSize(QtCore.QSize(22,22))
        self.b_reload.setObjectName("b_reload")
        self.cb_permanent = QtGui.QCheckBox(self.pag2)
        self.cb_permanent.setGeometry(QtCore.QRect(50,320,291,25))
        self.cb_permanent.setObjectName("cb_permanent")
        self.pages.addWidget(self.pag2)
        self.pag3 = QtGui.QWidget()
        self.pag3.setObjectName("pag3")
        self.b_prev3 = QtGui.QPushButton(self.pag3)
        self.b_prev3.setGeometry(QtCore.QRect(60,400,71,61))
        self.b_prev3.setObjectName("b_prev3")
        self.b_next3 = QtGui.QPushButton(self.pag3)
        self.b_next3.setGeometry(QtCore.QRect(360,400,71,61))
        self.b_next3.setObjectName("b_next3")
        self.rb_static = QtGui.QRadioButton(self.pag3)
        self.rb_static.setGeometry(QtCore.QRect(120,220,102,26))
        self.rb_static.setObjectName("rb_static")
        self.label_5 = QtGui.QLabel(self.pag3)
        self.label_5.setGeometry(QtCore.QRect(20,30,381,81))
        self.label_5.setObjectName("label_5")
        self.rb_dynamic = QtGui.QRadioButton(self.pag3)
        self.rb_dynamic.setGeometry(QtCore.QRect(120,180,211,26))
        self.rb_dynamic.setChecked(True)
        self.rb_dynamic.setObjectName("rb_dynamic")
        self.pages.addWidget(self.pag3)
        self.pag4 = QtGui.QWidget()
        self.pag4.setObjectName("pag4")
        self.label_6 = QtGui.QLabel(self.pag4)
        self.label_6.setGeometry(QtCore.QRect(40,40,291,20))
        self.label_6.setObjectName("label_6")
        self.le_ip = QtGui.QLineEdit(self.pag4)
        self.le_ip.setGeometry(QtCore.QRect(160,120,171,26))
        self.le_ip.setObjectName("le_ip")
        self.lineEdit_2 = QtGui.QLineEdit(self.pag4)
        self.lineEdit_2.setGeometry(QtCore.QRect(160,160,171,26))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtGui.QLineEdit(self.pag4)
        self.lineEdit_3.setGeometry(QtCore.QRect(160,200,171,26))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_7 = QtGui.QLabel(self.pag4)
        self.label_7.setGeometry(QtCore.QRect(40,130,63,20))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtGui.QLabel(self.pag4)
        self.label_8.setGeometry(QtCore.QRect(40,160,63,20))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtGui.QLabel(self.pag4)
        self.label_9.setGeometry(QtCore.QRect(40,200,81,20))
        self.label_9.setObjectName("label_9")
        self.comboBox = QtGui.QComboBox(self.pag4)
        self.comboBox.setGeometry(QtCore.QRect(60,270,311,51))
        self.comboBox.setObjectName("comboBox")
        self.b_next4 = QtGui.QPushButton(self.pag4)
        self.b_next4.setGeometry(QtCore.QRect(360,400,71,61))
        self.b_next4.setObjectName("b_next4")
        self.b_prev4 = QtGui.QPushButton(self.pag4)
        self.b_prev4.setGeometry(QtCore.QRect(60,400,71,61))
        self.b_prev4.setObjectName("b_prev4")
        self.pages.addWidget(self.pag4)
        self.label_3 = QtGui.QLabel(FormInternet)
        self.label_3.setGeometry(QtCore.QRect(15,7,110,91))
        self.label_3.setPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/kademar.png"))
        self.label_3.setObjectName("label_3")
        self.b_sortir = QtGui.QPushButton(FormInternet)
        self.b_sortir.setGeometry(QtCore.QRect(20,440,101,31))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/enrera.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.b_sortir.setIcon(icon)
        self.b_sortir.setObjectName("b_sortir")

        self.retranslateUi(FormInternet)
        self.pages.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(FormInternet)

    def retranslateUi(self, FormInternet):
        FormInternet.setWindowTitle(QtGui.QApplication.translate("FormInternet", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.b_configure.setText(QtGui.QApplication.translate("FormInternet", "Configurar acceso a internet", None, QtGui.QApplication.UnicodeUTF8))
        self.l_title.setText(QtGui.QApplication.translate("FormInternet", "Internet and Network Connectivity ", None, QtGui.QApplication.UnicodeUTF8))
        self.l_pc.setText(QtGui.QApplication.translate("FormInternet", "Sistema", None, QtGui.QApplication.UnicodeUTF8))
        self.l_hostname.setText(QtGui.QApplication.translate("FormInternet", "(localhost)", None, QtGui.QApplication.UnicodeUTF8))
        self.l_router.setText(QtGui.QApplication.translate("FormInternet", "Router", None, QtGui.QApplication.UnicodeUTF8))
        self.l_internet.setText(QtGui.QApplication.translate("FormInternet", "Internet", None, QtGui.QApplication.UnicodeUTF8))
        self.l_diag.setText(QtGui.QApplication.translate("FormInternet", "Diagnostic:", None, QtGui.QApplication.UnicodeUTF8))
        self.l_inet_provider.setText(QtGui.QApplication.translate("FormInternet", "Internet Provicer Interface: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("FormInternet", "Net Device", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("FormInternet", "Select Net Device", None, QtGui.QApplication.UnicodeUTF8))
        self.b_next.setText(QtGui.QApplication.translate("FormInternet", "Next", None, QtGui.QApplication.UnicodeUTF8))
        self.b_prev.setText(QtGui.QApplication.translate("FormInternet", "Back", None, QtGui.QApplication.UnicodeUTF8))
        self.b_prev_2.setText(QtGui.QApplication.translate("FormInternet", "Disconfig", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("FormInternet", "Wireless Network", None, QtGui.QApplication.UnicodeUTF8))
        self.b_next2.setText(QtGui.QApplication.translate("FormInternet", "Next", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("FormInternet", "Select Wireless Network", None, QtGui.QApplication.UnicodeUTF8))
        self.b_prev2.setText(QtGui.QApplication.translate("FormInternet", "Back", None, QtGui.QApplication.UnicodeUTF8))
        self.l_key.setText(QtGui.QApplication.translate("FormInternet", "key", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_key_type.addItem(QtGui.QApplication.translate("FormInternet", "WEP", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_key_type.addItem(QtGui.QApplication.translate("FormInternet", "Hexa", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_key_type.addItem(QtGui.QApplication.translate("FormInternet", "ASCII", None, QtGui.QApplication.UnicodeUTF8))
        self.b_reload.setText(QtGui.QApplication.translate("FormInternet", "Reload", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_permanent.setText(QtGui.QApplication.translate("FormInternet", "Make Permanent Connection", None, QtGui.QApplication.UnicodeUTF8))
        self.b_prev3.setText(QtGui.QApplication.translate("FormInternet", "Back", None, QtGui.QApplication.UnicodeUTF8))
        self.b_next3.setText(QtGui.QApplication.translate("FormInternet", "Next", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_static.setText(QtGui.QApplication.translate("FormInternet", "Static IP", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("FormInternet", "In this step you must choose what kind of IP you have.", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_dynamic.setText(QtGui.QApplication.translate("FormInternet", "Dynamic IP (by default)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("FormInternet", "Introduce Static IP parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.le_ip.setInputMask(QtGui.QApplication.translate("FormInternet", "999.999.999.999; ", None, QtGui.QApplication.UnicodeUTF8))
        self.le_ip.setText(QtGui.QApplication.translate("FormInternet", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_2.setInputMask(QtGui.QApplication.translate("FormInternet", "999.999.999.999; ", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_3.setInputMask(QtGui.QApplication.translate("FormInternet", "999.999.999.999; ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("FormInternet", "IP", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("FormInternet", "Netmask", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("FormInternet", "Gateway", None, QtGui.QApplication.UnicodeUTF8))
        self.b_next4.setText(QtGui.QApplication.translate("FormInternet", "Next", None, QtGui.QApplication.UnicodeUTF8))
        self.b_prev4.setText(QtGui.QApplication.translate("FormInternet", "Back", None, QtGui.QApplication.UnicodeUTF8))
        self.b_sortir.setText(QtGui.QApplication.translate("FormInternet", "Enrera", None, QtGui.QApplication.UnicodeUTF8))

