# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/internet.ui'
#
# Created: Sat Dec 26 04:03:34 2009
#      by: PyQt4 UI code generator 4.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_FormInternet(object):
    def setupUi(self, FormInternet):
        FormInternet.setObjectName("FormInternet")
        FormInternet.resize(800,600)
        FormInternet.setMinimumSize(QtCore.QSize(800,600))
        self.label_2 = QtGui.QLabel(FormInternet)
        self.label_2.setGeometry(QtCore.QRect(0,0,800,600))
        self.label_2.setPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/bg/cadi.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.pages = QtGui.QStackedWidget(FormInternet)
        self.pages.setGeometry(QtCore.QRect(190,0,611,601))
        self.pages.setObjectName("pages")
        self.page = QtGui.QWidget()
        self.page.setObjectName("page")
        self.l_img_router = QtGui.QLabel(self.page)
        self.l_img_router.setGeometry(QtCore.QRect(280,156,71,61))
        self.l_img_router.setPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/router.png"))
        self.l_img_router.setScaledContents(True)
        self.l_img_router.setObjectName("l_img_router")
        self.l_img_pc = QtGui.QLabel(self.page)
        self.l_img_pc.setGeometry(QtCore.QRect(80,146,71,71))
        self.l_img_pc.setPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/sistema.png"))
        self.l_img_pc.setObjectName("l_img_pc")
        self.l_img_internet = QtGui.QLabel(self.page)
        self.l_img_internet.setGeometry(QtCore.QRect(470,152,71,70))
        self.l_img_internet.setPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/network.png"))
        self.l_img_internet.setObjectName("l_img_internet")
        self.l_img_diag_router = QtGui.QLabel(self.page)
        self.l_img_diag_router.setGeometry(QtCore.QRect(170,176,91,31))
        self.l_img_diag_router.setPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/search.png"))
        self.l_img_diag_router.setAlignment(QtCore.Qt.AlignCenter)
        self.l_img_diag_router.setObjectName("l_img_diag_router")
        self.b_configure = QtGui.QPushButton(self.page)
        self.b_configure.setGeometry(QtCore.QRect(130,430,291,51))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/network.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.b_configure.setIcon(icon)
        self.b_configure.setIconSize(QtCore.QSize(32,32))
        self.b_configure.setObjectName("b_configure")
        self.l_title = QtGui.QLabel(self.page)
        self.l_title.setGeometry(QtCore.QRect(60,60,511,20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.l_title.setFont(font)
        self.l_title.setAlignment(QtCore.Qt.AlignCenter)
        self.l_title.setObjectName("l_title")
        self.l_pc = QtGui.QLabel(self.page)
        self.l_pc.setGeometry(QtCore.QRect(70,220,71,20))
        self.l_pc.setAlignment(QtCore.Qt.AlignCenter)
        self.l_pc.setObjectName("l_pc")
        self.l_hostname = QtGui.QLabel(self.page)
        self.l_hostname.setGeometry(QtCore.QRect(30,242,151,20))
        font = QtGui.QFont()
        font.setItalic(True)
        self.l_hostname.setFont(font)
        self.l_hostname.setAlignment(QtCore.Qt.AlignCenter)
        self.l_hostname.setObjectName("l_hostname")
        self.l_router = QtGui.QLabel(self.page)
        self.l_router.setGeometry(QtCore.QRect(280,220,71,20))
        self.l_router.setAlignment(QtCore.Qt.AlignCenter)
        self.l_router.setObjectName("l_router")
        self.l_internet = QtGui.QLabel(self.page)
        self.l_internet.setGeometry(QtCore.QRect(470,220,71,20))
        self.l_internet.setAlignment(QtCore.Qt.AlignCenter)
        self.l_internet.setObjectName("l_internet")
        self.l_diag = QtGui.QLabel(self.page)
        self.l_diag.setGeometry(QtCore.QRect(80,320,171,20))
        self.l_diag.setObjectName("l_diag")
        self.l_final_diag = QtGui.QLabel(self.page)
        self.l_final_diag.setGeometry(QtCore.QRect(290,320,161,20))
        font = QtGui.QFont()
        font.setItalic(True)
        self.l_final_diag.setFont(font)
        self.l_final_diag.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.l_final_diag.setObjectName("l_final_diag")
        self.l_inet_provider = QtGui.QLabel(self.page)
        self.l_inet_provider.setGeometry(QtCore.QRect(80,350,261,20))
        self.l_inet_provider.setObjectName("l_inet_provider")
        self.l_inet_eth_provider = QtGui.QLabel(self.page)
        self.l_inet_eth_provider.setGeometry(QtCore.QRect(360,350,91,20))
        font = QtGui.QFont()
        font.setItalic(True)
        self.l_inet_eth_provider.setFont(font)
        self.l_inet_eth_provider.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.l_inet_eth_provider.setObjectName("l_inet_eth_provider")
        self.l_ip_pc = QtGui.QLabel(self.page)
        self.l_ip_pc.setGeometry(QtCore.QRect(60,260,111,20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.l_ip_pc.setFont(font)
        self.l_ip_pc.setAlignment(QtCore.Qt.AlignCenter)
        self.l_ip_pc.setObjectName("l_ip_pc")
        self.l_ip_router = QtGui.QLabel(self.page)
        self.l_ip_router.setGeometry(QtCore.QRect(260,240,111,20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.l_ip_router.setFont(font)
        self.l_ip_router.setAlignment(QtCore.Qt.AlignCenter)
        self.l_ip_router.setObjectName("l_ip_router")
        self.l_img_diag_internet = QtGui.QLabel(self.page)
        self.l_img_diag_internet.setGeometry(QtCore.QRect(360,176,91,31))
        self.l_img_diag_internet.setPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/search.png"))
        self.l_img_diag_internet.setAlignment(QtCore.Qt.AlignCenter)
        self.l_img_diag_internet.setObjectName("l_img_diag_internet")
        self.pages.addWidget(self.page)
        self.pag1 = QtGui.QWidget()
        self.pag1.setObjectName("pag1")
        self.label_4 = QtGui.QLabel(self.pag1)
        self.label_4.setGeometry(QtCore.QRect(59,60,491,21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label = QtGui.QLabel(self.pag1)
        self.label.setGeometry(QtCore.QRect(60,110,381,20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.list_net_dev = QtGui.QListWidget(self.pag1)
        self.list_net_dev.setGeometry(QtCore.QRect(60,150,491,211))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.list_net_dev.setFont(font)
        self.list_net_dev.setObjectName("list_net_dev")
        self.b_next = QtGui.QPushButton(self.pag1)
        self.b_next.setEnabled(False)
        self.b_next.setGeometry(QtCore.QRect(420,440,131,51))
        self.b_next.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/go-next.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.b_next.setIcon(icon)
        self.b_next.setIconSize(QtCore.QSize(22,22))
        self.b_next.setObjectName("b_next")
        self.b_prev = QtGui.QPushButton(self.pag1)
        self.b_prev.setGeometry(QtCore.QRect(60,440,131,51))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/go_previous.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.b_prev.setIcon(icon)
        self.b_prev.setIconSize(QtCore.QSize(22,22))
        self.b_prev.setObjectName("b_prev")
        self.b_disconfigure = QtGui.QPushButton(self.pag1)
        self.b_disconfigure.setGeometry(QtCore.QRect(240,440,131,51))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/stoped.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.b_disconfigure.setIcon(icon)
        self.b_disconfigure.setIconSize(QtCore.QSize(22,22))
        self.b_disconfigure.setObjectName("b_disconfigure")
        self.cb_autoip = QtGui.QCheckBox(self.pag1)
        self.cb_autoip.setGeometry(QtCore.QRect(60,390,391,25))
        font = QtGui.QFont()
        font.setItalic(True)
        self.cb_autoip.setFont(font)
        self.cb_autoip.setChecked(True)
        self.cb_autoip.setObjectName("cb_autoip")
        self.pages.addWidget(self.pag1)
        self.pag2 = QtGui.QWidget()
        self.pag2.setObjectName("pag2")
        self.label_11 = QtGui.QLabel(self.pag2)
        self.label_11.setGeometry(QtCore.QRect(59,60,481,21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.b_next2 = QtGui.QPushButton(self.pag2)
        self.b_next2.setEnabled(False)
        self.b_next2.setGeometry(QtCore.QRect(410,480,121,51))
        self.b_next2.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/go-next.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.b_next2.setIcon(icon)
        self.b_next2.setIconSize(QtCore.QSize(22,22))
        self.b_next2.setObjectName("b_next2")
        self.label_10 = QtGui.QLabel(self.pag2)
        self.label_10.setGeometry(QtCore.QRect(60,110,241,20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.list_net_wifi = QtGui.QListWidget(self.pag2)
        self.list_net_wifi.setGeometry(QtCore.QRect(60,150,491,211))
        self.list_net_wifi.setObjectName("list_net_wifi")
        self.b_prev2 = QtGui.QPushButton(self.pag2)
        self.b_prev2.setGeometry(QtCore.QRect(60,480,121,51))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/go_previous.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.b_prev2.setIcon(icon)
        self.b_prev2.setIconSize(QtCore.QSize(22,22))
        self.b_prev2.setObjectName("b_prev2")
        self.l_key = QtGui.QLabel(self.pag2)
        self.l_key.setGeometry(QtCore.QRect(60,420,61,20))
        self.l_key.setObjectName("l_key")
        self.le_key = QtGui.QLineEdit(self.pag2)
        self.le_key.setGeometry(QtCore.QRect(130,420,291,26))
        self.le_key.setEchoMode(QtGui.QLineEdit.Password)
        self.le_key.setObjectName("le_key")
        self.cb_key_type = QtGui.QComboBox(self.pag2)
        self.cb_key_type.setGeometry(QtCore.QRect(430,420,101,25))
        self.cb_key_type.setObjectName("cb_key_type")
        self.b_reload = QtGui.QPushButton(self.pag2)
        self.b_reload.setGeometry(QtCore.QRect(410,100,131,41))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/reload.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.b_reload.setIcon(icon)
        self.b_reload.setIconSize(QtCore.QSize(32,32))
        self.b_reload.setObjectName("b_reload")
        self.cb_permanent = QtGui.QCheckBox(self.pag2)
        self.cb_permanent.setGeometry(QtCore.QRect(60,380,391,25))
        self.cb_permanent.setObjectName("cb_permanent")
        self.pages.addWidget(self.pag2)
        self.pag3 = QtGui.QWidget()
        self.pag3.setObjectName("pag3")
        self.b_prev3 = QtGui.QPushButton(self.pag3)
        self.b_prev3.setGeometry(QtCore.QRect(60,480,121,51))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/go_previous.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.b_prev3.setIcon(icon)
        self.b_prev3.setIconSize(QtCore.QSize(22,1622))
        self.b_prev3.setObjectName("b_prev3")
        self.b_next3 = QtGui.QPushButton(self.pag3)
        self.b_next3.setGeometry(QtCore.QRect(410,480,121,51))
        self.b_next3.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/go-next.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.b_next3.setIcon(icon)
        self.b_next3.setIconSize(QtCore.QSize(22,22))
        self.b_next3.setObjectName("b_next3")
        self.groupBox = QtGui.QGroupBox(self.pag3)
        self.groupBox.setGeometry(QtCore.QRect(90,100,431,171))
        self.groupBox.setObjectName("groupBox")
        self.rb_ip_static = QtGui.QRadioButton(self.groupBox)
        self.rb_ip_static.setGeometry(QtCore.QRect(220,30,102,26))
        self.rb_ip_static.setObjectName("rb_ip_static")
        self.rb_ip_dynamic = QtGui.QRadioButton(self.groupBox)
        self.rb_ip_dynamic.setGeometry(QtCore.QRect(20,30,211,26))
        self.rb_ip_dynamic.setChecked(True)
        self.rb_ip_dynamic.setObjectName("rb_ip_dynamic")
        self.l_netmask = QtGui.QLabel(self.groupBox)
        self.l_netmask.setEnabled(False)
        self.l_netmask.setGeometry(QtCore.QRect(70,104,63,20))
        self.l_netmask.setObjectName("l_netmask")
        self.le_ip = QtGui.QLineEdit(self.groupBox)
        self.le_ip.setEnabled(False)
        self.le_ip.setGeometry(QtCore.QRect(170,70,171,26))
        self.le_ip.setObjectName("le_ip")
        self.l_ip = QtGui.QLabel(self.groupBox)
        self.l_ip.setEnabled(False)
        self.l_ip.setGeometry(QtCore.QRect(70,73,63,20))
        self.l_ip.setObjectName("l_ip")
        self.le_gateway = QtGui.QLineEdit(self.groupBox)
        self.le_gateway.setEnabled(False)
        self.le_gateway.setGeometry(QtCore.QRect(170,130,171,26))
        self.le_gateway.setObjectName("le_gateway")
        self.l_gateway = QtGui.QLabel(self.groupBox)
        self.l_gateway.setEnabled(False)
        self.l_gateway.setGeometry(QtCore.QRect(70,133,81,20))
        self.l_gateway.setObjectName("l_gateway")
        self.le_netmask = QtGui.QLineEdit(self.groupBox)
        self.le_netmask.setEnabled(False)
        self.le_netmask.setGeometry(QtCore.QRect(170,100,171,26))
        self.le_netmask.setObjectName("le_netmask")
        self.groupBox_2 = QtGui.QGroupBox(self.pag3)
        self.groupBox_2.setGeometry(QtCore.QRect(90,290,431,151))
        self.groupBox_2.setObjectName("groupBox_2")
        self.le_custom_dns = QtGui.QLineEdit(self.groupBox_2)
        self.le_custom_dns.setEnabled(False)
        self.le_custom_dns.setGeometry(QtCore.QRect(60,110,311,26))
        self.le_custom_dns.setObjectName("le_custom_dns")
        self.cb_dns = QtGui.QComboBox(self.groupBox_2)
        self.cb_dns.setEnabled(False)
        self.cb_dns.setGeometry(QtCore.QRect(30,70,381,31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.cb_dns.setFont(font)
        self.cb_dns.setObjectName("cb_dns")
        self.rb_dns_static = QtGui.QRadioButton(self.groupBox_2)
        self.rb_dns_static.setGeometry(QtCore.QRect(220,30,102,26))
        self.rb_dns_static.setObjectName("rb_dns_static")
        self.rb_dns_dynamic = QtGui.QRadioButton(self.groupBox_2)
        self.rb_dns_dynamic.setGeometry(QtCore.QRect(10,30,211,26))
        self.rb_dns_dynamic.setChecked(True)
        self.rb_dns_dynamic.setObjectName("rb_dns_dynamic")
        self.pages.addWidget(self.pag3)
        self.pag4 = QtGui.QWidget()
        self.pag4.setObjectName("pag4")
        self.label_7 = QtGui.QLabel(self.pag4)
        self.label_7.setGeometry(QtCore.QRect(500,60,64,64))
        self.label_7.setPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/network.png"))
        self.label_7.setObjectName("label_7")
        self.l_mng = QtGui.QLabel(self.pag4)
        self.l_mng.setGeometry(QtCore.QRect(280,350,21,16))
        self.l_mng.setPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/instalador/img/wait.gif"))
        self.l_mng.setObjectName("l_mng")
        self.label_9 = QtGui.QLabel(self.pag4)
        self.label_9.setGeometry(QtCore.QRect(70,240,441,81))
        self.label_9.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        self.l_titol_9 = QtGui.QLabel(self.pag4)
        self.l_titol_9.setGeometry(QtCore.QRect(20,110,561,20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.l_titol_9.setFont(font)
        self.l_titol_9.setAlignment(QtCore.Qt.AlignCenter)
        self.l_titol_9.setObjectName("l_titol_9")
        self.pages.addWidget(self.pag4)
        self.label_3 = QtGui.QLabel(FormInternet)
        self.label_3.setGeometry(QtCore.QRect(20,10,90,90))
        self.label_3.setPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/kademar.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.b_sortir = QtGui.QPushButton(FormInternet)
        self.b_sortir.setGeometry(QtCore.QRect(20,540,131,41))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/enrera.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.b_sortir.setIcon(icon)
        self.b_sortir.setObjectName("b_sortir")

        self.retranslateUi(FormInternet)
        self.pages.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(FormInternet)
        FormInternet.setTabOrder(self.b_configure,self.b_sortir)
        FormInternet.setTabOrder(self.b_sortir,self.list_net_dev)
        FormInternet.setTabOrder(self.list_net_dev,self.cb_autoip)
        FormInternet.setTabOrder(self.cb_autoip,self.b_next)
        FormInternet.setTabOrder(self.b_next,self.b_disconfigure)
        FormInternet.setTabOrder(self.b_disconfigure,self.b_prev)
        FormInternet.setTabOrder(self.b_prev,self.b_reload)
        FormInternet.setTabOrder(self.b_reload,self.list_net_wifi)
        FormInternet.setTabOrder(self.list_net_wifi,self.cb_permanent)
        FormInternet.setTabOrder(self.cb_permanent,self.le_key)
        FormInternet.setTabOrder(self.le_key,self.cb_key_type)
        FormInternet.setTabOrder(self.cb_key_type,self.b_next2)
        FormInternet.setTabOrder(self.b_next2,self.b_prev2)
        FormInternet.setTabOrder(self.b_prev2,self.rb_ip_dynamic)
        FormInternet.setTabOrder(self.rb_ip_dynamic,self.rb_ip_static)
        FormInternet.setTabOrder(self.rb_ip_static,self.le_ip)
        FormInternet.setTabOrder(self.le_ip,self.le_netmask)
        FormInternet.setTabOrder(self.le_netmask,self.le_gateway)
        FormInternet.setTabOrder(self.le_gateway,self.rb_dns_dynamic)
        FormInternet.setTabOrder(self.rb_dns_dynamic,self.rb_dns_static)
        FormInternet.setTabOrder(self.rb_dns_static,self.cb_dns)
        FormInternet.setTabOrder(self.cb_dns,self.le_custom_dns)
        FormInternet.setTabOrder(self.le_custom_dns,self.b_next3)
        FormInternet.setTabOrder(self.b_next3,self.b_prev3)

    def retranslateUi(self, FormInternet):
        FormInternet.setWindowTitle(QtGui.QApplication.translate("FormInternet", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.b_configure.setText(QtGui.QApplication.translate("FormInternet", "Configure Internet Access", None, QtGui.QApplication.UnicodeUTF8))
        self.l_title.setText(QtGui.QApplication.translate("FormInternet", "Internet and Network Connectivity ", None, QtGui.QApplication.UnicodeUTF8))
        self.l_pc.setText(QtGui.QApplication.translate("FormInternet", "System", None, QtGui.QApplication.UnicodeUTF8))
        self.l_hostname.setText(QtGui.QApplication.translate("FormInternet", "(localhost)", None, QtGui.QApplication.UnicodeUTF8))
        self.l_router.setText(QtGui.QApplication.translate("FormInternet", "Router", None, QtGui.QApplication.UnicodeUTF8))
        self.l_internet.setText(QtGui.QApplication.translate("FormInternet", "Internet", None, QtGui.QApplication.UnicodeUTF8))
        self.l_diag.setText(QtGui.QApplication.translate("FormInternet", "Diagnostic:", None, QtGui.QApplication.UnicodeUTF8))
        self.l_inet_provider.setText(QtGui.QApplication.translate("FormInternet", "Internet Provider Interface: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("FormInternet", "Net Device", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("FormInternet", "Select Net Device", None, QtGui.QApplication.UnicodeUTF8))
        self.b_next.setText(QtGui.QApplication.translate("FormInternet", "Next", None, QtGui.QApplication.UnicodeUTF8))
        self.b_prev.setText(QtGui.QApplication.translate("FormInternet", "Back", None, QtGui.QApplication.UnicodeUTF8))
        self.b_disconfigure.setText(QtGui.QApplication.translate("FormInternet", "Disconfig", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_autoip.setText(QtGui.QApplication.translate("FormInternet", "Configure with a Automatic IP (by default)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("FormInternet", "Wireless Network", None, QtGui.QApplication.UnicodeUTF8))
        self.b_next2.setText(QtGui.QApplication.translate("FormInternet", "Next", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("FormInternet", "Select Wireless Network", None, QtGui.QApplication.UnicodeUTF8))
        self.b_prev2.setText(QtGui.QApplication.translate("FormInternet", "Back", None, QtGui.QApplication.UnicodeUTF8))
        self.l_key.setText(QtGui.QApplication.translate("FormInternet", "key", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_key_type.addItem(QtGui.QApplication.translate("FormInternet", "WEP/Hexa", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_key_type.addItem(QtGui.QApplication.translate("FormInternet", "ASCII", None, QtGui.QApplication.UnicodeUTF8))
        self.b_reload.setText(QtGui.QApplication.translate("FormInternet", "Reload", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_permanent.setText(QtGui.QApplication.translate("FormInternet", "Make Permanent Connection (write to interfaces file)", None, QtGui.QApplication.UnicodeUTF8))
        self.b_prev3.setText(QtGui.QApplication.translate("FormInternet", "Back", None, QtGui.QApplication.UnicodeUTF8))
        self.b_next3.setText(QtGui.QApplication.translate("FormInternet", "Next", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("FormInternet", "IP Address", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_ip_static.setText(QtGui.QApplication.translate("FormInternet", "Static IP", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_ip_dynamic.setText(QtGui.QApplication.translate("FormInternet", "Dynamic IP (by default)", None, QtGui.QApplication.UnicodeUTF8))
        self.l_netmask.setText(QtGui.QApplication.translate("FormInternet", "Netmask", None, QtGui.QApplication.UnicodeUTF8))
        self.le_ip.setInputMask(QtGui.QApplication.translate("FormInternet", "999.999.999.999; ", None, QtGui.QApplication.UnicodeUTF8))
        self.le_ip.setText(QtGui.QApplication.translate("FormInternet", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.l_ip.setText(QtGui.QApplication.translate("FormInternet", "IP", None, QtGui.QApplication.UnicodeUTF8))
        self.le_gateway.setInputMask(QtGui.QApplication.translate("FormInternet", "999.999.999.999; ", None, QtGui.QApplication.UnicodeUTF8))
        self.l_gateway.setText(QtGui.QApplication.translate("FormInternet", "Gateway", None, QtGui.QApplication.UnicodeUTF8))
        self.le_netmask.setInputMask(QtGui.QApplication.translate("FormInternet", "999.999.999.999; ", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("FormInternet", "DNS Nameservers", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_dns_static.setText(QtGui.QApplication.translate("FormInternet", "Static DNS", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_dns_dynamic.setText(QtGui.QApplication.translate("FormInternet", "Dynamic DNS (by default)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("FormInternet", "Now kademar is configuring your network connection.\n"
"\n"
"Be patient, please.", None, QtGui.QApplication.UnicodeUTF8))
        self.l_titol_9.setText(QtGui.QApplication.translate("FormInternet", "Configuring Internet Connection", None, QtGui.QApplication.UnicodeUTF8))
        self.b_sortir.setText(QtGui.QApplication.translate("FormInternet", "Back", None, QtGui.QApplication.UnicodeUTF8))

