# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/language.ui'
#
# Created: Sat Dec 26 04:03:35 2009
#      by: PyQt4 UI code generator 4.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_FormLanguage(object):
    def setupUi(self, FormLanguage):
        FormLanguage.setObjectName("FormLanguage")
        FormLanguage.resize(800,600)
        FormLanguage.setMinimumSize(QtCore.QSize(800,600))
        self.label_2 = QtGui.QLabel(FormLanguage)
        self.label_2.setGeometry(QtCore.QRect(0,0,800,600))
        self.label_2.setPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/bg/cadi.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.pageWidget = QtGui.QStackedWidget(FormLanguage)
        self.pageWidget.setGeometry(QtCore.QRect(240,60,491,481))
        self.pageWidget.setObjectName("pageWidget")
        self.software = QtGui.QWidget()
        self.software.setObjectName("software")
        self.label_4 = QtGui.QLabel(self.software)
        self.label_4.setGeometry(QtCore.QRect(9,30,471,21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label = QtGui.QLabel(self.software)
        self.label.setGeometry(QtCore.QRect(40,80,411,41))
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.b_eng = QtGui.QPushButton(self.software)
        self.b_eng.setGeometry(QtCore.QRect(330,200,121,61))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/instalador/img/eng.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.b_eng.setIcon(icon)
        self.b_eng.setIconSize(QtCore.QSize(32,32))
        self.b_eng.setCheckable(True)
        self.b_eng.setObjectName("b_eng")
        self.b_esp = QtGui.QPushButton(self.software)
        self.b_esp.setGeometry(QtCore.QRect(180,200,121,61))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/instalador/img/esp.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.b_esp.setIcon(icon)
        self.b_esp.setIconSize(QtCore.QSize(32,32))
        self.b_esp.setCheckable(True)
        self.b_esp.setObjectName("b_esp")
        self.b_cat = QtGui.QPushButton(self.software)
        self.b_cat.setGeometry(QtCore.QRect(40,200,121,61))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/instalador/img/cat.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.b_cat.setIcon(icon)
        self.b_cat.setIconSize(QtCore.QSize(32,32))
        self.b_cat.setCheckable(True)
        self.b_cat.setObjectName("b_cat")
        self.l_bandera = QtGui.QLabel(self.software)
        self.l_bandera.setGeometry(QtCore.QRect(190,310,101,101))
        self.l_bandera.setPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/instalador/img/cat.png"))
        self.l_bandera.setScaledContents(True)
        self.l_bandera.setObjectName("l_bandera")
        self.pageWidget.addWidget(self.software)
        self.label_3 = QtGui.QLabel(FormLanguage)
        self.label_3.setGeometry(QtCore.QRect(20,10,90,90))
        self.label_3.setPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/kademar.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.b_sortir = QtGui.QPushButton(FormLanguage)
        self.b_sortir.setGeometry(QtCore.QRect(20,540,131,41))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/enrera.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.b_sortir.setIcon(icon)
        self.b_sortir.setObjectName("b_sortir")
        self.b_SaX = QtGui.QPushButton(FormLanguage)
        self.b_SaX.setGeometry(QtCore.QRect(20,490,131,41))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/enrera.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.b_SaX.setIcon(icon)
        self.b_SaX.setObjectName("b_SaX")

        self.retranslateUi(FormLanguage)
        self.pageWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(FormLanguage)

    def retranslateUi(self, FormLanguage):
        FormLanguage.setWindowTitle(QtGui.QApplication.translate("FormLanguage", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("FormLanguage", "Language", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("FormLanguage", "You can change the default system language.", None, QtGui.QApplication.UnicodeUTF8))
        self.b_eng.setText(QtGui.QApplication.translate("FormLanguage", "English", None, QtGui.QApplication.UnicodeUTF8))
        self.b_esp.setText(QtGui.QApplication.translate("FormLanguage", "Castellano", None, QtGui.QApplication.UnicodeUTF8))
        self.b_cat.setText(QtGui.QApplication.translate("FormLanguage", "Català", None, QtGui.QApplication.UnicodeUTF8))
        self.b_sortir.setText(QtGui.QApplication.translate("FormLanguage", "Back", None, QtGui.QApplication.UnicodeUTF8))
        self.b_SaX.setText(QtGui.QApplication.translate("FormLanguage", "Save && Exit", None, QtGui.QApplication.UnicodeUTF8))

