# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/pppoe.ui'
#
# Created: Sat Dec 26 04:03:35 2009
#      by: PyQt4 UI code generator 4.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_FormPPPoE(object):
    def setupUi(self, FormPPPoE):
        FormPPPoE.setObjectName("FormPPPoE")
        FormPPPoE.resize(800,600)
        FormPPPoE.setMinimumSize(QtCore.QSize(800,600))
        self.label_2 = QtGui.QLabel(FormPPPoE)
        self.label_2.setGeometry(QtCore.QRect(0,0,800,600))
        self.label_2.setPixmap(QtGui.QPixmap("../../../../../../usr/share/kademar/utils/cadi/img/bg/cadi.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.pages = QtGui.QStackedWidget(FormPPPoE)
        self.pages.setGeometry(QtCore.QRect(210,70,561,481))
        self.pages.setObjectName("pages")
        self.software = QtGui.QWidget()
        self.software.setObjectName("software")
        self.label_4 = QtGui.QLabel(self.software)
        self.label_4.setGeometry(QtCore.QRect(19,20,461,21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label = QtGui.QLabel(self.software)
        self.label.setGeometry(QtCore.QRect(30,80,411,51))
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.l_logo_blth = QtGui.QLabel(self.software)
        self.l_logo_blth.setGeometry(QtCore.QRect(350,240,121,141))
        self.l_logo_blth.setPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/pppoe.png"))
        self.l_logo_blth.setObjectName("l_logo_blth")
        self.b_inicia = QtGui.QPushButton(self.software)
        self.b_inicia.setGeometry(QtCore.QRect(60,280,261,71))
        self.b_inicia.setObjectName("b_inicia")
        self.label_6 = QtGui.QLabel(self.software)
        self.label_6.setGeometry(QtCore.QRect(30,130,491,71))
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_6.setFont(font)
        self.label_6.setFrameShape(QtGui.QFrame.Box)
        self.label_6.setFrameShadow(QtGui.QFrame.Raised)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.pages.addWidget(self.software)
        self.page = QtGui.QWidget()
        self.page.setObjectName("page")
        self.label_5 = QtGui.QLabel(self.page)
        self.label_5.setGeometry(QtCore.QRect(60,70,191,20))
        self.label_5.setObjectName("label_5")
        self.list_net_dev = QtGui.QListWidget(self.page)
        self.list_net_dev.setGeometry(QtCore.QRect(60,110,421,211))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.list_net_dev.setFont(font)
        self.list_net_dev.setObjectName("list_net_dev")
        self.b_finish = QtGui.QPushButton(self.page)
        self.b_finish.setGeometry(QtCore.QRect(380,370,71,61))
        self.b_finish.setObjectName("b_finish")
        self.b_disconfigure = QtGui.QPushButton(self.page)
        self.b_disconfigure.setGeometry(QtCore.QRect(70,370,71,61))
        self.b_disconfigure.setObjectName("b_disconfigure")
        self.pages.addWidget(self.page)
        self.label_3 = QtGui.QLabel(FormPPPoE)
        self.label_3.setGeometry(QtCore.QRect(20,10,90,90))
        self.label_3.setPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/kademar.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.b_sortir = QtGui.QPushButton(FormPPPoE)
        self.b_sortir.setGeometry(QtCore.QRect(20,530,131,41))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/enrera.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.b_sortir.setIcon(icon)
        self.b_sortir.setObjectName("b_sortir")

        self.retranslateUi(FormPPPoE)
        self.pages.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(FormPPPoE)

    def retranslateUi(self, FormPPPoE):
        FormPPPoE.setWindowTitle(QtGui.QApplication.translate("FormPPPoE", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("FormPPPoE", "ADSL/PPPoE", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("FormPPPoE", "Here you can configure ADSL PPP over Ethernet.", None, QtGui.QApplication.UnicodeUTF8))
        self.b_inicia.setText(QtGui.QApplication.translate("FormPPPoE", "Start PPPoE Detection\n"
"(Can take a while, be patient)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("FormPPPoE", "This isn\'t the normal connection way. So, if you aren\'t sure that you need this kind of connection, we recommend to quit from this module", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("FormPPPoE", "Select Net Device", None, QtGui.QApplication.UnicodeUTF8))
        self.b_finish.setText(QtGui.QApplication.translate("FormPPPoE", "Next", None, QtGui.QApplication.UnicodeUTF8))
        self.b_disconfigure.setText(QtGui.QApplication.translate("FormPPPoE", "Disconfig", None, QtGui.QApplication.UnicodeUTF8))
        self.b_sortir.setText(QtGui.QApplication.translate("FormPPPoE", "Back", None, QtGui.QApplication.UnicodeUTF8))

