# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/services.ui'
#
# Created: Sat Dec 26 04:03:35 2009
#      by: PyQt4 UI code generator 4.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_FormServices(object):
    def setupUi(self, FormServices):
        FormServices.setObjectName("FormServices")
        FormServices.resize(800,600)
        FormServices.setMinimumSize(QtCore.QSize(800,600))
        self.label_2 = QtGui.QLabel(FormServices)
        self.label_2.setGeometry(QtCore.QRect(0,0,800,600))
        self.label_2.setPixmap(QtGui.QPixmap("../../../../../../usr/share/kademar/utils/cadi/img/bg/cadi.png"))
        self.label_2.setScaledContents(False)
        self.label_2.setObjectName("label_2")
        self.pageWidget = QtGui.QStackedWidget(FormServices)
        self.pageWidget.setGeometry(QtCore.QRect(210,50,571,501))
        self.pageWidget.setObjectName("pageWidget")
        self.software = QtGui.QWidget()
        self.software.setObjectName("software")
        self.label_4 = QtGui.QLabel(self.software)
        self.label_4.setGeometry(QtCore.QRect(9,10,471,21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label = QtGui.QLabel(self.software)
        self.label.setGeometry(QtCore.QRect(40,80,411,41))
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.l_logo_blth = QtGui.QLabel(self.software)
        self.l_logo_blth.setGeometry(QtCore.QRect(380,200,131,141))
        self.l_logo_blth.setPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/services.png"))
        self.l_logo_blth.setObjectName("l_logo_blth")
        self.groupBox = QtGui.QGroupBox(self.software)
        self.groupBox.setGeometry(QtCore.QRect(30,160,331,211))
        self.groupBox.setObjectName("groupBox")
        self.cb_samba = QtGui.QCheckBox(self.groupBox)
        self.cb_samba.setGeometry(QtCore.QRect(20,40,281,25))
        self.cb_samba.setObjectName("cb_samba")
        self.cb_apache = QtGui.QCheckBox(self.groupBox)
        self.cb_apache.setGeometry(QtCore.QRect(20,70,281,25))
        self.cb_apache.setObjectName("cb_apache")
        self.cb_mysql = QtGui.QCheckBox(self.groupBox)
        self.cb_mysql.setGeometry(QtCore.QRect(20,100,281,25))
        self.cb_mysql.setObjectName("cb_mysql")
        self.cb_cups = QtGui.QCheckBox(self.groupBox)
        self.cb_cups.setGeometry(QtCore.QRect(20,130,271,25))
        self.cb_cups.setObjectName("cb_cups")
        self.cb_ssh = QtGui.QCheckBox(self.groupBox)
        self.cb_ssh.setGeometry(QtCore.QRect(20,160,291,25))
        self.cb_ssh.setObjectName("cb_ssh")
        self.pageWidget.addWidget(self.software)
        self.label_3 = QtGui.QLabel(FormServices)
        self.label_3.setGeometry(QtCore.QRect(20,10,90,90))
        self.label_3.setPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/kademar.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.b_sortir = QtGui.QPushButton(FormServices)
        self.b_sortir.setGeometry(QtCore.QRect(20,530,121,41))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/enrera.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.b_sortir.setIcon(icon)
        self.b_sortir.setObjectName("b_sortir")
        self.b_SaX = QtGui.QPushButton(FormServices)
        self.b_SaX.setGeometry(QtCore.QRect(20,470,121,41))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/enrera.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.b_SaX.setIcon(icon)
        self.b_SaX.setObjectName("b_SaX")

        self.retranslateUi(FormServices)
        self.pageWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(FormServices)

    def retranslateUi(self, FormServices):
        FormServices.setWindowTitle(QtGui.QApplication.translate("FormServices", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("FormServices", "System Services", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("FormServices", "Here you can define what services do you want to run", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("FormServices", "Services", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_samba.setText(QtGui.QApplication.translate("FormServices", "Samba - Sharing Files", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_apache.setText(QtGui.QApplication.translate("FormServices", "Apache2 - Web Server", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_mysql.setText(QtGui.QApplication.translate("FormServices", "MySQL - Database Server", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_cups.setText(QtGui.QApplication.translate("FormServices", "CUPS - Print Service", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_ssh.setText(QtGui.QApplication.translate("FormServices", "SSH - Secure Conection Server", None, QtGui.QApplication.UnicodeUTF8))
        self.b_sortir.setText(QtGui.QApplication.translate("FormServices", "Back", None, QtGui.QApplication.UnicodeUTF8))
        self.b_SaX.setText(QtGui.QApplication.translate("FormServices", "Save && Exit", None, QtGui.QApplication.UnicodeUTF8))

