# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/users.ui'
#
# Created: Sat Dec 26 04:03:36 2009
#      by: PyQt4 UI code generator 4.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_FormUsers(object):
    def setupUi(self, FormUsers):
        FormUsers.setObjectName("FormUsers")
        FormUsers.resize(800,600)
        FormUsers.setMinimumSize(QtCore.QSize(800,600))
        self.label_2 = QtGui.QLabel(FormUsers)
        self.label_2.setGeometry(QtCore.QRect(0,0,800,600))
        self.label_2.setPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/bg/cadi.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.pages = QtGui.QStackedWidget(FormUsers)
        self.pages.setGeometry(QtCore.QRect(240,70,491,481))
        self.pages.setObjectName("pages")
        self.software = QtGui.QWidget()
        self.software.setObjectName("software")
        self.label_4 = QtGui.QLabel(self.software)
        self.label_4.setGeometry(QtCore.QRect(9,20,471,21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label = QtGui.QLabel(self.software)
        self.label.setGeometry(QtCore.QRect(40,80,411,41))
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.l_logo_blth = QtGui.QLabel(self.software)
        self.l_logo_blth.setGeometry(QtCore.QRect(300,30,131,101))
        self.l_logo_blth.setPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/users.png"))
        self.l_logo_blth.setObjectName("l_logo_blth")
        self.list_user = QtGui.QListWidget(self.software)
        self.list_user.setGeometry(QtCore.QRect(30,190,256,192))
        self.list_user.setIconSize(QtCore.QSize(32,32))
        self.list_user.setObjectName("list_user")
        self.b_delUser = QtGui.QPushButton(self.software)
        self.b_delUser.setGeometry(QtCore.QRect(300,330,151,51))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/list-remove-user.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.b_delUser.setIcon(icon)
        self.b_delUser.setIconSize(QtCore.QSize(32,32))
        self.b_delUser.setObjectName("b_delUser")
        self.b_addUser = QtGui.QPushButton(self.software)
        self.b_addUser.setGeometry(QtCore.QRect(300,190,151,51))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/list_add_user.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.b_addUser.setIcon(icon)
        self.b_addUser.setIconSize(QtCore.QSize(32,32))
        self.b_addUser.setObjectName("b_addUser")
        self.b_modifyUser = QtGui.QPushButton(self.software)
        self.b_modifyUser.setGeometry(QtCore.QRect(300,250,151,51))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/user-properties.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.b_modifyUser.setIcon(icon)
        self.b_modifyUser.setIconSize(QtCore.QSize(32,32))
        self.b_modifyUser.setObjectName("b_modifyUser")
        self.l_warn = QtGui.QLabel(self.software)
        self.l_warn.setGeometry(QtCore.QRect(60,420,331,20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170,0,0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active,QtGui.QPalette.WindowText,brush)
        brush = QtGui.QBrush(QtGui.QColor(170,0,0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive,QtGui.QPalette.WindowText,brush)
        brush = QtGui.QBrush(QtGui.QColor(115,120,124))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled,QtGui.QPalette.WindowText,brush)
        self.l_warn.setPalette(palette)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.l_warn.setFont(font)
        self.l_warn.setObjectName("l_warn")
        self.pages.addWidget(self.software)
        self.page = QtGui.QWidget()
        self.page.setObjectName("page")
        self.le_user = QtGui.QLineEdit(self.page)
        self.le_user.setGeometry(QtCore.QRect(200,130,201,26))
        self.le_user.setObjectName("le_user")
        self.le_login = QtGui.QLineEdit(self.page)
        self.le_login.setGeometry(QtCore.QRect(200,180,201,26))
        self.le_login.setObjectName("le_login")
        self.le_passwd = QtGui.QLineEdit(self.page)
        self.le_passwd.setGeometry(QtCore.QRect(200,230,201,26))
        self.le_passwd.setEchoMode(QtGui.QLineEdit.Password)
        self.le_passwd.setObjectName("le_passwd")
        self.le_passwd2 = QtGui.QLineEdit(self.page)
        self.le_passwd2.setGeometry(QtCore.QRect(200,280,201,26))
        self.le_passwd2.setEchoMode(QtGui.QLineEdit.Password)
        self.le_passwd2.setObjectName("le_passwd2")
        self.label_7 = QtGui.QLabel(self.page)
        self.label_7.setGeometry(QtCore.QRect(42,133,131,20))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtGui.QLabel(self.page)
        self.label_8.setGeometry(QtCore.QRect(60,183,121,20))
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtGui.QLabel(self.page)
        self.label_9.setGeometry(QtCore.QRect(60,233,121,20))
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtGui.QLabel(self.page)
        self.label_10.setGeometry(QtCore.QRect(30,283,151,20))
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.b_create = QtGui.QPushButton(self.page)
        self.b_create.setGeometry(QtCore.QRect(310,380,121,41))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/ok.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.b_create.setIcon(icon)
        self.b_create.setIconSize(QtCore.QSize(22,22))
        self.b_create.setObjectName("b_create")
        self.b_cancel = QtGui.QPushButton(self.page)
        self.b_cancel.setGeometry(QtCore.QRect(150,380,121,41))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/enrera.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.b_cancel.setIcon(icon)
        self.b_cancel.setIconSize(QtCore.QSize(22,22))
        self.b_cancel.setObjectName("b_cancel")
        self.label_11 = QtGui.QLabel(self.page)
        self.label_11.setGeometry(QtCore.QRect(10,30,471,20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.pages.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName("page_2")
        self.le_modify_user = QtGui.QLineEdit(self.page_2)
        self.le_modify_user.setGeometry(QtCore.QRect(200,280,201,26))
        self.le_modify_user.setObjectName("le_modify_user")
        self.l_pass = QtGui.QLabel(self.page_2)
        self.l_pass.setGeometry(QtCore.QRect(42,183,131,20))
        self.l_pass.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.l_pass.setObjectName("l_pass")
        self.le_modify_pass = QtGui.QLineEdit(self.page_2)
        self.le_modify_pass.setGeometry(QtCore.QRect(200,180,201,26))
        self.le_modify_pass.setEchoMode(QtGui.QLineEdit.Password)
        self.le_modify_pass.setObjectName("le_modify_pass")
        self.b_cancel_2 = QtGui.QPushButton(self.page_2)
        self.b_cancel_2.setGeometry(QtCore.QRect(150,380,121,41))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/enrera.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.b_cancel_2.setIcon(icon)
        self.b_cancel_2.setIconSize(QtCore.QSize(22,22))
        self.b_cancel_2.setObjectName("b_cancel_2")
        self.label_13 = QtGui.QLabel(self.page_2)
        self.label_13.setGeometry(QtCore.QRect(10,30,471,20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.b_modify = QtGui.QPushButton(self.page_2)
        self.b_modify.setGeometry(QtCore.QRect(310,380,121,41))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/ok.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.b_modify.setIcon(icon)
        self.b_modify.setIconSize(QtCore.QSize(22,22))
        self.b_modify.setObjectName("b_modify")
        self.ch_pass = QtGui.QCheckBox(self.page_2)
        self.ch_pass.setGeometry(QtCore.QRect(60,140,191,25))
        self.ch_pass.setObjectName("ch_pass")
        self.l_user = QtGui.QLabel(self.page_2)
        self.l_user.setGeometry(QtCore.QRect(40,280,131,20))
        self.l_user.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.l_user.setObjectName("l_user")
        self.ch_username = QtGui.QCheckBox(self.page_2)
        self.ch_username.setGeometry(QtCore.QRect(60,240,241,25))
        self.ch_username.setObjectName("ch_username")
        self.pages.addWidget(self.page_2)
        self.label_3 = QtGui.QLabel(FormUsers)
        self.label_3.setGeometry(QtCore.QRect(20,10,90,90))
        self.label_3.setPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/kademar.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.b_sortir = QtGui.QPushButton(FormUsers)
        self.b_sortir.setGeometry(QtCore.QRect(20,540,131,41))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/cadi/img/enrera.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.b_sortir.setIcon(icon)
        self.b_sortir.setObjectName("b_sortir")

        self.retranslateUi(FormUsers)
        self.pages.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(FormUsers)

    def retranslateUi(self, FormUsers):
        FormUsers.setWindowTitle(QtGui.QApplication.translate("FormUsers", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("FormUsers", "Users", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("FormUsers", "You can manage you user accounts", None, QtGui.QApplication.UnicodeUTF8))
        self.b_delUser.setText(QtGui.QApplication.translate("FormUsers", "Delete User", None, QtGui.QApplication.UnicodeUTF8))
        self.b_addUser.setText(QtGui.QApplication.translate("FormUsers", "Add User", None, QtGui.QApplication.UnicodeUTF8))
        self.b_modifyUser.setText(QtGui.QApplication.translate("FormUsers", "Modify User", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("FormUsers", "User Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("FormUsers", "Account Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("FormUsers", "Password", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("FormUsers", "Repeat Password", None, QtGui.QApplication.UnicodeUTF8))
        self.b_create.setText(QtGui.QApplication.translate("FormUsers", "Accept", None, QtGui.QApplication.UnicodeUTF8))
        self.b_cancel.setText(QtGui.QApplication.translate("FormUsers", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("FormUsers", "Create New User Account", None, QtGui.QApplication.UnicodeUTF8))
        self.l_pass.setText(QtGui.QApplication.translate("FormUsers", "Password", None, QtGui.QApplication.UnicodeUTF8))
        self.b_cancel_2.setText(QtGui.QApplication.translate("FormUsers", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("FormUsers", "Modify User Account", None, QtGui.QApplication.UnicodeUTF8))
        self.b_modify.setText(QtGui.QApplication.translate("FormUsers", "Accept", None, QtGui.QApplication.UnicodeUTF8))
        self.ch_pass.setText(QtGui.QApplication.translate("FormUsers", "Change Pasword", None, QtGui.QApplication.UnicodeUTF8))
        self.l_user.setText(QtGui.QApplication.translate("FormUsers", "User Name", None, QtGui.QApplication.UnicodeUTF8))
        self.ch_username.setText(QtGui.QApplication.translate("FormUsers", "Change User Name", None, QtGui.QApplication.UnicodeUTF8))
        self.b_sortir.setText(QtGui.QApplication.translate("FormUsers", "Back", None, QtGui.QApplication.UnicodeUTF8))

