#!/bin/bash

#################################################
# Script per Configurar el sistema a la nova    #
#         -------------------------             #
#    Preparat per la kademar 4.0 - 3 Nov 2005   #
#    Preparat per la kademar 4.1 - 2 Feb 2006   #
#    Preparat per la kademar 4.7 - 24 Mar 2008  #
#    Preparat per la kademar 4.8 - 07 Feb 2009  #
#    Llicenciat Sota GNU/GPL 2.0 o Superiors    #
#################################################

. /tmp/instalador-environment


#Carreguem algunes variables des del fitxer general live-cd
[ -e /usr/share/kademar/config-livecd ] && . /usr/share/kademar/config-livecd

fitxer_serveis_en_rcS="/usr/share/kademar/utils/instalador/scripts/scripts-lyra/install-sysconfig_serveis_en_rcS"
fitxer_serveis_en_rc1="/usr/share/kademar/utils/instalador/scripts/scripts-lyra/install-sysconfig_serveis_en_rc1_single"
fitxer_serveis_en_rc_normals="/usr/share/kademar/utils/instalador/scripts/scripts-lyra/install-sysconfig_serveis_en_rc_normals"
fitxer_serveis_en_rc_apagada="/usr/share/kademar/utils/instalador/scripts/scripts-lyra/install-sysconfig_serveis_en_rc_apagada"

ruta_fstab="/etc/fstab"

#Ens assegurem de que està buit el fitxer de restauracio de Serveis dels rc?.d
echo > "$DESTI/serveis"

#############
#### rcS.d INICI
#############
cat "$fitxer_serveis_en_rcS" 2>/dev/null | while read line
do
	echo "update-rc.d `echo $line | awk ' { print $2 } '` start `echo $line | awk ' { print $1 } '` S ." >> "$DESTI/serveis"
done

#############
#### rc0-6   NORMALS
#############

cat "$fitxer_serveis_en_rc_normals" 2>/dev/null | while read line
do
	echo "update-rc.d `echo $line | awk ' { print $2 } '` defaults `echo $line | awk ' { print $1 } '`" >> "$DESTI/serveis"
done


#############
#### rc1.d SINGLE
#############

cat $fitxer_serveis_en_rc1 2>/dev/null | while read line
do
	if [ -z "`echo $line | awk ' { print $3 } '`" ]; then
		funcio="stop"
	else
		funcio="start"
	fi
	echo "update-rc.d `echo $line | awk ' { print $2 } '` $funcio `echo $line | awk ' { print $1 } '` 1 ." >> $DESTI/serveis
done



# Create rc0.d and rc6.d OK - fix:  filesystem NOT clean (umount / busy)
cat "$fitxer_serveis_en_rc_apagada" 2>/dev/null | while read line
do
    rm /etc/rc0.d/*`echo $line | awk ' { print $3 } '` 2>/dev/null
    rm /etc/rc6.d/*`echo $line | awk ' { print $3 } '` 2>/dev/null
    echo "ln -s ../init.d/`echo $line | awk ' { print $3 } '` /etc/rc0.d/`echo $line | awk ' { print $1 } '``echo $line | awk ' { print $2 } '``echo $line | awk ' { print $3 } '`" >> "$DESTI/serveis"
    echo "ln -s ../init.d/`echo $line | awk ' { print $3 } '` /etc/rc6.d/`echo $line | awk ' { print $1 } '``echo $line | awk ' { print $2 } '``echo $line | awk ' { print $3 } '`" >> "$DESTI/serveis"
done



#########################


#Busquem i carreguem el ACPI, tan per portatils com per sobretaula
if [ -d /proc/acpi ]; then
	if [ -z "`grep noacpi /proc/cmdline`" ]; then
		echo "update-rc.d acpid defaults 20" >> "$DESTI/serveis"
	fi
fi

#Càrrega de les tecles de toshiba, si existeixen
if [ -d /proc/acpi/toshiba/keys ]; then
		echo "update-rc.d fnfxd defaults 20" >> "$DESTI/serveis"
fi

#Fem el mateix amb el APM
if [ -d /proc/apm ]; then
	# APM
	if [ -z "`grep noacpi /proc/cmdline`" ]; then
		echo "update-rc.d apmd defaults 20" >> "$DESTI/serveis"
	fi
fi

#Win-Modems  Detection
if [ -n "`lsmod | grep slamr`" -o -n "`lsmod | grep slusb`" ]; then
	echo "update-rc.d sl-modem-daemon defaults 12" >> "$DESTI/serveis"
fi


#CREEM ELS SERVEIS
chroot "$DESTI" sh /serveis

#Borrem la prova del delicte  :-D
rm -f "$DESTI/serveis"


#Borrem l'entrada del kdm en el 99 i el posem en el 01 (solament en apagat)
rm -fr $DESTI/etc/rc[106].d/K99kdm
for i in 1 0 6
do
	ln -s ../init.d/kdm "$DESTI/etc/rc$i.d/K01kdm"
done

#halt and reboot services
ln -s ../init.d/halt "$DESTI/etc/rc0.d/S90halt"
ln -s ../init.d/reboot "$DESTI/etc/rc6.d/S90reboot"


#Borrem les entrades del XDM
rm -fr $DESTI/etc/rc?.d/*xdm


##### MODIFICACIO KDMRC  ######
##  IT'S NOW ON THE KDE kademar PACKAGE
##### FI MODIFICACIO KDMRC  ######


#Creem les entrades pel klik en /etc/fstab
echo "
#Klik Lines
/tmp/app/1/image /tmp/app/1 cramfs,iso9660 user,noauto,ro,loop,exec 0 0
/tmp/app/2/image /tmp/app/2 cramfs,iso9660 user,noauto,ro,loop,exec 0 0
/tmp/app/3/image /tmp/app/3 cramfs,iso9660 user,noauto,ro,loop,exec 0 0
/tmp/app/4/image /tmp/app/4 cramfs,iso9660 user,noauto,ro,loop,exec 0 0
/tmp/app/5/image /tmp/app/5 cramfs,iso9660 user,noauto,ro,loop,exec 0 0
/tmp/app/6/image /tmp/app/6 cramfs,iso9660 user,noauto,ro,loop,exec 0 0
/tmp/app/7/image /tmp/app/7 cramfs,iso9660 user,noauto,ro,loop,exec 0 0" >> "$DESTI$ruta_fstab"

#Fem que  www.kademar.org sigui la pagina per defecte del firefox
[ -e "$DESTI/etc/mozilla-firefox/profile/prefs.js" ] && echo 'user_pref("browser.startup.homepage", "http://www.kademar.org");
user_pref(\"network.protocol-handler.app.klik\", \"~/.klik\"); >> ' >> "$DESTI/etc/mozilla-firefox/profile/prefs.js"


#substitution of all wallpapers from configurated monitor (panoramic/normal)
[ -e "$DESTI/var/kademar/monitor" ] && . "$DESTI/var/kademar/monitor"
[ -z "$monitor" ] && monitor=normal
[ -e /usr/share/kademar/config-livecd ] && . /usr/share/kademar/config-livecd


if [ "$monitor" = panoramic ]; then
    for i in  /usr/share/apps/kdm/themes/kademar/background.png /etc/splashy/themes/kademar/background.png
    do
        rm -f "$DESTI$i"
        cp "$xsession_background_panoramic" "$DESTI$i"
    done
fi


###### CONFIGURE LOCALE  ##########
CMDLINE=`cat /proc/cmdline`

# same for strings
stringinstring(){
case "$2" in *$1*) return 0;; esac
return 1
}

# Reread boot command line; echo last parameter's argument or return false.
getbootparam(){
stringinstring " $1=" "$CMDLINE" || return 1
result="${CMDLINE##*$1=}"
result="${result%%[ 	]*}"
echo "$result"
return 0
}

##### END CONFIGURE LOCALE  ##########