#!/bin/bash

list=`ls`
for i in $list
do
	if [ -e $i/trunk ]; then
	    cd $i/trunk
	    debuild -r fakeroot
	    cd ../..
	fi
done

echo "enter folder where copy .deb files"
read folder

if [ -n "$folder" ]; then
    mkdir -p "$folder"
    for i in $list
    do
        mv $i/*.deb "$folder" 2>/dev/null
    done
fi
