Document: squashfs-tools-lzma
Title: Debian squashfs-tools-lzma Manual
Author: <insert document author here>
Abstract: This manual describes what squashfs-tools-lzma is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/squashfs-tools-lzma/squashfs-tools-lzma.sgml.gz

Format: postscript
Files: /usr/share/doc/squashfs-tools-lzma/squashfs-tools-lzma.ps.gz

Format: text
Files: /usr/share/doc/squashfs-tools-lzma/squashfs-tools-lzma.text.gz

Format: HTML
Index: /usr/share/doc/squashfs-tools-lzma/html/index.html
Files: /usr/share/doc/squashfs-tools-lzma/html/*.html

  
