#!/bin/bash

#################################################
# Script per instalar el GRUB com a boot-loader #
#         -------------------------             #
#    Parcialment extret dels Burnix-Scripts     #
#    Preparat per la kademar 4.0 - 3 Nov 2005   #
#    Llicenciat Sota GNU/GPL 2.0 o Superiors    #
#    Modifict 4-4-08  - kademar 5.0		#
#################################################

#MODE TO CALL IT
# install-bootloader  [hda1]  [Destination Target]
. /tmp/instalador-environment

#Assignem el parametre 1 al dispositiu
# DEV="$1"
#Si no n'hem assignat cap, para l'escript amb un error
# [ -z "$DEV" -o "$DEV" = "0" ] && echo "I NEED A DEVICE TO OPERATE WITH!!!" && exit 1
#Assignem una variable amb el dispositiu sense numero
# DEV_SENSE_NUMERO=${DEV%[1-9]}

#Assignem el parametre 2 al desti
# DESTI="$2"
#Si no n'hem assignat cap, assignem el per defecte en la kademar 4.0
# [ -z "$DESTI" -o "$DESTI" = "0" ] && DESTI="/instalador/desti"

#Versió del Kernel
# kernel="`uname -r`"

#Borrem una possible carpeta grub anterior, i la tornem a crear
# rm -fr $DESTI/boot/grub 
# mkdir -p $DESTI/boot/grub 

#Copiem propiament el grub en la seva carpeta
# cp $DESTI/lib/grub/i386-pc/* $DESTI/boot/grub/ 
#Borrem l'arxiu de configuració del grub en cas de que existeixi
# [ -e $DESTI/boot/grub/menu.lst ] && rm -f $DESTI/boot/grub/menu.lst
# [ -e $DESTI/boot/grub/device.map ] && rm -f $DESTI/boot/grub/device.map

#Borrem el mtab
# rm -f  $DESTI/etc/mtab
#I creem una entrada estandar per l'instalador
# echo "/dev/$DEV / reiserfs rw 0 0" > $DESTI/etc/mtab
# 

#Creem el Device.map amb la informacio dels dispositius
# echo quit \
#   | /sbin/grub --batch --no-floppy --device-map=$DESTI/boot/grub/device.map


#chroot $DESTI sed -i "s~# kopt.*~# kopt=root=$DESTI_ROOT $DEF_BOOTPARMS~g" /boot/grub/menu.lst 

#TODO find a way to not have to do that twice
#chroot $DESTI update-grub -y  

#Creem l'initrd per el kernel
# chroot $DESTI mkinitrd -r $DEV -o /boot/initrd.img-$kernel $kernel

#chroot $DESTI update-grub -y  

#if [ -f /cdrom/boot/grub/bootlogo ] ; then
	#echo "${BLUE}Copying  ${GREEN}gfxboot${NORMAL}"
	#cp /cdrom/boot/grub/bootlogo $DESTI/boot/grub
	#mv $DESTI/boot/grub/menu.lst $DESTI/boot/grub/menu.lst.ori
	#echo "gfxmenu = /boot/grub/bootlogo" > $DESTI/boot/grub/menu.lst
	#cat $DESTI/boot/grub/menu.lst.ori >> $DESTI/boot/grub/menu.lst
	#rm $DESTI/boot/grub/menu.lst.ori
#fi

# grub-install --no-floppy --force-lba --root-directory=$DESTI /dev/$DEV_SENSE_NUMERO

# echo "grub-install --no-floppy --force-lba --root-directory=$DESTI /dev/$DEV_SENSE_NUMERO"

#echo "${BLUE}Boot parms: ${GREEN}$DEF_BOOTPARMS${NORMAL}"

#Borrem l'entrada genèrica del mtab
rm -f $DESTI/etc/mtab
#Restaurem l'entrada original del mtab
ln -s /proc/mounts $DESTI/etc/mtab
