#!/bin/bash

driver(){
trobat=no
cat /etc/X11/xorg.conf | grep -v \# | grep -vi input | while read line
do
[ -n "`echo $line | grep Section | grep \"Device\"`" ] && trobat=si

	if [ "$trobat" == "si" ]; then
		dev=`echo "$line" | grep Driver | cut -d\" -f2`
		[ -n "$dev" ] && echo "$dev" && exit
	fi

done
}

display_driver="$(driver)"


######################   RECUPERA ACCELERACIO  #####################
#extret de detectachipset

# Si es NVIDIA el modul, mirem de que el libgl estigui ben configurat
libglx_nvidia="`ls $dirbase/usr/lib/xorg/modules/extensions/libglx.so.1.0* 2>/dev/null`"
libgl_nvidia="`ls $dirbase/usr/lib/libGL.so.1.0* 2>/dev/null`"

#Suport als nous últims drivers de nvidia
[ -z "$libglx_nvidia" ] && libglx_nvidia="`ls $dirbase/usr/lib/xorg/modules/extensions/libglx.so.????* 2>/dev/null`"
[ -z "$libgl_nvidia" ] && libgl_nvidia="`ls $dirbase/usr/lib/libGL.so.????* 2>/dev/null`"

#Si el dirbase no es 0, treiem la seva influencia en el path
#Sino els links es crearien malament, ja que portarien el dirbase en la ruta d'enllaç
if [ -n "$dirbase" ]; then
	libglx_nvidia="`echo $libglx_nvidia | sed s:$dirbase::g`"
	libgl_nvidia="`echo $libglx_nvidia | sed s:$dirbase::g`"
fi

# Pels moduls NVIDIA, voldrem el Link, i si no, voldrem que sigui l'original
# Si es el modul nvidia i el GLX de nvidia està instal·lat
if [ "$display_driver" = "nvidia" -a -n "$libglx_nvidia" ]; then
	#Si no és un link (volem el link a les GLX de nvidia) el creem
	if [ ! -L "$dirbase/usr/lib/xorg/modules/extensions/libglx.so" ]; then
	#Copiem el glx vell per si l'hem de restaurar
		rm -f "$dirbase/usr/lib/xorg/modules/extensions/libglx.so_kademar_replaced"
		mv "$dirbase/usr/lib/xorg/modules/extensions/libglx.so" "$dirbase/usr/lib/xorg/modules/extensions/libglx.so_kademar_replaced"
		ln -s "$libglx_nvidia" "$dirbase/usr/lib/xorg/modules/extensions/libglx.so"
	fi
	#Posa l'enllaç cap a libGL de nvidia
	rm -f "$dirbase/usr/lib/libGL.so"
	rm -f "$dirbase/usr/lib/libGL.so.1"

	#Utilitza el normal, si el de NVIDIA no existeix
	[ -z "$libgl_nvidia" ] && libgl_nvidia="/usr/lib/libGL.so.1.2"
	ln -s "$libgl_nvidia" "$dirbase/usr/lib/libGL.so"
	ln -s "$libgl_nvidia" "$dirbase/usr/lib/libGL.so.1"
else
#si el link està fet (i no es NVIDIA el modul, o no existeix) i existeix la còpia (per si canviem  nvidia -> ati per.exemple)
	if [ -L "$dirbase/usr/lib/xorg/modules/extensions/libglx.so" -a -e "$dirbase/usr/lib/xorg/modules/extensions/libglx.so_kademar_replaced" ]; then
		rm -f "$dirbase/usr/lib/xorg/modules/extensions/libglx.so"
		cp "$dirbase/usr/lib/xorg/modules/extensions/libglx.so_kademar_replaced" "$dirbase/usr/lib/xorg/modules/extensions/libglx.so"
	fi

	#Restaura l'enllaç dels libGL
	rm -f "$dirbase/usr/lib/libGL.so"
	rm -f "$dirbase/usr/lib/libGL.so.1"
	ln -s "/usr/lib/libGL.so.1.2" "$dirbase/usr/lib/libGL.so.1"
	ln -s "/usr/lib/libGL.so.1.2" "$dirbase/usr/lib/libGL.so"
fi






