#!/bin/bash
### BEGIN INIT INFO
# Provides:          xsession
# Required-Start:    $local_fs $all
# Required-Stop:     $local_fs $remote_fs
# Should-Start:      console-screen kbd acpid dbus hal
# Should-Stop:       console-screen kbd
# Default-Start:     
# Default-Stop:      
# Short-Description: Start X session on Live-CD
# Description:       Xsession on Live-CD is usefull to start a non-installed system, in any pc.
### END INIT INFO
# /etc/init.d/xsession: start or stop the X display manager on Live-CD
# Script originally stolen from the kdm & xdm package
#
# description: Start de Xsession
#

# 8-9-09 - Added support to cmdline "nox"

[ "`arch`" = "x86_64" ] && arch="_amd64"

export PATH="/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin"

#Detect No X cmdline
for i in `cat /proc/cmdline`
do
    [ "$i" = "nox" ] &&  nox="true"
    [ "$i" = "server" ] &&  nox="true"
done



# Check boot commandline for specified option,
# echo last found argument, or return false.
getbootparam(){
 local result="" i CMDLINE
 read CMDLINE < /proc/cmdline
 for i in $CMDLINE; do
  case "$i" in $1=*) result="${i#*=}" ;; esac
 done
 [ -n "$result" ] || return 1
 echo "$result"
 return 0
}

# # Switch to default language
# [ -e /etc/default/locale ] && . /etc/default/locale
# 
# 
# 
# [ -n "$LANG" ] && export LANG
# [ -n "$LANGUAGE" ] && export LANGUAGE
# [ -n "$LC_MESSAGES" ] && export LC_MESSAGES
# [ -n "$LC_ALL" ] && export LC_ALL
# 


# Start function
start(){



 # Read default from /etc/default (Debian) and/or /etc/sysconfig (Knoppix)
. /etc/kademar/config-livecd
 GROUP="$user"
 SESSION="kde"
 XMODULE=""
xsesson_commands_file=/var/tmp/xsession-commands

XSERVER=Xorg
XCONFIG="/etc/X11/xorg.conf"

xserver_file=/var/tmp/xserver
[ -e $xserver_file ] && . $xserver_file

#full acces for desktop-selector
chmod 777 $xserver_file

KVER="`uname -r`"

 [ -n "$DESKTOP" ] || DESKTOP="$(getbootparam desktop)"
 [ -n "$DESKTOP" ] || DESKTOP="$SESSION"
#  [ -n "$DPI" ] || DPI="$(getbootparam dpi)"
#  [ -n "$DPI" ] || DPI="`grep Xft.dpi: /etc/X11/Xresources/x11-common | sed 's/:/ /g' | awk ' { print $2 } '`"
#  [ -n "$DPI" ] || DPI="96"


#  for xm in "$XMODULE" fbdev vesa nv radeon ati nvidia fglrx; do # XMODULE="" -> autodetect!

#   if [ -n "$xm" -a "$xm" != "$XMODULE" ]; then
#    # Recreate xorg.conf for new modulenv|radeon|ati
#    rm -f /etc/X11/xorg.conf
#    echo "XMODULE='$xm'" >> $xserver_file
#    #XORGOPTIONS=""
#    #case "$xm" in nv|fbdev|vesa) ;; *) XORGOPTIONS="$XORGOPTIONS -composite" ;; esac
#    /usr/share/kademar/scripts/engegada/xautoconf # $XORGOPTIONS
#   fi
  
  oldtime="$(date +'%s')"
  # Older compiz versions start gtk-window-decorator only if GNOME_DESKTOP_SESSION_ID is set.
#   sessreg -a -l :0 -x /etc/X11/xdm/Xservers $user

#start  Desktop Selector if requested
#if [ "$desktop_selector" != "no" ]; then
su -l -c "$precommand export STARTUP=desktop-selector$arch ; exec /usr/bin/startx -- vt5 -br -noreset -nolisten tcp" "$user" </dev/tty5 >/dev/null 2>&1 ; RC="$?"
## xserver_file is filled on  kademar-livecd-autoconfig
#fi

[ -e $xserver_file ] && . $xserver_file

 if [ "$RC" = "0" -a "$DESKTOP" != "none" ]; then
	
	
	#get real desktop
	STARTUP="start$DESKTOP"
	
	
	rm -f $xsesson_commands_file
	touch $xsesson_commands_file
	chown $user.$user $xsesson_commands_file
	
	case "$DESKTOP" in
		kde|KDE|Kde|kde3|KDE3|Kde3)
		echo "kde_restart" > $xsesson_commands_file
	
			[ -e /usr/bin/startkde ] && STARTUP=/usr/bin/startkde
			[ -e /opt/kde3/bin/startkde ] && STARTUP=/opt/kde3/bin/startkde
			[ -e /opt/trinity/bin/startkde ] && STARTUP=/opt/trinity/bin/startkde
			precommand="export XDM_MANAGED=\"/var/tmp/xsession-commands,maysd,mayfn,sched,method=classic\""

	
		;;
		kde4|KDE4|Kde4) 
		echo "kde_restart" > $xsesson_commands_file
		precommand="export XDM_MANAGED=\"/var/tmp/xsession-commands,maysd,mayfn,sched,method=classic\""
	
			STARTUP=startkde
		;;
	esac
	
	type -p "$STARTUP" >/dev/null 2>&1 || STARTUP="$DESKTOP-session"
	type -p "$STARTUP" >/dev/null 2>&1 || STARTUP="startlxde"

	
	# Create home if not existing.
	#  [ -d /home/"$user" ] || install -d -m 700 -o "$user" -g "$GROUP" /home/"$user"
	
# 	su -c "/usr/share/kademar/scripts/engegada/kademar-inici.d-standalone/common-configure_wallpapers" - "$user"
	
	su -l -c "$precommand export STARTUP=$STARTUP ; exec /usr/bin/startx -- vt5 -br -noreset -nolisten tcp" "$user" </dev/tty5 >/dev/null 2>&1 ; RC="$?"
  fi

#   sessreg -d -l :0 -x /etc/X11/xdm/Xservers $user
  # Temporary workaround for missing KDE/Gnome shutdown button
  if tail -1 /home/"$user"/.xsession-errors 2>/dev/null | egrep -q -e '(startkde: Done|^gnome)'; then
   /sbin/init 0
  fi
  newtime="$(date +'%s')"
  if [ "$((newtime - oldtime))" -lt 30 ]; then
   # If X stays up no longer than 30 secs, it crashed, probably.
   [ "$RC" = "0" ] || continue
   tail /var/log/Xorg.0.log | egrep -q "(^Fatal server error:|[Ss]egmentation)" && continue
  fi
  break
 done
 if [ "$RC" = "0" ]; then
  echo "${BLUE}$miss_acabat_sense${NORMAL}"
  		XSESSION_COMMAND=$(cat $xsesson_commands_file)
		NEXT_RUNLEVEL=0
	
		[ "$DESKTOP" = "icewm" ] && NEXT_RUNLEVEL=0
	
		if [ -n "$XSESSION_COMMAND" ]; then
			case "$XSESSION_COMMAND" in
			shutdown*halt*)
				NEXT_RUNLEVEL=0
			;;
			shutdown*reboot*)
				NEXT_RUNLEVEL=6
			;;
			*)
				/etc/init.d/kademar-livecd-xsession restart
			;;
			esac
		fi
		init $NEXT_RUNLEVEL
  return "$RC"
 else
 	error_msg
 fi
}

stop(){
 killall startx >/dev/null 2>&1
}

error_msg(){
 # Shutdown or failure messages
 case "$LANG" in
 *)
  ERRORMSG="[1mThe graphical subsystem could not be startet\nor terminated unexpectedly.\nMaybe your graphics adapter or monitor are not auto-configurable.\n\nPlease try to reboot and give some of the Knoppix-Cheatcodes\nat the initial boot:-prompt, which match your graphics adapter.\nExamples:\n   kademar xmodule=radeon (or ati, nv, cirrus, ...)\n   kademar xmodule=fbdev\n   kademar xmodule=vesa\n"
  RETURNPROMPT="Please hit ENTER to reboot.";;
 esac
 echo -e "$ERRORMSG"
}

### MAIN

case "$1" in
 start)
	if [ -z "$nox" ]; then
		start
	else
		#Configure some services - taken of kademarcenter
		sh /usr/share/kademar/scripts/services_nox
	fi
 ;;

 stop)  stop  ;;
 restart) stop; sleep 4; start;;
 *)
	echo "command not recognized $1"
 ;;
esac

exit $?
