Document: kademar-csic
Title: Debian kademar-csic Manual
Author: <insert document author here>
Abstract: This manual describes what kademar-csic is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/kademar-csic/kademar-csic.sgml.gz

Format: postscript
Files: /usr/share/doc/kademar-csic/kademar-csic.ps.gz

Format: text
Files: /usr/share/doc/kademar-csic/kademar-csic.text.gz

Format: HTML
Index: /usr/share/doc/kademar-csic/html/index.html
Files: /usr/share/doc/kademar-csic/html/*.html


