Document: kademar-heliox
Title: Debian kademar-heliox Manual
Author: <insert document author here>
Abstract: This manual describes what kademar-heliox is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/kademar-heliox/kademar-heliox.sgml.gz

Format: postscript
Files: /usr/share/doc/kademar-heliox/kademar-heliox.ps.gz

Format: text
Files: /usr/share/doc/kademar-heliox/kademar-heliox.text.gz

Format: HTML
Index: /usr/share/doc/kademar-heliox/html/index.html
Files: /usr/share/doc/kademar-heliox/html/*.html


