#!/bin/sh
# postrm script for kademar-heliox
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postrm> `remove'
#        * <postrm> `purge'
#        * <old-postrm> `upgrade' <new-version>
#        * <new-postrm> `failed-upgrade' <old-version>
#        * <new-postrm> `abort-install'
#        * <new-postrm> `abort-install' <old-version>
#        * <new-postrm> `abort-upgrade' <old-version>
#        * <disappearer's-postrm> `disappear' <overwriter>
#          <overwriter-version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package


case "$1" in
    purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)

        if [ remove = "$1" ]; then
                rm -f /boot/grub/message.kademar
                dpkg-divert --package kademar-heliox --remove --divert /boot/message.kademar.orig --rename /boot/grub/message.kademar

                rm -f /etc/inittab
                dpkg-divert --package kademar-heliox --remove --divert /etc/inittab.orig --rename /etc/inittab

                rm -f /etc/init.d/gdm
                dpkg-divert --package kademar-heliox --remove --divert /etc/init.d/dpkg/gdm.orig --rename /etc/init.d/gdm

                dpkg-divert --package kademar-heliox --remove --divert /etc/init.d/dpkg/kademar-installed.orig --rename /etc/init.d/kademar-installed

                rm -f /etc/init.d/adriane-screenreader
                dpkg-divert --package kademar-heliox --remove --divert /etc/init.d/dpkg/adriane-screenreader.orig --rename adriane-screenreader

                rm -f /etc/init.d/sbl
                dpkg-divert --package kademar-heliox --remove --divert /etc/init.d/dpkg/sbl.orig --rename sbl

                rm -f /etc/init.d/gdm
                dpkg-divert --package kademar-heliox --remove --divert /etc/init.d/dpkg/gdm.orig --rename /etc/init.d/gdm


                rm -f /etc/splash/splash
                ln -s /etc/splash/splash.kademar /etc/splash/splash

                rm -f /usr/share/kademar/utils/instalador/instalador.py
                dpkg-divert --package kademar-heliox --remove --divert /usr/share/kademar/utils/instalador/instalador.py.orig --rename /usr/share/kademar/utils/instalador/instalador.py

                rm -f /usr/share/kademar/utils/instalador/ui_instalador.py
                dpkg-divert --package kademar-heliox --remove --divert /usr/share/kademar/utils/instalador/ui_instalador.py.orig --rename /usr/share/kademar/utils/instalador/ui_instalador.py

                rm -f /usr/share/kademar/utils/instalador/scripts/make-grub_menu-version1
                dpkg-divert --package kademar-heliox --remove --divert /usr/share/kademar/utils/instalador/scripts/make-grub_menu-version1.orig --rename /usr/share/kademar/utils/instalador/scripts/make-grub_menu-version1

                rm -f /usr/share/kademar/utils/instalador-nano/scripts/bootinst.sh
                dpkg-divert --package kademar-heliox --remove --divert /usr/share/kademar/utils/instalador-nano/scripts/bootinst.sh.orig --rename /usr/share/kademar/utils/instalador-nano/scripts/bootinst.sh


                rm -f /usr/share/kademar/utils/kademarcenter/html/equip_ca.html
                dpkg-divert --package kademar-heliox --remove --divert /usr/share/kademar/utils/kademarcenter/html/equip_ca.html.orig --rename /usr/share/kademar/utils/kademarcenter/html/equip_ca.html

                rm -f /usr/share/kademar/utils/kademarcenter/html/equip_es.html
                dpkg-divert --package kademar-heliox --remove --divert /usr/share/kademar/utils/kademarcenter/html/equip_es.html.orig --rename /usr/share/kademar/utils/kademarcenter/html/equip_es.html

                rm -f /usr/share/kademar/utils/kademarcenter/html/equip_en.html
                dpkg-divert --package kademar-heliox --remove --divert /usr/share/kademar/utils/kademarcenter/html/equip_en.html.orig --rename /usr/share/kademar/utils/kademarcenter/html/equip_en.html

                rm -f /usr/share/kademar/utils/kademarcenter/ui_kademarstart.py
                dpkg-divert --package kademar-heliox --remove --divert /usr/share/kademar/utils/kademarcenter/ui_kademarstart.py.orig --rename /usr/share/kademar/utils/kademarcenter/ui_kademarstart.py

                rm -f /usr/share/kademar/utils/kademarcenter/kademarcenter.py
                dpkg-divert --package kademar-heliox --remove --divert /usr/share/kademar/utils/kademarcenter/kademarcenter.py.orig --rename /usr/share/kademar/utils/kademarcenter/kademarcenter.py

                rm -f /usr/share/wallpapers/kademar.png
                dpkg-divert --package kademar-heliox --remove --divert /usr/share/wallpapers/kademar.png.orig --rename /usr/share/wallpapers/kademar.png

                rm -f /usr/share/wallpapers/kademar-panoramic.png
                dpkg-divert --package kademar-heliox --remove --divert /usr/share/wallpapers/kademar-panoramic.png.orig --rename /usr/share/wallpapers/kademar-panoramic.png

                rm -f /usr/share/wallpapers/kademar-black.png
                dpkg-divert --package kademar-heliox --remove --divert /usr/share/wallpapers/kademar-black.png.orig --rename /usr/share/wallpapers/kademar-black.png

                rm -f /usr/share/kademar/utils/kademarcenter/img/banda.png
                dpkg-divert --package kademar-heliox --remove --divert /usr/share/kademar/utils/kademarcenter/img/banda.png.orig --rename /usr/share/kademar/utils/kademarcenter/img/banda.png

                dpkg-divert --package kademar-heliox --remove --divert /usr/share/kademar/kademarcenter.desktop --rename /usr/share/applications/kademarcenter.desktop

        fi

    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# dh_installdeb will replace this with shell code automatically
# generated by other debhelper scripts.

#DEBHELPER#

exit 0


