Document: kademarcenter
Title: Debian kademarcenter Manual
Author: <insert document author here>
Abstract: This manual describes what kademarcenter is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/kademarcenter/kademarcenter.sgml.gz

Format: postscript
Files: /usr/share/doc/kademarcenter/kademarcenter.ps.gz

Format: text
Files: /usr/share/doc/kademarcenter/kademarcenter.text.gz

Format: HTML
Index: /usr/share/doc/kademarcenter/html/index.html
Files: /usr/share/doc/kademarcenter/html/*.html


