#!/bin/bash

#Main part
main_title="fnux"
main_description="\n\n\n\n\n               Benvingut a l'instal·lador de kademar Linux\n\n\n\n\n\n\n\n                 Desitja continuar la instal·lació?"
main_partition="\n\n\nPer instal·lar kademar Linux es necessita tenir el disc ja particionat.\n\n\n Es necessiten al menys dues particions:\n   - Arrel: On kademar serà instal·lada.\n   - Swap: Espai per al manteniment del sistema.\n\nSi ho desitja, pot tenir els seus documents d'usuari en una partició separada de la partició de sistema.\n\n\n\n
  Vol continuar amb el següent pas?
\n\n Si sel·lecciona NO, anirà al particionador de disc."
main_partition_disk="\nSel·lecciona el disc dur que vulgui particionar"
# main_part="\n\n\n\n Ara es recopilaran les dades necesàries per continuar. Pot trigar una estona, tingui paciència, si us plau."


#Partition part
fs_detector_select_disk_partition="Sel·lecciona el disc dur que vulguis particionar"
fs_detector_select_disk="Sel·lecciona el disc dur on instal·lar la kademar"
fs_detector_selected_disk="Has sel·leccionat el disk:"
fs_detector_select_root_partition="Sel·lecciona la partició ARREL on instal·lar la kademar"
fs_detector_select_swap_partition="Sel·lecciona la partició SWAP on instal·lar la kademar"

fs_detector_ask_home_partition="\n\n\n\n\n\n\n\n\n\nDesitja tenir els documents d'usuari en una partició separada a la partició ARREL del sistema?"
fs_detector_select_home_partition="Sel·lecciona la partició USUARI on instal·lar la kademar"

fs_detailed_format="\n\n\n\n\n\n\nVol configurar en detall el sistema de fitxers amb el que formatar les particions?"

fs_detailed_root_format="Sel·leccioni el sistema de fitxers a utilitzar per formatar la partició ARREL"
fs_detailed_home_format="Sel·leccioni el sistema de fitxers a utilitzar per formatar la partició USUARI"

fs_format_noformat="No Formatis"

fs_partition_no_more_left="\n\n\n\n    No queda cap partició sense sel·leccionar. L'opció de tenir els documents separats, queda deshabilitada"


#License part
license_gpl="     kademar Linux és software lliure i això no canviarà.\n\nAmb motiu de millorar l'experiència de l'usuari amb kademar, l'Equip kademar ha decidit incloure software no lliure al 100%. El resum d'aquestes llicències no lliures incloses en kademar seria:\n  - No pot modificar aquests programes.\n  - Pot redistribuir-los sense cap modificació de les fonts.\n\nPot llegir més sobre aquestes llicències no lliures incloses a kademar, a la nostra pàgina web de kademar.\nSi no accepta aquestes llicències, tot el software no lliure com : suport DivX , suport MP3 ,controladors gràfics de nVidia , firmwares de dispositius, flash, java, etc. seran completament esborrats del seu sistema convertint kademar Linux en una versió de linux 100% lliure i de lliure distribució. \n\n\nAccepta els termes de les llicències NO lliures incloses en kademar per tal de maximitzar l'experiència d'usuari?"

#System configuration
system_lang_select="\n\n\n\n\nSel·lecciona en quin idioma per defecte del seu sistema. Pot canviar-ho més tard des del CADI."
system_pc_name="\n\n\n\n\nAra ha de configurar el nom de Pc. Serà utilitzat en la identificació de xarxa.\n\nNOTA: No entri caràcters especials com accents, ce trencada, enya, o espais."

#Root Config
system_root_passwd1="Ara definirem la contrasenya de l'usuari Administrador.\n\nL'usuari Administrador es l'únic amb privilegis i autorizació per a realitzar qualsevol tasca al sistema, incloent esborrar tots els arxius.\n\nIntrodueixi la contrasenya confirmar-la i Recordi-la!\n\n\n(Anoti aquesta contrassenya en un lloc segur)\n\n La contrasenya no pot ser buida\n\nNOTA: No es mostrarà cap caràcter introduït."
system_root_passwd2="Torni a entrar la contrassenya de l'usuari Administrador, per tal de confirmar-la.\n\n\n          (Anoti aquesta contrassenya en un lloc segur)\n\nNOTA: No es mostrarà cap caràcter introduït."

#User config
user_config_name="\n\n\n\nAra ha de definir un usuari perquè sigui possible utilitzar el sistema.\n\n
Introdueixi el seu nom"

user_config_login="\n\n\n\nAra s'ha de definir el nom d'usuari per crear el compte, que pot ser el seu mateix nom.\n\nNOTA: No entri caràcters especials com accents, ce trencada, enya, o espais."

user_config_passwd1="\n\n\n\nPer a major seguretat s'ha de definir una contrassenya per al usuari. \n\n La contrasenya no pot ser buida\n\nNOTA: No es mostrarà cap caràcter introduït."
user_config_passwd2="\n\n\n\nTorni a entrar la contrassenya de l'usuari, per tal de confirmar-la.\n\n\n          (Anoti aquesta contrassenya en un lloc segur)\n\nNOTA: No es mostrarà cap caràcter introduït."


user_config_autologin="\n\n\nCom a comoditat per l'usuari, es pot desactivar l'autenticació amb contrassenya cada cop que engega l'ordinador. No és una opció segura per la privacitat de les dades.\n\n Vol DESACTIVAR la solicitut de la contrassenya a l'inici?"


#Installation begins

begins_installation="\n\n\n\n          Ara començarà el procés d'instal·lació.\n\n\n\n Primerament es recolliran dades de l'ordinador. Pot trigar una estona, sigui pacient, si us plau."
begins_installation_without_format="\n\n\n\nNOTA: Totes les dades es conservaran"
begins_installation_with_format="\n\n\n\nNOTA: Totes les dades de les particions %PARTITIONS% s'esborraran!"

be_sure_umounted="\n\n\n\n    Ha de tancar totes les aplicacions obertes amb accés a disc, per tal de que l'instal·lació sigui exitosa"

copying="\n\n\n\n          Copiant els fitxer..."

configuring="\n\n\n\n          Configurant el sistema..."

finishing="\n\n\n\n          Tencant els processos restants..."

finished="kademar Linux s'ha instal·lat en el seu PC\n\n     Ara ja pot tancar l'instal·lador i continuar utilitzant kademar en mode Live, o pot reiniciar el seu ordinador i començar desde el sistema instal·lat en disc\n\n     Recordi-se'n de visitar la nostra pàgina web si té cap problema.\n\n\n\n          Gracies per escollir kademar Linux\n\n     Vol Reiniciar el ordinador ara?"