# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/kademarcenter.ui'
#
# Created: Sat Dec 26 04:03:22 2009
#      by: PyQt4 UI code generator 4.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Form_kademarcenter(object):
    def setupUi(self, Form_kademarcenter):
        Form_kademarcenter.setObjectName("Form_kademarcenter")
        Form_kademarcenter.resize(500,400)
        Form_kademarcenter.setMinimumSize(QtCore.QSize(500,400))
        Form_kademarcenter.setMaximumSize(QtCore.QSize(500,400))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../../usr/share/kademar/utils/kademarcenter/img/kademar.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        Form_kademarcenter.setWindowIcon(icon)
        self.label_4 = QtGui.QLabel(Form_kademarcenter)
        self.label_4.setGeometry(QtCore.QRect(0,0,500,400))
        self.label_4.setPixmap(QtGui.QPixmap("../../../../../../usr/share/kademar/utils/kademarcenter/img/bg/kademarcenter.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label = QtGui.QLabel(Form_kademarcenter)
        self.label.setGeometry(QtCore.QRect(13,6,60,60))
        self.label.setPixmap(QtGui.QPixmap("../../../../../../usr/share/kademar/utils/kademarcenter/img/kademar.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.frame = QtGui.QFrame(Form_kademarcenter)
        self.frame.setGeometry(QtCore.QRect(129,39,351,331))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.l_ver = QtGui.QLabel(self.frame)
        self.l_ver.setGeometry(QtCore.QRect(130,63,201,16))
        self.l_ver.setObjectName("l_ver")
        self.l_tipu = QtGui.QLabel(self.frame)
        self.l_tipu.setGeometry(QtCore.QRect(130,46,201,16))
        self.l_tipu.setObjectName("l_tipu")
        self.l_kdm = QtGui.QLabel(self.frame)
        self.l_kdm.setGeometry(QtCore.QRect(130,30,201,16))
        self.l_kdm.setObjectName("l_kdm")
        self.l_ram = QtGui.QLabel(self.frame)
        self.l_ram.setGeometry(QtCore.QRect(70,226,261,16))
        self.l_ram.setObjectName("l_ram")
        self.label_6 = QtGui.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(10,10,109,85))
        self.label_6.setPixmap(QtGui.QPixmap("../../../../../../usr/share/kademar/utils/kademarcenter/img/pc.png"))
        self.label_6.setObjectName("label_6")
        self.l_kern = QtGui.QLabel(self.frame)
        self.l_kern.setGeometry(QtCore.QRect(130,80,201,16))
        self.l_kern.setTextFormat(QtCore.Qt.PlainText)
        self.l_kern.setObjectName("l_kern")
        self.label_5 = QtGui.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(10,216,51,48))
        self.label_5.setPixmap(QtGui.QPixmap("../../../../../../usr/share/kademar/utils/kademarcenter/img/mem.png"))
        self.label_5.setObjectName("label_5")
        self.l_cpuinfo = QtGui.QLabel(self.frame)
        self.l_cpuinfo.setGeometry(QtCore.QRect(70,160,261,31))
        self.l_cpuinfo.setObjectName("l_cpuinfo")
        self.l_cpu = QtGui.QLabel(self.frame)
        self.l_cpu.setGeometry(QtCore.QRect(70,140,261,16))
        self.l_cpu.setObjectName("l_cpu")
        self.l_host = QtGui.QLabel(self.frame)
        self.l_host.setGeometry(QtCore.QRect(130,97,201,16))
        self.l_host.setObjectName("l_host")
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10,140,51,48))
        self.label_2.setPixmap(QtGui.QPixmap("../../../../../../usr/share/kademar/utils/kademarcenter/img/cpu.png"))
        self.label_2.setObjectName("label_2")
        self.label_7 = QtGui.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(120,10,131,16))
        self.label_7.setObjectName("label_7")
        self.b_settings = QtGui.QPushButton(self.frame)
        self.b_settings.setGeometry(QtCore.QRect(100,270,181,51))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/kademarcenter/img/kcontrol.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.b_settings.setIcon(icon)
        self.b_settings.setIconSize(QtCore.QSize(32,32))
        self.b_settings.setObjectName("b_settings")

        self.retranslateUi(Form_kademarcenter)
        QtCore.QMetaObject.connectSlotsByName(Form_kademarcenter)

    def retranslateUi(self, Form_kademarcenter):
        Form_kademarcenter.setWindowTitle(QtGui.QApplication.translate("Form_kademarcenter", "kademarcenter", None, QtGui.QApplication.UnicodeUTF8))
        self.l_ver.setText(QtGui.QApplication.translate("Form_kademarcenter", "versio", None, QtGui.QApplication.UnicodeUTF8))
        self.l_tipu.setText(QtGui.QApplication.translate("Form_kademarcenter", "tipus", None, QtGui.QApplication.UnicodeUTF8))
        self.l_kdm.setText(QtGui.QApplication.translate("Form_kademarcenter", "kdm", None, QtGui.QApplication.UnicodeUTF8))
        self.l_ram.setText(QtGui.QApplication.translate("Form_kademarcenter", "RAM", None, QtGui.QApplication.UnicodeUTF8))
        self.l_kern.setText(QtGui.QApplication.translate("Form_kademarcenter", "kernel", None, QtGui.QApplication.UnicodeUTF8))
        self.l_cpuinfo.setText(QtGui.QApplication.translate("Form_kademarcenter", "CPU info", None, QtGui.QApplication.UnicodeUTF8))
        self.l_cpu.setText(QtGui.QApplication.translate("Form_kademarcenter", "CPU", None, QtGui.QApplication.UnicodeUTF8))
        self.l_host.setText(QtGui.QApplication.translate("Form_kademarcenter", "hostname", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form_kademarcenter", "System:", None, QtGui.QApplication.UnicodeUTF8))
        self.b_settings.setText(QtGui.QApplication.translate("Form_kademarcenter", "Settings", None, QtGui.QApplication.UnicodeUTF8))

