# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/settings.ui'
#
# Created: Sat Dec 26 04:03:23 2009
#      by: PyQt4 UI code generator 4.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Form_settings(object):
    def setupUi(self, Form_settings):
        Form_settings.setObjectName("Form_settings")
        Form_settings.resize(600,500)
        Form_settings.setMinimumSize(QtCore.QSize(600,500))
        Form_settings.setMaximumSize(QtCore.QSize(500,400))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/kademarcenter/img/kademar.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        Form_settings.setWindowIcon(icon)
        self.l_fons = QtGui.QLabel(Form_settings)
        self.l_fons.setGeometry(QtCore.QRect(0,0,600,500))
        self.l_fons.setPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/kademarcenter/img/bg/kademarcenter.png"))
        self.l_fons.setScaledContents(True)
        self.l_fons.setObjectName("l_fons")
        self.pages = QtGui.QStackedWidget(Form_settings)
        self.pages.setGeometry(QtCore.QRect(150,50,401,401))
        self.pages.setObjectName("pages")
        self.p_general = QtGui.QWidget()
        self.p_general.setObjectName("p_general")
        self.label_3 = QtGui.QLabel(self.p_general)
        self.label_3.setGeometry(QtCore.QRect(30,0,331,20))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.cb_hotplugactions = QtGui.QCheckBox(self.p_general)
        self.cb_hotplugactions.setGeometry(QtCore.QRect(30,100,351,21))
        self.cb_hotplugactions.setObjectName("cb_hotplugactions")
        self.cb_balloon = QtGui.QCheckBox(self.p_general)
        self.cb_balloon.setGeometry(QtCore.QRect(30,180,351,21))
        self.cb_balloon.setObjectName("cb_balloon")
        self.cb_sound = QtGui.QCheckBox(self.p_general)
        self.cb_sound.setGeometry(QtCore.QRect(30,260,361,21))
        self.cb_sound.setObjectName("cb_sound")
        self.pages.addWidget(self.p_general)
        self.p_updates = QtGui.QWidget()
        self.p_updates.setObjectName("p_updates")
        self.l_titol = QtGui.QLabel(self.p_updates)
        self.l_titol.setGeometry(QtCore.QRect(100,30,131,16))
        self.l_titol.setObjectName("l_titol")
        self.sb_update_hours = QtGui.QSpinBox(self.p_updates)
        self.sb_update_hours.setGeometry(QtCore.QRect(80,180,46,22))
        self.sb_update_hours.setMinimum(1)
        self.sb_update_hours.setObjectName("sb_update_hours")
        self.l_actualitzacio = QtGui.QLabel(self.p_updates)
        self.l_actualitzacio.setGeometry(QtCore.QRect(140,180,251,16))
        self.l_actualitzacio.setObjectName("l_actualitzacio")
        self.rb_no_update = QtGui.QRadioButton(self.p_updates)
        self.rb_no_update.setGeometry(QtCore.QRect(20,260,111,20))
        self.rb_no_update.setObjectName("rb_no_update")
        self.rb_autoupdate = QtGui.QRadioButton(self.p_updates)
        self.rb_autoupdate.setGeometry(QtCore.QRect(20,100,371,20))
        self.rb_autoupdate.setObjectName("rb_autoupdate")
        self.rb_only_warn = QtGui.QRadioButton(self.p_updates)
        self.rb_only_warn.setGeometry(QtCore.QRect(20,140,181,20))
        self.rb_only_warn.setObjectName("rb_only_warn")
        self.pages.addWidget(self.p_updates)
        self.p_usb = QtGui.QWidget()
        self.p_usb.setObjectName("p_usb")
        self.label_5 = QtGui.QLabel(self.p_usb)
        self.label_5.setGeometry(QtCore.QRect(110,30,131,16))
        self.label_5.setObjectName("label_5")
        self.label_7 = QtGui.QLabel(self.p_usb)
        self.label_7.setGeometry(QtCore.QRect(40,100,291,16))
        self.label_7.setObjectName("label_7")
        self.pages.addWidget(self.p_usb)
        self.p_diskcleanup = QtGui.QWidget()
        self.p_diskcleanup.setObjectName("p_diskcleanup")
        self.label_8 = QtGui.QLabel(self.p_diskcleanup)
        self.label_8.setGeometry(QtCore.QRect(50,80,291,16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtGui.QLabel(self.p_diskcleanup)
        self.label_9.setGeometry(QtCore.QRect(40,40,351,16))
        self.label_9.setObjectName("label_9")
        self.radioButton_4 = QtGui.QRadioButton(self.p_diskcleanup)
        self.radioButton_4.setGeometry(QtCore.QRect(50,110,231,20))
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtGui.QRadioButton(self.p_diskcleanup)
        self.radioButton_5.setGeometry(QtCore.QRect(50,150,241,20))
        self.radioButton_5.setObjectName("radioButton_5")
        self.tableWidget = QtGui.QTableWidget(self.p_diskcleanup)
        self.tableWidget.setGeometry(QtCore.QRect(50,180,291,171))
        self.tableWidget.setObjectName("tableWidget")
        self.pages.addWidget(self.p_diskcleanup)
        self.l_logo = QtGui.QLabel(Form_settings)
        self.l_logo.setGeometry(QtCore.QRect(10,10,60,60))
        self.l_logo.setPixmap(QtGui.QPixmap("../../../../../usr/share/kademar/utils/kademarcenter/img/kademar.png"))
        self.l_logo.setScaledContents(True)
        self.l_logo.setObjectName("l_logo")
        self.b_general = QtGui.QPushButton(Form_settings)
        self.b_general.setGeometry(QtCore.QRect(10,150,111,24))
        self.b_general.setObjectName("b_general")
        self.b_updates = QtGui.QPushButton(Form_settings)
        self.b_updates.setGeometry(QtCore.QRect(10,190,111,24))
        self.b_updates.setObjectName("b_updates")
        self.b_diskcleanup = QtGui.QPushButton(Form_settings)
        self.b_diskcleanup.setGeometry(QtCore.QRect(10,270,111,24))
        self.b_diskcleanup.setObjectName("b_diskcleanup")
        self.b_usb = QtGui.QPushButton(Form_settings)
        self.b_usb.setGeometry(QtCore.QRect(10,230,111,24))
        self.b_usb.setObjectName("b_usb")

        self.retranslateUi(Form_settings)
        self.pages.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form_settings)

    def retranslateUi(self, Form_settings):
        Form_settings.setWindowTitle(QtGui.QApplication.translate("Form_settings", "kademarcenter Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form_settings", "Settings kademarcenter", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_hotplugactions.setText(QtGui.QApplication.translate("Form_settings", "Open Action Panel on a device/media plug", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_balloon.setText(QtGui.QApplication.translate("Form_settings", "Use a balloon to warn for a pluged device", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_sound.setText(QtGui.QApplication.translate("Form_settings", "Use a sound warn for a pluged device", None, QtGui.QApplication.UnicodeUTF8))
        self.l_titol.setText(QtGui.QApplication.translate("Form_settings", "Settings kademarcenter", None, QtGui.QApplication.UnicodeUTF8))
        self.l_actualitzacio.setText(QtGui.QApplication.translate("Form_settings", "Temps d\'actualització del sistema (en Hores)", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_no_update.setText(QtGui.QApplication.translate("Form_settings", "No Actualitzar", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_autoupdate.setText(QtGui.QApplication.translate("Form_settings", "Actualitzar el Sistema Automàticament (Recomanat)", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_only_warn.setText(QtGui.QApplication.translate("Form_settings", "Solament avisar dels nous paquets", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form_settings", "Settings kademarcenter", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form_settings", "Preferència de les aplicacions usades automàticament", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Form_settings", "Preferències de cercar espai de disc lliure", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Form_settings", "Preferència de les aplicacions usades automàticament", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_4.setText(QtGui.QApplication.translate("Form_settings", "Cercar i avisar", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_5.setText(QtGui.QApplication.translate("Form_settings", "Cercar i Esborrar automàticament les carpetes:", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.clear()
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        headerItem = QtGui.QTableWidgetItem()
        headerItem.setText(QtGui.QApplication.translate("Form_settings", "Esborrar?", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.setHorizontalHeaderItem(0,headerItem)
        headerItem1 = QtGui.QTableWidgetItem()
        headerItem1.setText(QtGui.QApplication.translate("Form_settings", "Directori", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.setHorizontalHeaderItem(1,headerItem1)
        self.b_general.setText(QtGui.QApplication.translate("Form_settings", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.b_updates.setText(QtGui.QApplication.translate("Form_settings", "Updates", None, QtGui.QApplication.UnicodeUTF8))
        self.b_diskcleanup.setText(QtGui.QApplication.translate("Form_settings", "Disc Lliure", None, QtGui.QApplication.UnicodeUTF8))
        self.b_usb.setText(QtGui.QApplication.translate("Form_settings", "USB", None, QtGui.QApplication.UnicodeUTF8))

