#!/bin/bash
#Script per posar autologin en kdm o desactivarlo

AUTOLOGIN="$1"
created_user="$2"
DESTI="$3"

[ -z "$3" ] && echo "ÑAC" && exit 1

#Activem el autologin en el KDM si es demana
if [ "$AUTOLOGIN" = "autologin_si" ]; then
	fitxer_a_modificar=/etc/gdm/gdm.conf
# 	find0=`cat "$DESTI/$fitxer_a_modificar" | grep "AutoLogin="`
# 	find1=`cat "$DESTI/$fitxer_a_modificar" | grep "AutoLoginEnable="`
# 	[ -z "$find0" ] && find0="AquEStaKAdeNaNOLAtrobARAsMAI"
# 	[ -z "$find1" ] && find1="AquEStaKAdeNaNOLAtrobARAsMAI"
# 	
# 	cat "$DESTI/$fitxer_a_modificar"  | sed s/"$find0"/"AutoLoginUser=$created_user"/g | sed s:"$find1":"AutoLoginEnable=true":g > "$DESTI/$fitxer_a_modificar.tmp"
# 	rm "$DESTI/$fitxer_a_modificar"
# 	mv "$DESTI/$fitxer_a_modificar.tmp" "$DESTI/$fitxer_a_modificar"
echo "[daemon]
AutomaticLoginEnable=true
AutomaticLogin=$created_user" >> "$DESTI/$fitxer_a_modificar"

fi

#Desactivem el autologin en el KDM si es demana
# if [ "$AUTOLOGIN" = "autologin_no" ]; then
# 	fitxer_a_modificar=/etc/gdm/gdm.conf
# 	find0=`cat "$DESTI/$fitxer_a_modificar" | grep "AutoLogin="`
# 	find1=`cat "$DESTI/$fitxer_a_modificar" | grep "AutoLoginEnable="`
# 	[ -z "$find0" ] && find0="AquEStaKAdeNaNOLAtrobARAsMAI"
# 	[ -z "$find1" ] && find1="AquEStaKAdeNaNOLAtrobARAsMAI"
# 	
# 	cat "$DESTI/$fitxer_a_modificar"  | sed s/"$find0"/'#AutoLogin='/g | sed s:"$find1":"AutoLoginEnable=false":g > "$DESTI/$fitxer_a_modificar.tmp"
# 	rm -f"$DESTI/$fitxer_a_modificar"
# 	mv "$DESTI/$fitxer_a_modificar.tmp" "$DESTI/$fitxer_a_modificar"
# fi