Document: kademar-leo
Title: Debian kademar-leo Manual
Author: <insert document author here>
Abstract: This manual describes what kademar-leo is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/kademar-leo/kademar-leo.sgml.gz

Format: postscript
Files: /usr/share/doc/kademar-leo/kademar-leo.ps.gz

Format: text
Files: /usr/share/doc/kademar-leo/kademar-leo.text.gz

Format: HTML
Index: /usr/share/doc/kademar-leo/html/index.html
Files: /usr/share/doc/kademar-leo/html/*.html

  
