#Alias Zone
alias which="type -path"
alias where="type -all"
alias ll="ls -l --color=auto"
alias l="ls -a --color=auto"
alias ..="cd .."
alias rm="rm -i"
alias mv="mv -i"
alias cp="cp -i"
alias la="ls -la --color=auto"
alias ls="ls --color=auto"
alias cd..="cd .."
alias grep="grep --colour=auto"
# alias mplayer="mplayer -zoom"
# alias gmplayer="gmplayer -zoom" 
