# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/instalador.ui'
#
# Created: Mon Apr  9 13:47:46 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_FormInstall(object):
    def setupUi(self, FormInstall):
        FormInstall.setObjectName(_fromUtf8("FormInstall"))
        FormInstall.resize(800, 600)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(FormInstall.sizePolicy().hasHeightForWidth())
        FormInstall.setSizePolicy(sizePolicy)
        FormInstall.setMinimumSize(QtCore.QSize(800, 600))
        FormInstall.setMaximumSize(QtCore.QSize(640, 480))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../usr/share/kademar/icons/kpackage.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        FormInstall.setWindowIcon(icon)
        self.fons = QtGui.QLabel(FormInstall)
        self.fons.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.fons.setText(_fromUtf8(""))
        self.fons.setPixmap(QtGui.QPixmap(_fromUtf8("../../../../../usr/share/kademar/utils/instalador/img/bg/instalador.png")))
        self.fons.setScaledContents(True)
        self.fons.setObjectName(_fromUtf8("fons"))
        self.w_process = QtGui.QWidget(FormInstall)
        self.w_process.setGeometry(QtCore.QRect(0, 0, 181, 421))
        self.w_process.setObjectName(_fromUtf8("w_process"))
        self.l_titol = QtGui.QLabel(self.w_process)
        self.l_titol.setGeometry(QtCore.QRect(10, 10, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.l_titol.setFont(font)
        self.l_titol.setObjectName(_fromUtf8("l_titol"))
        self.led_disc = QtGui.QLabel(self.w_process)
        self.led_disc.setGeometry(QtCore.QRect(10, 60, 28, 28))
        self.led_disc.setText(_fromUtf8(""))
        self.led_disc.setPixmap(QtGui.QPixmap(_fromUtf8("../../../../../usr/share/kademar/utils/instalador/img/vermell_p.png")))
        self.led_disc.setObjectName(_fromUtf8("led_disc"))
        self.l_disc = QtGui.QLabel(self.w_process)
        self.l_disc.setGeometry(QtCore.QRect(50, 50, 111, 51))
        self.l_disc.setWordWrap(True)
        self.l_disc.setObjectName(_fromUtf8("l_disc"))
        self.led_copia = QtGui.QLabel(self.w_process)
        self.led_copia.setGeometry(QtCore.QRect(10, 107, 28, 28))
        self.led_copia.setText(_fromUtf8(""))
        self.led_copia.setPixmap(QtGui.QPixmap(_fromUtf8("../../../../../usr/share/kademar/utils/instalador/img/vermell_p.png")))
        self.led_copia.setObjectName(_fromUtf8("led_copia"))
        self.l_copia = QtGui.QLabel(self.w_process)
        self.l_copia.setGeometry(QtCore.QRect(50, 106, 111, 31))
        self.l_copia.setWordWrap(True)
        self.l_copia.setObjectName(_fromUtf8("l_copia"))
        self.led_license = QtGui.QLabel(self.w_process)
        self.led_license.setGeometry(QtCore.QRect(10, 154, 28, 28))
        self.led_license.setText(_fromUtf8(""))
        self.led_license.setPixmap(QtGui.QPixmap(_fromUtf8("../../../../../usr/share/kademar/utils/instalador/img/vermell_p.png")))
        self.led_license.setObjectName(_fromUtf8("led_license"))
        self.l_sistema = QtGui.QLabel(self.w_process)
        self.l_sistema.setGeometry(QtCore.QRect(50, 154, 111, 31))
        self.l_sistema.setWordWrap(True)
        self.l_sistema.setObjectName(_fromUtf8("l_sistema"))
        self.led_user = QtGui.QLabel(self.w_process)
        self.led_user.setGeometry(QtCore.QRect(10, 296, 28, 28))
        self.led_user.setText(_fromUtf8(""))
        self.led_user.setPixmap(QtGui.QPixmap(_fromUtf8("../../../../../usr/share/kademar/utils/instalador/img/vermell_p.png")))
        self.led_user.setObjectName(_fromUtf8("led_user"))
        self.l_user = QtGui.QLabel(self.w_process)
        self.l_user.setGeometry(QtCore.QRect(50, 296, 111, 31))
        self.l_user.setWordWrap(True)
        self.l_user.setObjectName(_fromUtf8("l_user"))
        self.led_mbr = QtGui.QLabel(self.w_process)
        self.led_mbr.setGeometry(QtCore.QRect(10, 343, 28, 28))
        self.led_mbr.setText(_fromUtf8(""))
        self.led_mbr.setPixmap(QtGui.QPixmap(_fromUtf8("../../../../../usr/share/kademar/utils/instalador/img/vermell_p.png")))
        self.led_mbr.setObjectName(_fromUtf8("led_mbr"))
        self.l_mbr = QtGui.QLabel(self.w_process)
        self.l_mbr.setGeometry(QtCore.QRect(50, 333, 111, 51))
        self.l_mbr.setWordWrap(True)
        self.l_mbr.setObjectName(_fromUtf8("l_mbr"))
        self.led_passwd = QtGui.QLabel(self.w_process)
        self.led_passwd.setGeometry(QtCore.QRect(10, 248, 28, 28))
        self.led_passwd.setText(_fromUtf8(""))
        self.led_passwd.setPixmap(QtGui.QPixmap(_fromUtf8("../../../../../usr/share/kademar/utils/instalador/img/vermell_p.png")))
        self.led_passwd.setObjectName(_fromUtf8("led_passwd"))
        self.l_passwd = QtGui.QLabel(self.w_process)
        self.l_passwd.setGeometry(QtCore.QRect(50, 228, 111, 71))
        self.l_passwd.setWordWrap(True)
        self.l_passwd.setObjectName(_fromUtf8("l_passwd"))
        self.led_sistema = QtGui.QLabel(self.w_process)
        self.led_sistema.setGeometry(QtCore.QRect(10, 201, 28, 31))
        self.led_sistema.setText(_fromUtf8(""))
        self.led_sistema.setPixmap(QtGui.QPixmap(_fromUtf8("../../../../../usr/share/kademar/utils/instalador/img/vermell_p.png")))
        self.led_sistema.setObjectName(_fromUtf8("led_sistema"))
        self.l_license = QtGui.QLabel(self.w_process)
        self.l_license.setGeometry(QtCore.QRect(50, 201, 111, 31))
        self.l_license.setWordWrap(True)
        self.l_license.setObjectName(_fromUtf8("l_license"))
        self.w_logo = QtGui.QWidget(FormInstall)
        self.w_logo.setGeometry(QtCore.QRect(0, 400, 181, 201))
        palette = QtGui.QPalette()
        self.w_logo.setPalette(palette)
        self.w_logo.setAutoFillBackground(False)
        self.w_logo.setObjectName(_fromUtf8("w_logo"))
        self.logo_kademar = QtGui.QLabel(self.w_logo)
        self.logo_kademar.setGeometry(QtCore.QRect(30, 92, 90, 90))
        self.logo_kademar.setText(_fromUtf8(""))
        self.logo_kademar.setPixmap(QtGui.QPixmap(_fromUtf8("../../../../../usr/share/kademar/utils/instalador/img/kademar.png")))
        self.logo_kademar.setObjectName(_fromUtf8("logo_kademar"))
        self.progressBar = QtGui.QProgressBar(self.w_logo)
        self.progressBar.setGeometry(QtCore.QRect(10, 38, 131, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignLeading)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.l_finished = QtGui.QLabel(self.w_logo)
        self.l_finished.setGeometry(QtCore.QRect(10, 41, 130, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.l_finished.setFont(font)
        self.l_finished.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.l_finished.setWordWrap(True)
        self.l_finished.setObjectName(_fromUtf8("l_finished"))
        self.boto_ajuda = QtGui.QPushButton(self.w_logo)
        self.boto_ajuda.setGeometry(QtCore.QRect(9, 8, 131, 26))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../usr/share/kademar/utils/instalador/img/help.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boto_ajuda.setIcon(icon1)
        self.boto_ajuda.setObjectName(_fromUtf8("boto_ajuda"))
        self.w_botons = QtGui.QWidget(FormInstall)
        self.w_botons.setGeometry(QtCore.QRect(180, 540, 621, 61))
        self.w_botons.setObjectName(_fromUtf8("w_botons"))
        self.boto_back = QtGui.QPushButton(self.w_botons)
        self.boto_back.setGeometry(QtCore.QRect(110, 10, 111, 31))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../usr/share/kademar/utils/instalador/img/back.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boto_back.setIcon(icon2)
        self.boto_back.setIconSize(QtCore.QSize(20, 20))
        self.boto_back.setObjectName(_fromUtf8("boto_back"))
        self.boto_next = QtGui.QPushButton(self.w_botons)
        self.boto_next.setGeometry(QtCore.QRect(400, 10, 111, 31))
        self.boto_next.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../usr/share/kademar/utils/instalador/img/next.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boto_next.setIcon(icon3)
        self.boto_next.setIconSize(QtCore.QSize(20, 20))
        self.boto_next.setDefault(True)
        self.boto_next.setObjectName(_fromUtf8("boto_next"))
        self.boto_exit = QtGui.QPushButton(self.w_botons)
        self.boto_exit.setGeometry(QtCore.QRect(110, 10, 111, 31))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../usr/share/kademar/utils/instalador/img/exit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boto_exit.setIcon(icon4)
        self.boto_exit.setIconSize(QtCore.QSize(20, 20))
        self.boto_exit.setObjectName(_fromUtf8("boto_exit"))
        self.pages = QtGui.QStackedWidget(FormInstall)
        self.pages.setGeometry(QtCore.QRect(180, 0, 621, 541))
        self.pages.setObjectName(_fromUtf8("pages"))
        self.p_principal = QtGui.QWidget()
        self.p_principal.setObjectName(_fromUtf8("p_principal"))
        self.label = QtGui.QLabel(self.p_principal)
        self.label.setGeometry(QtCore.QRect(30, 60, 561, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label.setWordWrap(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.boto_ajuda2 = QtGui.QPushButton(self.p_principal)
        self.boto_ajuda2.setGeometry(QtCore.QRect(470, 400, 61, 51))
        self.boto_ajuda2.setText(_fromUtf8(""))
        self.boto_ajuda2.setIcon(icon1)
        self.boto_ajuda2.setIconSize(QtCore.QSize(32, 32))
        self.boto_ajuda2.setObjectName(_fromUtf8("boto_ajuda2"))
        self.label_3 = QtGui.QLabel(self.p_principal)
        self.label_3.setGeometry(QtCore.QRect(70, 380, 391, 91))
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.line = QtGui.QFrame(self.p_principal)
        self.line.setGeometry(QtCore.QRect(90, 350, 401, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.label_17 = QtGui.QLabel(self.p_principal)
        self.label_17.setGeometry(QtCore.QRect(130, 188, 80, 80))
        self.label_17.setText(_fromUtf8(""))
        self.label_17.setPixmap(QtGui.QPixmap(_fromUtf8("../../../../../usr/share/kademar/utils/instalador/img/lyra.png")))
        self.label_17.setScaledContents(True)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_18 = QtGui.QLabel(self.p_principal)
        self.label_18.setGeometry(QtCore.QRect(250, 197, 52, 61))
        self.label_18.setText(_fromUtf8(""))
        self.label_18.setPixmap(QtGui.QPixmap(_fromUtf8("../../../../../usr/share/kademar/utils/instalador/img/arrow.png")))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_20 = QtGui.QLabel(self.p_principal)
        self.label_20.setGeometry(QtCore.QRect(340, 146, 150, 160))
        self.label_20.setText(_fromUtf8(""))
        self.label_20.setPixmap(QtGui.QPixmap(_fromUtf8("../../../../../usr/share/kademar/utils/instalador/img/computer.png")))
        self.label_20.setScaledContents(True)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.pages.addWidget(self.p_principal)
        self.p_information = QtGui.QWidget()
        self.p_information.setObjectName(_fromUtf8("p_information"))
        self.l_mng = QtGui.QLabel(self.p_information)
        self.l_mng.setGeometry(QtCore.QRect(290, 310, 21, 16))
        self.l_mng.setText(_fromUtf8(""))
        self.l_mng.setPixmap(QtGui.QPixmap(_fromUtf8("../../../../../usr/share/kademar/utils/instalador/img/wait.gif")))
        self.l_mng.setObjectName(_fromUtf8("l_mng"))
        self.label_9 = QtGui.QLabel(self.p_information)
        self.label_9.setGeometry(QtCore.QRect(80, 200, 441, 81))
        self.label_9.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.l_titol_9 = QtGui.QLabel(self.p_information)
        self.l_titol_9.setGeometry(QtCore.QRect(30, 70, 561, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.l_titol_9.setFont(font)
        self.l_titol_9.setAlignment(QtCore.Qt.AlignCenter)
        self.l_titol_9.setObjectName(_fromUtf8("l_titol_9"))
        self.label_7 = QtGui.QLabel(self.p_information)
        self.label_7.setGeometry(QtCore.QRect(530, 20, 64, 64))
        self.label_7.setText(_fromUtf8(""))
        self.label_7.setPixmap(QtGui.QPixmap(_fromUtf8("../../../../../usr/share/kademar/utils/instalador/img/pc.png")))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.pages.addWidget(self.p_information)
        self.p_disc = QtGui.QWidget()
        self.p_disc.setObjectName(_fromUtf8("p_disc"))
        self.label_8 = QtGui.QLabel(self.p_disc)
        self.label_8.setGeometry(QtCore.QRect(50, 100, 511, 151))
        self.label_8.setTextFormat(QtCore.Qt.RichText)
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.l_titol_2 = QtGui.QLabel(self.p_disc)
        self.l_titol_2.setGeometry(QtCore.QRect(30, 70, 561, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.l_titol_2.setFont(font)
        self.l_titol_2.setAlignment(QtCore.Qt.AlignCenter)
        self.l_titol_2.setObjectName(_fromUtf8("l_titol_2"))
        self.ch_tot_en_particio = QtGui.QCheckBox(self.p_disc)
        self.ch_tot_en_particio.setGeometry(QtCore.QRect(70, 270, 211, 21))
        self.ch_tot_en_particio.setChecked(True)
        self.ch_tot_en_particio.setObjectName(_fromUtf8("ch_tot_en_particio"))
        self.boto_particionar = QtGui.QPushButton(self.p_disc)
        self.boto_particionar.setGeometry(QtCore.QRect(440, 260, 141, 41))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../usr/share/kademar/utils/instalador/img/gparted.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boto_particionar.setIcon(icon5)
        self.boto_particionar.setIconSize(QtCore.QSize(32, 32))
        self.boto_particionar.setObjectName(_fromUtf8("boto_particionar"))
        self.ch_adv = QtGui.QCheckBox(self.p_disc)
        self.ch_adv.setGeometry(QtCore.QRect(310, 270, 121, 21))
        self.ch_adv.setObjectName(_fromUtf8("ch_adv"))
        self.cb_hd_arrel = QtGui.QComboBox(self.p_disc)
        self.cb_hd_arrel.setGeometry(QtCore.QRect(110, 363, 361, 22))
        self.cb_hd_arrel.setObjectName(_fromUtf8("cb_hd_arrel"))
        self.cb_hd_format_arrel = QtGui.QComboBox(self.p_disc)
        self.cb_hd_format_arrel.setGeometry(QtCore.QRect(480, 363, 101, 22))
        self.cb_hd_format_arrel.setObjectName(_fromUtf8("cb_hd_format_arrel"))
        self.cb_hd_format_arrel.addItem(_fromUtf8(""))
        self.cb_hd_format_arrel.addItem(_fromUtf8(""))
        self.cb_hd_format_arrel.addItem(_fromUtf8(""))
        self.cb_hd_format_arrel.addItem(_fromUtf8(""))
        self.cb_hd_format_arrel.addItem(_fromUtf8(""))
        self.cb_hd_swap = QtGui.QComboBox(self.p_disc)
        self.cb_hd_swap.setGeometry(QtCore.QRect(110, 403, 361, 22))
        self.cb_hd_swap.setObjectName(_fromUtf8("cb_hd_swap"))
        self.cb_hd_home = QtGui.QComboBox(self.p_disc)
        self.cb_hd_home.setGeometry(QtCore.QRect(110, 443, 361, 22))
        self.cb_hd_home.setObjectName(_fromUtf8("cb_hd_home"))
        self.cb_hd_format_swap = QtGui.QComboBox(self.p_disc)
        self.cb_hd_format_swap.setGeometry(QtCore.QRect(480, 403, 101, 22))
        self.cb_hd_format_swap.setObjectName(_fromUtf8("cb_hd_format_swap"))
        self.cb_hd_format_swap.addItem(_fromUtf8(""))
        self.cb_hd_format_home = QtGui.QComboBox(self.p_disc)
        self.cb_hd_format_home.setGeometry(QtCore.QRect(480, 443, 101, 22))
        self.cb_hd_format_home.setObjectName(_fromUtf8("cb_hd_format_home"))
        self.cb_hd_format_home.addItem(_fromUtf8(""))
        self.cb_hd_format_home.addItem(_fromUtf8(""))
        self.cb_hd_format_home.addItem(_fromUtf8(""))
        self.cb_hd_format_home.addItem(_fromUtf8(""))
        self.cb_hd_format_home.addItem(_fromUtf8(""))
        self.label_2 = QtGui.QLabel(self.p_disc)
        self.label_2.setGeometry(QtCore.QRect(110, 340, 261, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.l_format = QtGui.QLabel(self.p_disc)
        self.l_format.setGeometry(QtCore.QRect(480, 340, 111, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.l_format.setFont(font)
        self.l_format.setObjectName(_fromUtf8("l_format"))
        self.l_part_arrel = QtGui.QLabel(self.p_disc)
        self.l_part_arrel.setGeometry(QtCore.QRect(50, 366, 52, 16))
        font = QtGui.QFont()
        font.setItalic(True)
        self.l_part_arrel.setFont(font)
        self.l_part_arrel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.l_part_arrel.setObjectName(_fromUtf8("l_part_arrel"))
        self.l_part_swap = QtGui.QLabel(self.p_disc)
        self.l_part_swap.setGeometry(QtCore.QRect(20, 403, 81, 20))
        font = QtGui.QFont()
        font.setItalic(True)
        self.l_part_swap.setFont(font)
        self.l_part_swap.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.l_part_swap.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.l_part_swap.setObjectName(_fromUtf8("l_part_swap"))
        self.l_part_home = QtGui.QLabel(self.p_disc)
        self.l_part_home.setGeometry(QtCore.QRect(50, 443, 52, 16))
        font = QtGui.QFont()
        font.setItalic(True)
        self.l_part_home.setFont(font)
        self.l_part_home.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.l_part_home.setObjectName(_fromUtf8("l_part_home"))
        self.label_6 = QtGui.QLabel(self.p_disc)
        self.label_6.setGeometry(QtCore.QRect(530, 20, 64, 64))
        self.label_6.setText(_fromUtf8(""))
        self.label_6.setPixmap(QtGui.QPixmap(_fromUtf8("../../../../../usr/share/kademar/utils/instalador/img/hdd.png")))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.pages.addWidget(self.p_disc)
        self.p_license = QtGui.QWidget()
        self.p_license.setObjectName(_fromUtf8("p_license"))
        self.l_titol_10 = QtGui.QLabel(self.p_license)
        self.l_titol_10.setGeometry(QtCore.QRect(30, 70, 561, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.l_titol_10.setFont(font)
        self.l_titol_10.setAlignment(QtCore.Qt.AlignCenter)
        self.l_titol_10.setObjectName(_fromUtf8("l_titol_10"))
        self.label_28 = QtGui.QLabel(self.p_license)
        self.label_28.setGeometry(QtCore.QRect(50, 100, 511, 321))
        self.label_28.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_28.setWordWrap(True)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.rb_license_yes = QtGui.QRadioButton(self.p_license)
        self.rb_license_yes.setGeometry(QtCore.QRect(80, 430, 501, 21))
        self.rb_license_yes.setObjectName(_fromUtf8("rb_license_yes"))
        self.rb_license_no = QtGui.QRadioButton(self.p_license)
        self.rb_license_no.setGeometry(QtCore.QRect(80, 460, 491, 21))
        self.rb_license_no.setObjectName(_fromUtf8("rb_license_no"))
        self.label_4 = QtGui.QLabel(self.p_license)
        self.label_4.setGeometry(QtCore.QRect(530, 20, 64, 64))
        self.label_4.setText(_fromUtf8(""))
        self.label_4.setPixmap(QtGui.QPixmap(_fromUtf8("../../../../../usr/share/kademar/utils/instalador/img/license.png")))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.pages.addWidget(self.p_license)
        self.p_sistema = QtGui.QWidget()
        self.p_sistema.setObjectName(_fromUtf8("p_sistema"))
        self.t_pc = QtGui.QLineEdit(self.p_sistema)
        self.t_pc.setGeometry(QtCore.QRect(190, 240, 191, 24))
        self.t_pc.setInputMask(_fromUtf8(""))
        self.t_pc.setAlignment(QtCore.Qt.AlignCenter)
        self.t_pc.setObjectName(_fromUtf8("t_pc"))
        self.label_27 = QtGui.QLabel(self.p_sistema)
        self.label_27.setGeometry(QtCore.QRect(50, 100, 511, 91))
        self.label_27.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_27.setWordWrap(True)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.b_cat = QtGui.QPushButton(self.p_sistema)
        self.b_cat.setGeometry(QtCore.QRect(90, 301, 121, 41))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../usr/share/kademar/utils/instalador/img/cat.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_cat.setIcon(icon6)
        self.b_cat.setIconSize(QtCore.QSize(22, 22))
        self.b_cat.setCheckable(True)
        self.b_cat.setObjectName(_fromUtf8("b_cat"))
        self.l_pc = QtGui.QLabel(self.p_sistema)
        self.l_pc.setGeometry(QtCore.QRect(50, 210, 441, 16))
        self.l_pc.setObjectName(_fromUtf8("l_pc"))
        self.l_titol_3 = QtGui.QLabel(self.p_sistema)
        self.l_titol_3.setGeometry(QtCore.QRect(30, 70, 561, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.l_titol_3.setFont(font)
        self.l_titol_3.setAlignment(QtCore.Qt.AlignCenter)
        self.l_titol_3.setObjectName(_fromUtf8("l_titol_3"))
        self.b_eng = QtGui.QPushButton(self.p_sistema)
        self.b_eng.setGeometry(QtCore.QRect(410, 300, 121, 41))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../usr/share/kademar/utils/instalador/img/eng.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_eng.setIcon(icon7)
        self.b_eng.setIconSize(QtCore.QSize(22, 22))
        self.b_eng.setCheckable(True)
        self.b_eng.setObjectName(_fromUtf8("b_eng"))
        self.b_esp = QtGui.QPushButton(self.p_sistema)
        self.b_esp.setGeometry(QtCore.QRect(250, 301, 121, 41))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../usr/share/kademar/utils/instalador/img/esp.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_esp.setIcon(icon8)
        self.b_esp.setIconSize(QtCore.QSize(22, 22))
        self.b_esp.setCheckable(True)
        self.b_esp.setObjectName(_fromUtf8("b_esp"))
        self.l_bandera = QtGui.QLabel(self.p_sistema)
        self.l_bandera.setGeometry(QtCore.QRect(250, 370, 121, 121))
        self.l_bandera.setText(_fromUtf8(""))
        self.l_bandera.setPixmap(QtGui.QPixmap(_fromUtf8("../../../../../usr/share/kademar/utils/instalador/img/cat.png")))
        self.l_bandera.setScaledContents(True)
        self.l_bandera.setObjectName(_fromUtf8("l_bandera"))
        self.label_5 = QtGui.QLabel(self.p_sistema)
        self.label_5.setGeometry(QtCore.QRect(530, 20, 64, 64))
        self.label_5.setText(_fromUtf8(""))
        self.label_5.setPixmap(QtGui.QPixmap(_fromUtf8("../../../../../usr/share/kademar/utils/instalador/img/system.png")))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.pages.addWidget(self.p_sistema)
        self.p_passwd = QtGui.QWidget()
        self.p_passwd.setObjectName(_fromUtf8("p_passwd"))
        self.t_root_passwd1 = QtGui.QLineEdit(self.p_passwd)
        self.t_root_passwd1.setGeometry(QtCore.QRect(140, 300, 311, 24))
        self.t_root_passwd1.setMaxLength(12)
        self.t_root_passwd1.setEchoMode(QtGui.QLineEdit.Password)
        self.t_root_passwd1.setObjectName(_fromUtf8("t_root_passwd1"))
        self.l_root_passwd2 = QtGui.QLabel(self.p_passwd)
        self.l_root_passwd2.setGeometry(QtCore.QRect(100, 360, 431, 16))
        self.l_root_passwd2.setObjectName(_fromUtf8("l_root_passwd2"))
        self.label_10 = QtGui.QLabel(self.p_passwd)
        self.label_10.setGeometry(QtCore.QRect(50, 100, 511, 161))
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.l_root_passwd1 = QtGui.QLabel(self.p_passwd)
        self.l_root_passwd1.setGeometry(QtCore.QRect(100, 270, 441, 16))
        self.l_root_passwd1.setObjectName(_fromUtf8("l_root_passwd1"))
        self.t_root_passwd2 = QtGui.QLineEdit(self.p_passwd)
        self.t_root_passwd2.setGeometry(QtCore.QRect(140, 390, 311, 24))
        self.t_root_passwd2.setMaxLength(12)
        self.t_root_passwd2.setEchoMode(QtGui.QLineEdit.Password)
        self.t_root_passwd2.setObjectName(_fromUtf8("t_root_passwd2"))
        self.l_titol_4 = QtGui.QLabel(self.p_passwd)
        self.l_titol_4.setGeometry(QtCore.QRect(30, 70, 561, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.l_titol_4.setFont(font)
        self.l_titol_4.setAlignment(QtCore.Qt.AlignCenter)
        self.l_titol_4.setObjectName(_fromUtf8("l_titol_4"))
        self.label_11 = QtGui.QLabel(self.p_passwd)
        self.label_11.setGeometry(QtCore.QRect(530, 20, 64, 64))
        self.label_11.setText(_fromUtf8(""))
        self.label_11.setPixmap(QtGui.QPixmap(_fromUtf8("../../../../../usr/share/kademar/utils/instalador/img/root.png")))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.pages.addWidget(self.p_passwd)
        self.p_usuari = QtGui.QWidget()
        self.p_usuari.setObjectName(_fromUtf8("p_usuari"))
        self.l_user_account = QtGui.QLabel(self.p_usuari)
        self.l_user_account.setGeometry(QtCore.QRect(60, 340, 241, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.l_user_account.setFont(font)
        self.l_user_account.setObjectName(_fromUtf8("l_user_account"))
        self.label_19 = QtGui.QLabel(self.p_usuari)
        self.label_19.setGeometry(QtCore.QRect(50, 100, 511, 151))
        self.label_19.setAutoFillBackground(False)
        self.label_19.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_19.setWordWrap(True)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.t_user_account = QtGui.QLineEdit(self.p_usuari)
        self.t_user_account.setGeometry(QtCore.QRect(80, 360, 191, 24))
        self.t_user_account.setMaxLength(20)
        self.t_user_account.setEchoMode(QtGui.QLineEdit.Normal)
        self.t_user_account.setObjectName(_fromUtf8("t_user_account"))
        self.l_user_passwd2 = QtGui.QLabel(self.p_usuari)
        self.l_user_passwd2.setGeometry(QtCore.QRect(300, 410, 271, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.l_user_passwd2.setFont(font)
        self.l_user_passwd2.setObjectName(_fromUtf8("l_user_passwd2"))
        self.t_nom = QtGui.QLineEdit(self.p_usuari)
        self.t_nom.setGeometry(QtCore.QRect(80, 290, 410, 24))
        self.t_nom.setMaxLength(50)
        self.t_nom.setEchoMode(QtGui.QLineEdit.Normal)
        self.t_nom.setObjectName(_fromUtf8("t_nom"))
        self.t_user_passwd2 = QtGui.QLineEdit(self.p_usuari)
        self.t_user_passwd2.setGeometry(QtCore.QRect(320, 430, 191, 24))
        self.t_user_passwd2.setMaxLength(20)
        self.t_user_passwd2.setEchoMode(QtGui.QLineEdit.Password)
        self.t_user_passwd2.setObjectName(_fromUtf8("t_user_passwd2"))
        self.l_nom = QtGui.QLabel(self.p_usuari)
        self.l_nom.setGeometry(QtCore.QRect(60, 270, 281, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.l_nom.setFont(font)
        self.l_nom.setObjectName(_fromUtf8("l_nom"))
        self.l_titol_7 = QtGui.QLabel(self.p_usuari)
        self.l_titol_7.setGeometry(QtCore.QRect(30, 70, 561, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.l_titol_7.setFont(font)
        self.l_titol_7.setAlignment(QtCore.Qt.AlignCenter)
        self.l_titol_7.setObjectName(_fromUtf8("l_titol_7"))
        self.cb_autologin = QtGui.QCheckBox(self.p_usuari)
        self.cb_autologin.setGeometry(QtCore.QRect(320, 350, 261, 41))
        self.cb_autologin.setObjectName(_fromUtf8("cb_autologin"))
        self.t_user_passwd1 = QtGui.QLineEdit(self.p_usuari)
        self.t_user_passwd1.setGeometry(QtCore.QRect(80, 430, 191, 24))
        self.t_user_passwd1.setMaxLength(20)
        self.t_user_passwd1.setEchoMode(QtGui.QLineEdit.Password)
        self.t_user_passwd1.setObjectName(_fromUtf8("t_user_passwd1"))
        self.l_user_passwd1 = QtGui.QLabel(self.p_usuari)
        self.l_user_passwd1.setGeometry(QtCore.QRect(60, 410, 231, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.l_user_passwd1.setFont(font)
        self.l_user_passwd1.setObjectName(_fromUtf8("l_user_passwd1"))
        self.label_12 = QtGui.QLabel(self.p_usuari)
        self.label_12.setGeometry(QtCore.QRect(490, 10, 111, 71))
        self.label_12.setText(_fromUtf8(""))
        self.label_12.setPixmap(QtGui.QPixmap(_fromUtf8("../../../../../usr/share/kademar/utils/instalador/img/users.png")))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.pages.addWidget(self.p_usuari)
        self.p_mbr = QtGui.QWidget()
        self.p_mbr.setObjectName(_fromUtf8("p_mbr"))
        self.label_30 = QtGui.QLabel(self.p_mbr)
        self.label_30.setGeometry(QtCore.QRect(50, 100, 511, 171))
        self.label_30.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_30.setWordWrap(True)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.rb_man = QtGui.QRadioButton(self.p_mbr)
        self.rb_man.setGeometry(QtCore.QRect(100, 370, 381, 22))
        font = QtGui.QFont()
        font.setItalic(True)
        self.rb_man.setFont(font)
        self.rb_man.setObjectName(_fromUtf8("rb_man"))
        self.rb_auto = QtGui.QRadioButton(self.p_mbr)
        self.rb_auto.setGeometry(QtCore.QRect(100, 280, 331, 22))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.rb_auto.setFont(font)
        self.rb_auto.setChecked(True)
        self.rb_auto.setObjectName(_fromUtf8("rb_auto"))
        self.rb_no = QtGui.QRadioButton(self.p_mbr)
        self.rb_no.setGeometry(QtCore.QRect(100, 310, 411, 51))
        font = QtGui.QFont()
        font.setItalic(True)
        self.rb_no.setFont(font)
        self.rb_no.setObjectName(_fromUtf8("rb_no"))
        self.l_titol_6 = QtGui.QLabel(self.p_mbr)
        self.l_titol_6.setGeometry(QtCore.QRect(30, 70, 561, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.l_titol_6.setFont(font)
        self.l_titol_6.setAlignment(QtCore.Qt.AlignCenter)
        self.l_titol_6.setObjectName(_fromUtf8("l_titol_6"))
        self.cb_mbr = QtGui.QComboBox(self.p_mbr)
        self.cb_mbr.setGeometry(QtCore.QRect(150, 410, 311, 22))
        self.cb_mbr.setObjectName(_fromUtf8("cb_mbr"))
        self.ch_initrd = QtGui.QCheckBox(self.p_mbr)
        self.ch_initrd.setGeometry(QtCore.QRect(100, 460, 411, 31))
        self.ch_initrd.setObjectName(_fromUtf8("ch_initrd"))
        self.label_13 = QtGui.QLabel(self.p_mbr)
        self.label_13.setGeometry(QtCore.QRect(530, 20, 64, 64))
        self.label_13.setText(_fromUtf8(""))
        self.label_13.setPixmap(QtGui.QPixmap(_fromUtf8("../../../../../usr/share/kademar/utils/instalador/img/reboot.png")))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.pages.addWidget(self.p_mbr)
        self.p_final = QtGui.QWidget()
        self.p_final.setObjectName(_fromUtf8("p_final"))
        self.l_titol_5 = QtGui.QLabel(self.p_final)
        self.l_titol_5.setGeometry(QtCore.QRect(30, 70, 561, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.l_titol_5.setFont(font)
        self.l_titol_5.setAlignment(QtCore.Qt.AlignCenter)
        self.l_titol_5.setObjectName(_fromUtf8("l_titol_5"))
        self.label_32 = QtGui.QLabel(self.p_final)
        self.label_32.setGeometry(QtCore.QRect(60, 170, 511, 171))
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setWordWrap(True)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.label_14 = QtGui.QLabel(self.p_final)
        self.label_14.setGeometry(QtCore.QRect(530, 20, 64, 64))
        self.label_14.setText(_fromUtf8(""))
        self.label_14.setPixmap(QtGui.QPixmap(_fromUtf8("../../../../../usr/share/kademar/utils/instalador/img/flag_yellow.png")))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.l_clock = QtGui.QLabel(self.p_final)
        self.l_clock.setGeometry(QtCore.QRect(270, 330, 100, 100))
        self.l_clock.setText(_fromUtf8(""))
        self.l_clock.setPixmap(QtGui.QPixmap(_fromUtf8("../../../../../usr/share/kademar/utils/instalador/img/wait2.gif")))
        self.l_clock.setScaledContents(True)
        self.l_clock.setObjectName(_fromUtf8("l_clock"))
        self.pages.addWidget(self.p_final)
        self.p_end = QtGui.QWidget()
        self.p_end.setObjectName(_fromUtf8("p_end"))
        self.l_titol_8 = QtGui.QLabel(self.p_end)
        self.l_titol_8.setGeometry(QtCore.QRect(140, 100, 331, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.l_titol_8.setFont(font)
        self.l_titol_8.setAlignment(QtCore.Qt.AlignCenter)
        self.l_titol_8.setObjectName(_fromUtf8("l_titol_8"))
        self.label_33 = QtGui.QLabel(self.p_end)
        self.label_33.setGeometry(QtCore.QRect(120, 130, 361, 251))
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setWordWrap(True)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.cb_reboot = QtGui.QCheckBox(self.p_end)
        self.cb_reboot.setGeometry(QtCore.QRect(220, 410, 161, 21))
        self.cb_reboot.setObjectName(_fromUtf8("cb_reboot"))
        self.label_15 = QtGui.QLabel(self.p_end)
        self.label_15.setGeometry(QtCore.QRect(530, 20, 64, 64))
        self.label_15.setText(_fromUtf8(""))
        self.label_15.setPixmap(QtGui.QPixmap(_fromUtf8("../../../../../usr/share/kademar/utils/instalador/img/flag.png")))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.pages.addWidget(self.p_end)

        self.retranslateUi(FormInstall)
        self.pages.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(FormInstall)
        FormInstall.setTabOrder(self.boto_next, self.boto_back)
        FormInstall.setTabOrder(self.boto_back, self.boto_exit)
        FormInstall.setTabOrder(self.boto_exit, self.ch_tot_en_particio)
        FormInstall.setTabOrder(self.ch_tot_en_particio, self.ch_adv)
        FormInstall.setTabOrder(self.ch_adv, self.boto_particionar)
        FormInstall.setTabOrder(self.boto_particionar, self.cb_hd_arrel)
        FormInstall.setTabOrder(self.cb_hd_arrel, self.cb_hd_format_arrel)
        FormInstall.setTabOrder(self.cb_hd_format_arrel, self.cb_hd_swap)
        FormInstall.setTabOrder(self.cb_hd_swap, self.cb_hd_format_swap)
        FormInstall.setTabOrder(self.cb_hd_format_swap, self.cb_hd_home)
        FormInstall.setTabOrder(self.cb_hd_home, self.cb_hd_format_home)
        FormInstall.setTabOrder(self.cb_hd_format_home, self.t_pc)
        FormInstall.setTabOrder(self.t_pc, self.b_cat)
        FormInstall.setTabOrder(self.b_cat, self.b_esp)
        FormInstall.setTabOrder(self.b_esp, self.b_eng)
        FormInstall.setTabOrder(self.b_eng, self.t_root_passwd1)
        FormInstall.setTabOrder(self.t_root_passwd1, self.t_root_passwd2)
        FormInstall.setTabOrder(self.t_root_passwd2, self.t_nom)
        FormInstall.setTabOrder(self.t_nom, self.t_user_account)
        FormInstall.setTabOrder(self.t_user_account, self.cb_autologin)
        FormInstall.setTabOrder(self.cb_autologin, self.t_user_passwd1)
        FormInstall.setTabOrder(self.t_user_passwd1, self.t_user_passwd2)
        FormInstall.setTabOrder(self.t_user_passwd2, self.rb_auto)
        FormInstall.setTabOrder(self.rb_auto, self.rb_man)
        FormInstall.setTabOrder(self.rb_man, self.rb_no)
        FormInstall.setTabOrder(self.rb_no, self.cb_mbr)

    def retranslateUi(self, FormInstall):
        FormInstall.setWindowTitle(QtGui.QApplication.translate("FormInstall", "Installer", None, QtGui.QApplication.UnicodeUTF8))
        self.l_titol.setText(QtGui.QApplication.translate("FormInstall", "Installation Process", None, QtGui.QApplication.UnicodeUTF8))
        self.l_disc.setText(QtGui.QApplication.translate("FormInstall", "Disk and Partition", None, QtGui.QApplication.UnicodeUTF8))
        self.l_copia.setText(QtGui.QApplication.translate("FormInstall", "File Copy", None, QtGui.QApplication.UnicodeUTF8))
        self.l_sistema.setText(QtGui.QApplication.translate("FormInstall", "License", None, QtGui.QApplication.UnicodeUTF8))
        self.l_user.setText(QtGui.QApplication.translate("FormInstall", "User", None, QtGui.QApplication.UnicodeUTF8))
        self.l_mbr.setText(QtGui.QApplication.translate("FormInstall", "Boot Manager", None, QtGui.QApplication.UnicodeUTF8))
        self.l_passwd.setText(QtGui.QApplication.translate("FormInstall", "Administrator Password", None, QtGui.QApplication.UnicodeUTF8))
        self.l_license.setText(QtGui.QApplication.translate("FormInstall", "System", None, QtGui.QApplication.UnicodeUTF8))
        self.l_finished.setText(QtGui.QApplication.translate("FormInstall", "Copy Finished", None, QtGui.QApplication.UnicodeUTF8))
        self.boto_ajuda.setText(QtGui.QApplication.translate("FormInstall", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.boto_back.setText(QtGui.QApplication.translate("FormInstall", "Back", None, QtGui.QApplication.UnicodeUTF8))
        self.boto_next.setText(QtGui.QApplication.translate("FormInstall", "Next", None, QtGui.QApplication.UnicodeUTF8))
        self.boto_exit.setText(QtGui.QApplication.translate("FormInstall", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("FormInstall", "Welcome to kademar Linux Installer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("FormInstall", "kademar Installer have a help manual, it can be opened by clicking on \"Help\" button on left bar in any moment, or by clicking now right Information button.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("FormInstall", "Now kademar Installer is retreiving information of your system.\n"
"\n"
"Be patient, please.", None, QtGui.QApplication.UnicodeUTF8))
        self.l_titol_9.setText(QtGui.QApplication.translate("FormInstall", "Retreiving System Information", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("FormInstall", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'DejaVu Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">It\'s needed at least two partitions:</p>\n"
"<ul style=\"-qt-list-indent: 1;\"><li style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic;\">Root:</span> Where kademar will be installed.</li>\n"
"<li style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic;\">Swap:</span> Space for system management.</li></ul>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">If you want, you can have your user documents in a separated partition of system partition. To do it, uncheck <span style=\" font-style:italic;\">\"Within the same partition\".</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.l_titol_2.setText(QtGui.QApplication.translate("FormInstall", "Select partitions where install kademar", None, QtGui.QApplication.UnicodeUTF8))
        self.ch_tot_en_particio.setText(QtGui.QApplication.translate("FormInstall", "Within the same partition", None, QtGui.QApplication.UnicodeUTF8))
        self.boto_particionar.setText(QtGui.QApplication.translate("FormInstall", "Partitioning", None, QtGui.QApplication.UnicodeUTF8))
        self.ch_adv.setText(QtGui.QApplication.translate("FormInstall", "Advanced", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_hd_format_arrel.setItemText(0, QtGui.QApplication.translate("FormInstall", "Ext4", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_hd_format_arrel.setItemText(1, QtGui.QApplication.translate("FormInstall", "Reiser FS", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_hd_format_arrel.setItemText(2, QtGui.QApplication.translate("FormInstall", "Ext3", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_hd_format_arrel.setItemText(3, QtGui.QApplication.translate("FormInstall", "Ext2", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_hd_format_arrel.setItemText(4, QtGui.QApplication.translate("FormInstall", "No Format", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_hd_format_swap.setItemText(0, QtGui.QApplication.translate("FormInstall", "Swap FS", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_hd_format_home.setItemText(0, QtGui.QApplication.translate("FormInstall", "Ext4", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_hd_format_home.setItemText(1, QtGui.QApplication.translate("FormInstall", "Reiser FS", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_hd_format_home.setItemText(2, QtGui.QApplication.translate("FormInstall", "Ext3", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_hd_format_home.setItemText(3, QtGui.QApplication.translate("FormInstall", "Ext2", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_hd_format_home.setItemText(4, QtGui.QApplication.translate("FormInstall", "No Format", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("FormInstall", "Partition", None, QtGui.QApplication.UnicodeUTF8))
        self.l_format.setText(QtGui.QApplication.translate("FormInstall", "Format as", None, QtGui.QApplication.UnicodeUTF8))
        self.l_part_arrel.setText(QtGui.QApplication.translate("FormInstall", "Root", None, QtGui.QApplication.UnicodeUTF8))
        self.l_part_swap.setText(QtGui.QApplication.translate("FormInstall", "Swap", None, QtGui.QApplication.UnicodeUTF8))
        self.l_part_home.setText(QtGui.QApplication.translate("FormInstall", "Home", None, QtGui.QApplication.UnicodeUTF8))
        self.l_titol_10.setText(QtGui.QApplication.translate("FormInstall", "License", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("FormInstall", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'DejaVu Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">kademar Linux is free software, and this won\'t change.</span> </p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">In order to improve your user experience with kademar, kademar Team have decided to include non 100% free software. Resume of those non-free licenses included in kademar are:</p>\n"
"<ul style=\"-qt-list-indent: 1;\"><li style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">You cannot modify those programs.</li>\n"
"<li style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">You can redistribute it without any source modification</li></ul>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">You can read more about non-free licenses included on kademar, on kademar\'s webpage. </p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">If you doesn\'t accept it, all non-free software such as: DivX support, MP3 support, nVidia drivers, device firmwares, flash, java, etc. will be completly removed of your system, and kademar Linux would be converted to a Linux 100% free distribution, as in freedom. </p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Do you agree terms of non-free licenses included on kademar to maximize user experience?</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_license_yes.setText(QtGui.QApplication.translate("FormInstall", "Yes, I accept non-free license terms", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_license_no.setText(QtGui.QApplication.translate("FormInstall", "No, please remove all non-free software of kademar Linux", None, QtGui.QApplication.UnicodeUTF8))
        self.t_pc.setText(QtGui.QApplication.translate("FormInstall", "kademar", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("FormInstall", "Now you have to configure your PC name. It\'s used on local network identification.\n"
"\n"
"Also you have to define you default language of your system. You can change it later on CADI.", None, QtGui.QApplication.UnicodeUTF8))
        self.b_cat.setText(QtGui.QApplication.translate("FormInstall", "Català", None, QtGui.QApplication.UnicodeUTF8))
        self.l_pc.setText(QtGui.QApplication.translate("FormInstall", "PC Name (for local network identification, if you have it.)", None, QtGui.QApplication.UnicodeUTF8))
        self.l_titol_3.setText(QtGui.QApplication.translate("FormInstall", "System Configurations", None, QtGui.QApplication.UnicodeUTF8))
        self.b_eng.setText(QtGui.QApplication.translate("FormInstall", "English", None, QtGui.QApplication.UnicodeUTF8))
        self.b_esp.setText(QtGui.QApplication.translate("FormInstall", "Castellano", None, QtGui.QApplication.UnicodeUTF8))
        self.l_root_passwd2.setText(QtGui.QApplication.translate("FormInstall", "Reenter Administrator Password, to confirm it.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("FormInstall", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'DejaVu Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Now have to set the Adminstrator User password.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Administration User is the one with privileges and authorization to do any task on the system, even delete all the files.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Enter the password twice to confirm it and Remember it!</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; font-style:italic;\">(Keep this password in a safety place)</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.l_root_passwd1.setText(QtGui.QApplication.translate("FormInstall", "Enter Administration Password", None, QtGui.QApplication.UnicodeUTF8))
        self.l_titol_4.setText(QtGui.QApplication.translate("FormInstall", "Contrassenya d\'Administrador (root)", None, QtGui.QApplication.UnicodeUTF8))
        self.l_user_account.setText(QtGui.QApplication.translate("FormInstall", "Account name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("FormInstall", "Now you have to enter a user to be able to use the system.\n"
"Username can be your name, to create the accout that you\'ll use as default.\n"
"\n"
"For more security, you have to enter a password for the user.\n"
"If you don\'t want to be asked for it every time you start, check User Autostart checkbox.", None, QtGui.QApplication.UnicodeUTF8))
        self.l_user_passwd2.setText(QtGui.QApplication.translate("FormInstall", "Reenter User Password", None, QtGui.QApplication.UnicodeUTF8))
        self.l_nom.setText(QtGui.QApplication.translate("FormInstall", "Enter your name", None, QtGui.QApplication.UnicodeUTF8))
        self.l_titol_7.setText(QtGui.QApplication.translate("FormInstall", "User Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_autologin.setText(QtGui.QApplication.translate("FormInstall", "User Autostart\n"
" without ask your password.", None, QtGui.QApplication.UnicodeUTF8))
        self.l_user_passwd1.setText(QtGui.QApplication.translate("FormInstall", "User Password", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("FormInstall", "Here you have to indicate a disk where install Grub Boot Manager.\n"
"By default this selection is automatic, but you can set it manually.\n"
"Also you can bypass, setting not to install, but use it only if you know what you are doing.\n"
"\n"
"Grub will make you able to start kademar Linux on your machine and other operating systems.", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_man.setText(QtGui.QApplication.translate("FormInstall", "Manual - Advanced Selecction", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_auto.setText(QtGui.QApplication.translate("FormInstall", "Automatic - Recomended", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_no.setText(QtGui.QApplication.translate("FormInstall", "Do not install boot manager - NOT RECOMMENDED\n"
" (Only do it if you know what are doing)", None, QtGui.QApplication.UnicodeUTF8))
        self.l_titol_6.setText(QtGui.QApplication.translate("FormInstall", "Boot Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.ch_initrd.setText(QtGui.QApplication.translate("FormInstall", "Initrd (Activate if you receive an error when start)", None, QtGui.QApplication.UnicodeUTF8))
        self.l_titol_5.setText(QtGui.QApplication.translate("FormInstall", "Ending Installation Tasks", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("FormInstall", "Some installation tasks are pending.\n"
"\n"
"You have to wait while process is finishing.\n"
"You can see tasks status on left bar.", None, QtGui.QApplication.UnicodeUTF8))
        self.l_titol_8.setText(QtGui.QApplication.translate("FormInstall", "Installation Finished!!!", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("FormInstall", "kademar Linux it\'s installed on your PC\n"
"\n"
"Now you can close installer and continue using kademar on Live mode, or you can reboot you computer and start on the installed system.\n"
"\n"
"Remember to go to our webpage if you have some trouble.\n"
"\n"
"\n"
"\n"
"Thanks for choosing kademar Linux", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_reboot.setText(QtGui.QApplication.translate("FormInstall", "Reboot Computer", None, QtGui.QApplication.UnicodeUTF8))

