#!/bin/bash
#
# Creat per Adonay Sanz per la kademar  -  Agost 2007
# 21-05-09 firefox languages & unified settings
# 
# Configuration automated created by  crea_config-2nd_stage  of  kademar package
#

#### GENERAL DEFINITIONS ####

#User
user="kademar"

#Language
. /etc/default/locale

#Laptop
if [ "`cat /etc/kademar/laptop`" != 0 ]; then
	#If isn't a laptop
	laptop=no
    resposta_numlock=on #Activate numeric keypad
else
	#If it's a laptop
	laptop=yes
    resposta_numlock=off #Desactivate numeric keypad
fi


case "$LANG" in
ca*)
	documents=Documents
	desktop=Escriptori
	lang_firefox=ca  #in reference of kademar webpage
	firefoxlanguages="ca,es-es,en-us,en"
;;
es*)
	documents=Documentos
	desktop=Escritorio
	lang_firefox=es  #in reference of kademar webpage
	firefoxlanguages="es-es,en-us,en"

;;
en*|*)
	documents=Documents
	desktop=Desktop
	lang_firefox=en  #in reference of kademar webpage
	firefoxlanguages="en-us,en,es-es"

;;
esac


#start cpu frequency scale
# /etc/init.d/loadcpufreq start
# /etc/init.d/cpufrequtils start



#### EMD GENERALDEFINITIONS ####