Document: kademar-core-kde4
Title: Debian kademar-core-kde4 Manual
Author: <insert document author here>
Abstract: This manual describes what kademar-core-kde4 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/kademar-core-kde4/kademar-core-kde4.sgml.gz

Format: postscript
Files: /usr/share/doc/kademar-core-kde4/kademar-core-kde4.ps.gz

Format: text
Files: /usr/share/doc/kademar-core-kde4/kademar-core-kde4.text.gz

Format: HTML
Index: /usr/share/doc/kademar-core-kde4/html/index.html
Files: /usr/share/doc/kademar-core-kde4/html/*.html
