#!/bin/sh
set -e
# Automatically added by dh_installmodules

case "$1" in
    purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)

	#Networking DHCP Permissive
        if [ remove = "$1" ]; then
#                 if [ -e /usr/share/apps/kicker/pics/kside.png-orig ]; then
#                         rm /usr/share/apps/kicker/pics/kside.png
#                 fi
#                 if [ -e /etc/kde3/kdm/kdmrc.orig ]; then
#                         rm /etc/kde3/kdm/kdmrc
#                 fi
#                 if [ -e /etc/kde3/kdm/backgroundrc.orig ]; then
#                         rm /etc/kde3/kdm/backgroundrc
#                 fi

                rm -f /etc/kde3/kdm/backgroundrc /etc/kde3/kdm/kdmrc /opt/kde3/share/apps/kicker/pics/kside.png
                dpkg-divert --package kademar-kde3-core --remove --divert /usr/share/apps/kicker/pics/kside.png-orig --rename /usr/share/apps/kicker/pics/kside.png
                dpkg-divert --package kademar-kde3-core --remove --divert /etc/kde3/kdm/kdmrc.orig --rename /etc/kde3/kdm/kdmrc
                dpkg-divert --package kademar-kde3-core --remove --divert /etc/kde3/kdm/backgroundrc.orig --rename /etc/kde3/kdm/backgroundrc
#                 dpkg-divert --remove /etc/kde3/kdm/backgroundrc
#                 dpkg-divert --remove /etc/kde3/kdm/kdmrc
#                 dpkg-divert --remove /opt/kde3/share/apps/kicker/pics/kside.png

        fi

        ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0