#!/bin/bash
#
# Created by Adonay Sanz for kademar  -  Genuary 2006
#  Script to Create Documents folder
#
# Modification 09-06-10: Icon part (combinated with xdg-user-dirs)
#

# mode to call it:
# documents                  -  for your current user

#Load language conf_file
. /etc/default/locale

#get translation from xdg-user-dirs
docs=`gettext -d xdg-user-dirs -s "Documents"`
desk=`gettext -d xdg-user-dirs -s "Desktop"`
down=`gettext -d xdg-user-dirs -s "Downloads"`
video=`gettext -d xdg-user-dirs -s "Videos"`
audio=`gettext -d xdg-user-dirs -s "Music"`
img=`gettext -d xdg-user-dirs -s "Pictures"`
tmpl=`gettext -d xdg-user-dirs -s "Templates"`
pub=`gettext -d xdg-user-dirs -s "Public"`

case "$LANG" in
ca*)
# 		amsn="Arxius Rebuts Amsn"
	sample=" de mostra"
;;
en*)

# 		amsn="Amsn Received Files"
	sample=" sample"
;;
es*|*)
# 		amsn="Archivos Recibidos Amsn"
	sample=" de muestra"
;;
esac


#Link Part
# 	[ ! -e "$HOME/$desk/$docs" ] && ln -s -n "$HOME/$docs" "$HOME/$desk/$docs"

# 	mkdir -p "$HOME/$down/$amsn/"

#Icon Parts
#Docs
if [ ! -e "$HOME/$docs/.directory" -a -e "$HOME/$docs/" ]; then
	echo "[Desktop Entry]
Icon=/usr/share/icons/oxygen/256x256/places/folder-documents.png" > "$HOME/$docs/.directory"
fi
#Downloads
if [ ! -e "$HOME/$down/.directory" -a -e "$HOME/$down/" ]; then
	echo "[Desktop Entry]
Icon=/usr/share/icons/oxygen/256x256/places/folder-downloads.png" > "$HOME/$down/.directory"
fi
#Video
if [ ! -e "$HOME/$video/.directory" -a -e "$HOME/$video/" ]; then
	echo "[Desktop Entry]
Icon=/usr/share/icons/oxygen/256x256/places/folder-video.png" > "$HOME/$video/.directory"
fi
#Audio
if [ ! -e "$HOME/$audio/.directory" -a -e "$HOME/$audio/" ]; then
	echo "[Desktop Entry]
Icon=/usr/share/icons/oxygen/256x256/places/folder-sound.png" > "$HOME/$audio/.directory"
fi
#Images
if [ ! -e "$HOME/$img/.directory" -a -e "$HOME/$img/" ]; then
	echo "[Desktop Entry]
Icon=/usr/share/icons/oxygen/256x256/places/folder-image.png" > "$HOME/$img/.directory"
fi
#Public (Amule - Apollon)
if [ ! -e "$HOME/$pub/.directory" -a -e "$HOME/$pub/" ]; then
	echo "[Desktop Entry]
Icon=/usr/share/icons/oxygen/256x256/places/folder-remote.png" > "$HOME/$pub/.directory"
fi
#Amsn
# 	if [ ! -e "$HOME/$shared/$amsn/.directory" -a -e "$HOME/$shared/$amsn/" ]; then
# 		echo "[Desktop Entry]
# Icon=/usr/share/icons/oxygen/256x256/places//usr/share/kademar/icons/amsn_folder.png" > "$HOME/$shared/$amsn/.directory"
# 	fi
#Templates
if [ ! -e "$HOME/$tmpl/.directory" -a -e "$HOME/$tmpl/" ]; then
	echo "[Desktop Entry]
Icon=/usr/share/icons/oxygen/256x256/places/folder-html.png" > "$HOME/$tmpl/.directory"
fi
#Carpeta de samples si existeixen i no exiteix el link que volem crear
[ -e /usr/share/kademar/media_sample/sound ] && [ ! -e "$HOME/$audio/$audio$sample" ] && ln -s /usr/share/kademar/media_sample/sound "$HOME/$audio/$audio$sample"
[ -e /usr/share/kademar/media_sample/video ] && [ ! -e "$HOME/$video/$video$sample" ] && ln -s /usr/share/kademar/media_sample/video "$HOME/$video/$video$sample"

#Si existeix media_sample/wallpapers  es una copia (per no tenir els  .desktop pel mig)
if [ -e /usr/share/kademar/media_sample/wallpapers ]; then
	[ ! -e "$HOME/$img/$img$sample" ] && ln -s /usr/share/kademar/media_sample/wallpapers "$HOME/$img/$img$sample"
else
	[ -e /usr/share/wallpapers ] && [ ! -e "$HOME/$img/$img$sample" ] && ln -s /usr/share/wallpapers "$HOME/$img/$img$sample"
fi
