#!/bin/bash

#################################################
# Script per Configurar l'idioma amb el CADI    #
#         -------------------------             #
#    Preparat per la kademar 4.0 - 3 Nov 2005   #
#        Modificat   kademar 4.1 - 20 Feb 2006  #
#        Modificat   kademar 4.3 - 5 Set 2006   #
#        Modificat   kademar 4.8 - 2 Feb 2009   #
#    Llicenciat Sota GNU/GPL 2.0 o Superiors    #
#################################################


locale_file=/etc/environment
motd_file=/etc/motd
issue_file=/etc/issue

#Check parameters
[ -z "$1" ] && echo "I need at least a LANG (xx) parameter to work" && exit 1

LANGUAGE="$1"
#echo $LANGUAGE #DEBUG

#Target folder, may change
[ -n "$2" ] && DESTI="$2"

########### //  LOCALE DEFINITION EXTRACTED FROM KNOPPIX \\ #############

case "$LANGUAGE" in
# Catalan version
ca*)
COUNTRY="es"
LANG="ca_ES@euro"
KEYTABLE="es"
LANG_COUNTRY="ca_ES"
XKEYBOARD="es"
KDEKEYBOARD="es"
CHARSET="iso8859-15"
# Additional KDE Keyboards
KDEKEYBOARDS=""
TZ="Europe/Madrid"
OPTIONAL=":ca_ES:ca:es_ES@euro:es_ES:es"
motd="Benvinguts a  kademar Linux"
;;
# German version
de*)
COUNTRY="de"
LANG="de_DE@euro"
KEYTABLE="de-latin1-nodeadkeys"
XKEYBOARD="de"
KDEKEYBOARD="de"
CHARSET="iso8859-15"
# Additional KDE Keyboards
KDEKEYBOARDS="us,fr"
TZ="Europe/Berlin"
;;
# Belgian version
be*)
LANGUAGE="be"
COUNTRY="be"
LANG="C"
KEYTABLE="be2-latin1"
XKEYBOARD="be"
KDEKEYBOARD="be"
CHARSET="iso8859-15"
# Additional KDE Keyboards
KDEKEYBOARDS="us,de,fr"
TZ="Europe/Brussels"
;;
# Bulgarian version
bg*)
LANGUAGE="bg"
COUNTRY="bg"
LANG="bg_BG"
KEYTABLE="bg"
XKEYBOARD="bg"
KDEKEYBOARD="bg"
CHARSET="microsoft-cp1251"
# Additional KDE Keyboards
KDEKEYBOARDS="us,de,fr"
TZ="Europe/Sofia"
;;
# Swiss version (basically de with some modifications*)
ch*)
LANGUAGE="de"
COUNTRY="ch"
LANG="de_CH"
KEYTABLE="sg-latin1"
XKEYBOARD="de_CH"
KDEKEYBOARD="de_CH"
CHARSET="iso8859-15"
# Additional KDE Keyboards
KDEKEYBOARDS="de,us,fr"
TZ="Europe/Zurich"
;;
cn*)
# Simplified Chinese version
COUNTRY="cn"
LANG="zh_CN.GB2312"
KEYTABLE="us"
XKEYBOARD="us"
KDEKEYBOARD="us"
CHARSET="gb2312.1980-0"
# Additional KDE Keyboards
KDEKEYBOARDS="us,de,fr"
XMODIFIERS="@im=Chinput"
TZ="Asia/Shanghai"
;;
# Czech version
cs*|cz*)
LANGUAGE="cs"
COUNTRY="cs"
LANG="cs_CZ"
KEYTABLE="cz-lat2"
XKEYBOARD="cs"
KDEKEYBOARD="cs"
CHARSET="iso8859-2"
# Additional KDE Keyboards
KDEKEYBOARDS="us,de,fr"
TZ="Europe/Prague"
CONSOLEFONT="iso02g"
;;
dk*|da*)
# Dansk version
COUNTRY="dk"
LANG="da_DK"
# Workaround: "dk" broken in gettext, use da:da_DK
LANGUAGE="da:da_DK"
# Keytable "dk" is correct.
KEYTABLE="dk"
XKEYBOARD="dk"
KDEKEYBOARD="dk"
CHARSET="iso8859-15"
# Additional KDE Keyboards
KDEKEYBOARDS="dk,de,us,fr"
TZ="Europe/Copenhagen"
;;
es*)
# Spanish version
COUNTRY="es"
LANG="es_ES@euro"
KEYTABLE="es"
LANG_COUNTRY="es_ES"
XKEYBOARD="es"
KDEKEYBOARD="es"
CHARSET="iso8859-15"
# Additional KDE Keyboards
KDEKEYBOARDS="de,us,fr"
TZ="Europe/Madrid"
OPTIONAL=":es_ES:es"
motd="Bienvenidos a  kademar Linux"
;;
fi*)
# Finnish version, though we may not have the kde-i18n files
COUNTRY="fi"
LANG="fi_FI@euro"
KEYTABLE="fi"
XKEYBOARD="fi"
KDEKEYBOARD="fi"
CHARSET="iso8859-15"
# Additional KDE Keyboards
KDEKEYBOARDS="us"
TZ="Europe/Helsinki"
;;
fr*)
# French version
COUNTRY="fr"
LANG="fr_FR@euro"
KEYTABLE="fr"
XKEYBOARD="fr"
KDEKEYBOARD="fr"
CHARSET="iso8859-15"
# Additional KDE Keyboards
KDEKEYBOARDS="de,us"
TZ="Europe/Paris"
;;
he*|il*)
# Hebrew version
LANGUAGE="he"
COUNTRY="il"
LANG="he_IL"
KEYTABLE="us"
XKEYBOARD="us"
KDEKEYBOARD="il"
CHARSET="iso8859-8"
# Additional KDE Keyboards
KDEKEYBOARDS="us,fr,de"
TZ="Asia/Jerusalem"
;;
ie*)
# Irish (English) version
COUNTRY="ie"
LANG="en_IE@euro"
KEYTABLE="uk"
XKEYBOARD="uk"
KDEKEYBOARD="gb"
CHARSET="iso8859-15"
#Additional KDE Keyboards
KDEKEYBOARDS="us,de,es,fr,it"
TZ="Europe/Dublin"
;;
it*)
# Italian version
COUNTRY="it"
LANG="it_IT@euro"
KEYTABLE="it"
XKEYBOARD="it"
KDEKEYBOARD="it"
CHARSET="iso8859-15"
# Additional KDE Keyboards
KDEKEYBOARDS="fr,us,de"
TZ="Europe/Rome"
;;
ja*)
# (limited) Japanese version
COUNTRY="jp"
LANG="ja_JP"
LANGUAGE="ja"
KEYTABLE="us"
XKEYBOARD="us"
KDEKEYBOARD="us"
CHARSET="iso8859-15"
# Additional KDE Keyboards
KDEKEYBOARDS="fr,us,de"
TZ="Asia/Tokyo"
;;
nl*)
# Dutch version
COUNTRY="nl"
LANG="nl_NL@euro"
KEYTABLE="us"
XKEYBOARD="us"
KDEKEYBOARD="en_US"
CHARSET="iso8859-15"
# Additional KDE Keyboards
KDEKEYBOARDS="nl,de,fr"
TZ="Europe/Amsterdam"
;;
pl*)
# Polish version
COUNTRY="pl"
LANG="pl_PL"
KEYTABLE="pl"
XKEYBOARD="pl"
KDEKEYBOARD="pl"
CHARSET="iso8859-2"
# Additional KDE Keyboards
KDEKEYBOARDS="de,us,fr"
TZ="Europe/Warsaw"
CONSOLEFONT="iso02g"
;;
ru*)
# Russian version
COUNTRY="ru"
LANG="ru_RU.KOI8-R"
KEYTABLE="ru"
XKEYBOARD="ru"
KDEKEYBOARD="ru"
CHARSET="koi8-r"
CONSOLEFONT="Cyr_a8x16"
# Additional KDE Keyboards
KDEKEYBOARDS="de,us,fr"
TZ="Europe/Moscow"
;;
sk*)
# Slovak version (guessed)
COUNTRY="sk"
LANG="sk"
KEYTABLE="sk-qwerty"
XKEYBOARD="sk"
KDEKEYBOARD="sk"
CHARSET="iso8859-2"
# Additional KDE Keyboards
KDEKEYBOARDS="us,de"
TZ="Europe/Bratislava"
CONSOLEFONT="iso02g"
;;
# Slovenian keyboard
sl*)
LANGUAGE="sl"
COUNTRY="si"
LANG="sl_SI"
KEYTABLE="slovene"
XKEYBOARD="sl"
KDEKEYBOARD="si"
CHARSET="iso8859-2"
# Additional KDE Keyboards
KDEKEYBOARDS="us,de"
TZ="Europe/Ljubljana"
CONSOLEFONT="iso02g"
;;
tr*)
# Turkish version (guessed)
COUNTRY="tr"
LANG="tr_TR"
KEYTABLE="tr_q-latin5"
XKEYBOARD="tr"
KDEKEYBOARD="tr"
CHARSET="iso8859-9"
# Additional KDE Keyboards
KDEKEYBOARDS="us,de,fr"
TZ="Europe/Istanbul"
;;
tw*)
# Traditional Chinese version (thanks to Chung-Yen Chang)
COUNTRY="tw"
LANG="zh_TW.Big5"
LANGUAGE="zh_TW.Big5"
KEYTABLE="us"
XKEYBOARD="us"
KDEKEYBOARD="us"
# CHARSET="big5-0"
CHARSET="iso8859-1"
# Additional KDE Keyboards
KDEKEYBOARDS="us"
XMODIFIERS="@im=xcin"
TZ="Asia/Taipei"
;;
uk*)
# British version
COUNTRY="uk"
LANG="en_GB"
LANGUAGE="en"
KEYTABLE="uk"
XKEYBOARD="uk"
KDEKEYBOARD="gb"
CHARSET="iso8859-1"
# Additional KDE Keyboards
KDEKEYBOARDS="us"
TZ="Europe/London"
motd="Welcome to  kademar Linux"
;;
en|*)
# American version
LANGUAGE="us"
COUNTRY="us"
LANG="en"
KEYTABLE="us"
XKEYBOARD="us"
KDEKEYBOARD="us"
CHARSET="iso8859-1"
# Additional KDE Keyboards
KDEKEYBOARDS="de,fr"
TZ="America/New_York"
motd="Welcome to  kademar Linux"
;;
esac

################ //  END OF LOCALE DEFINITION  \\  ####################

echo "LANGUAGE=$LANG$OPTIONAL"		       > "$DESTI$locale_file"
echo "LANG=$LANG$OPTIONAL"        	      >> "$DESTI$locale_file"
echo "LC_CTYPE=$LANG_COUNTRY.$CHARSET"	      >> "$DESTI$locale_file"
echo "LC_MESSAGES=$LANG_COUNTRY$OPTIONAL"     >> "$DESTI$locale_file"
echo "LC_NUMERIC=$LANG" 		      >> "$DESTI$locale_file"
echo "LC_TIME=$LANG"    		      >> "$DESTI$locale_file"
echo "LC_COLLATE=$LANG"  		      >> "$DESTI$locale_file"
echo "LC_MONETARY=$LANG"  		      >> "$DESTI$locale_file"
echo "LC_MESSAGES=$LANG"  	              >> "$DESTI$locale_file"
echo "LC_PAPER=$LANG"	 	    	      >> "$DESTI$locale_file"
echo "LC_NAME=$LANG"    		      >> "$DESTI$locale_file"
echo "LC_ADDRESS=$LANG" 		      >> "$DESTI$locale_file"
echo "LC_TELEPHONE=$LANG"  		      >> "$DESTI$locale_file"
echo "LC_MEASUREMENT=$LANG" 		      >> "$DESTI$locale_file"
echo "LC_IDENTIFICATION=$LANG"                >> "$DESTI$locale_file"
echo "LC_MM_CHARSET=$CHARSET"                 >> "$DESTI$locale_file"
echo "LC_ALL=$LANG"                           >> "$DESTI$locale_file"

# Load Key definition
[ ! -e /etc/console/ ] && mkdir -p /etc/console/
[ -e "$DESTI/etc/console/boottime.kmap.gz" ] && rm -fr "$DESTI/etc/console/boottime.kmap.gz"
[ -e "$DESTI/etc/boottime.kmap.gz" ] && rm -fr "$DESTI/etc/boottime.kmap.gz"
cp "$DESTI/usr/share/keymaps/i386/qwerty/$KEYTABLE.kmap.gz" "$DESTI/etc/console/boottime.kmap.gz"
cp "$DESTI/usr/share/keymaps/i386/qwerty/$KEYTABLE.kmap.gz" "$DESTI/etc/boottime.kmap.gz"

loadkeys $KEYTABLE >/dev/null

#Actualitzacio del MOTD, si la variable no és nul·la
[ -n "$motd" ] && rm -f "$DESTI$motd_file" && echo "$motd" > "$DESTI$motd_file"
[ -n "$motd" ] && echo "$motd" > "$DESTI$issue_file"
