#!/bin/bash

#################################################
# Script per Configurar l'idioma amb el CADI    #
#         -------------------------             #
#    Preparat per la kademar 4.0 - 3 Nov 2005   #
#        Modificat   kademar 4.1 - 20 Feb 2006  #
#        Modificat   kademar 4.3 - 5 Set 2006   #
#        Modificat   kademar 4.8 - 2 Feb 2009   #
#    Llicenciat Sota GNU/GPL 2.0 o Superiors    #
#################################################


locale_file=/etc/default/locale
motd_file=/etc/motd
issue_file=/etc/issue

#Check parameters
[ -z "$1" ] && echo "I need at least a LANG (xx) parameter to work" && exit 1

LANGUAGE="$1"
#echo $LANGUAGE #DEBUG

#Target folder, may change
[ -n "$2" ] && DESTI="$2"

########### //  LOCALE DEFINITION EXTRACTED FROM KNOPPIX \\ #############

case "$LANGUAGE" in
# Catalan version
ca*)
LANG="ca_ES.UTF-8"
KEYTABLE="es"
XKEYBOARD="es"
KDEKEYBOARD="es"
CHARSET="iso8859-15"
# Additional KDE Keyboards
KDEKEYBOARDS=""
TZ="Europe/Madrid"
OPTIONAL=":ca_ES:ca:es_ES@euro:es_ES:es"
motd="Benvinguts a  kademar Linux"
;;
# German version
de*)
LANG="de_DE@euro"
KEYTABLE="de-latin1-nodeadkeys"
XKEYBOARD="de"
KDEKEYBOARD="de"
CHARSET="iso8859-15"
# Additional KDE Keyboards
KDEKEYBOARDS="us,fr"
TZ="Europe/Berlin"
;;
# Belgian version
be*)
LANG="be"
KEYTABLE="be2-latin1"
XKEYBOARD="be"
KDEKEYBOARD="be"
CHARSET="iso8859-15"
# Additional KDE Keyboards
KDEKEYBOARDS="us,de,fr"
TZ="Europe/Brussels"
;;
# Bulgarian version
bg*)
LANG="bg_BG"
KEYTABLE="bg"
XKEYBOARD="bg"
KDEKEYBOARD="bg"
CHARSET="microsoft-cp1251"
# Additional KDE Keyboards
KDEKEYBOARDS="us,de,fr"
TZ="Europe/Sofia"
;;
# Swiss version (basically de with some modifications*)
ch*)
LANG="de_CH"
KEYTABLE="sg-latin1"
XKEYBOARD="de_CH"
KDEKEYBOARD="de_CH"
CHARSET="iso8859-15"
# Additional KDE Keyboards
KDEKEYBOARDS="de,us,fr"
TZ="Europe/Zurich"
;;
cn*)
# Simplified Chinese version
LANG="zh_CN.GB2312"
KEYTABLE="us"
XKEYBOARD="us"
KDEKEYBOARD="us"
CHARSET="gb2312.1980-0"
# Additional KDE Keyboards
KDEKEYBOARDS="us,de,fr"
XMODIFIERS="@im=Chinput"
TZ="Asia/Shanghai"
;;
# Czech version
cs*|cz*)
LANG="cs_CZ"
KEYTABLE="cz-lat2"
XKEYBOARD="cs"
KDEKEYBOARD="cs"
CHARSET="iso8859-2"
# Additional KDE Keyboards
KDEKEYBOARDS="us,de,fr"
TZ="Europe/Prague"
CONSOLEFONT="iso02g"
;;
dk*|da*)
# Dansk version
LANG="da_DK"
# Workaround: "dk" broken in gettext, use da:da_DK
OPTIONAL="da:da_DK"
# Keytable "dk" is correct.
KEYTABLE="dk"
XKEYBOARD="dk"
KDEKEYBOARD="dk"
CHARSET="iso8859-15"
# Additional KDE Keyboards
KDEKEYBOARDS="dk,de,us,fr"
TZ="Europe/Copenhagen"
;;
es*)
# Spanish version
LANG="es_ES@euro"
KEYTABLE="es"
XKEYBOARD="es"
KDEKEYBOARD="es"
CHARSET="iso8859-15"
# Additional KDE Keyboards
KDEKEYBOARDS="de,us,fr"
TZ="Europe/Madrid"
OPTIONAL=":es_ES:es"
motd="Bienvenidos a  kademar Linux"
;;
fi*)
# Finnish version, though we may not have the kde-i18n files
LANG="fi_FI@euro"
KEYTABLE="fi"
XKEYBOARD="fi"
KDEKEYBOARD="fi"
CHARSET="iso8859-15"
# Additional KDE Keyboards
KDEKEYBOARDS="us"
TZ="Europe/Helsinki"
;;
fr*)
# French version
LANG="fr_FR@euro"
KEYTABLE="fr"
XKEYBOARD="fr"
KDEKEYBOARD="fr"
CHARSET="iso8859-15"
# Additional KDE Keyboards
KDEKEYBOARDS="de,us"
TZ="Europe/Paris"
;;
he*|il*)
# Hebrew version
LANG="he_IL"
KEYTABLE="us"
XKEYBOARD="us"
KDEKEYBOARD="il"
CHARSET="iso8859-8"
# Additional KDE Keyboards
KDEKEYBOARDS="us,fr,de"
TZ="Asia/Jerusalem"
;;
ie*)
# Irish (English) version
LANG="en_IE@euro"
KEYTABLE="uk"
XKEYBOARD="uk"
KDEKEYBOARD="gb"
CHARSET="iso8859-15"
#Additional KDE Keyboards
KDEKEYBOARDS="us,de,es,fr,it"
TZ="Europe/Dublin"
;;
it*)
# Italian version
LANG="it_IT@euro"
KEYTABLE="it"
XKEYBOARD="it"
KDEKEYBOARD="it"
CHARSET="iso8859-15"
# Additional KDE Keyboards
KDEKEYBOARDS="fr,us,de"
TZ="Europe/Rome"
;;
ja*)
# (limited) Japanese version
LANG="ja_JP"
KEYTABLE="us"
XKEYBOARD="us"
KDEKEYBOARD="us"
CHARSET="iso8859-15"
# Additional KDE Keyboards
KDEKEYBOARDS="fr,us,de"
TZ="Asia/Tokyo"
;;
nl*)
# Dutch version
LANG="nl_NL@euro"
KEYTABLE="us"
XKEYBOARD="us"
KDEKEYBOARD="en_US"
CHARSET="iso8859-15"
# Additional KDE Keyboards
KDEKEYBOARDS="nl,de,fr"
TZ="Europe/Amsterdam"
;;
pl*)
# Polish version
LANG="pl_PL"
KEYTABLE="pl"
XKEYBOARD="pl"
KDEKEYBOARD="pl"
CHARSET="iso8859-2"
# Additional KDE Keyboards
KDEKEYBOARDS="de,us,fr"
TZ="Europe/Warsaw"
CONSOLEFONT="iso02g"
;;
ru*)
# Russian version
LANG="ru_RU.KOI8-R"
KEYTABLE="ru"
XKEYBOARD="ru"
KDEKEYBOARD="ru"
CHARSET="koi8-r"
CONSOLEFONT="Cyr_a8x16"
# Additional KDE Keyboards
KDEKEYBOARDS="de,us,fr"
TZ="Europe/Moscow"
;;
sk*)
# Slovak version (guessed)
LANG="sk"
KEYTABLE="sk-qwerty"
XKEYBOARD="sk"
KDEKEYBOARD="sk"
CHARSET="iso8859-2"
# Additional KDE Keyboards
KDEKEYBOARDS="us,de"
TZ="Europe/Bratislava"
CONSOLEFONT="iso02g"
;;
# Slovenian keyboard
sl*)
LANG="sl_SI"
KEYTABLE="slovene"
XKEYBOARD="sl"
KDEKEYBOARD="si"
CHARSET="iso8859-2"
# Additional KDE Keyboards
KDEKEYBOARDS="us,de"
TZ="Europe/Ljubljana"
CONSOLEFONT="iso02g"
;;
tr*)
# Turkish version (guessed)
LANG="tr_TR"
KEYTABLE="tr_q-latin5"
XKEYBOARD="tr"
KDEKEYBOARD="tr"
CHARSET="iso8859-9"
# Additional KDE Keyboards
KDEKEYBOARDS="us,de,fr"
TZ="Europe/Istanbul"
;;
tw*)
# Traditional Chinese version (thanks to Chung-Yen Chang)
LANG="zh_TW.Big5"
KEYTABLE="us"
XKEYBOARD="us"
KDEKEYBOARD="us"
# CHARSET="big5-0"
CHARSET="iso8859-1"
# Additional KDE Keyboards
KDEKEYBOARDS="us"
XMODIFIERS="@im=xcin"
TZ="Asia/Taipei"
;;
uk*)
# British version
LANG="en_GB.UTF-8"
KEYTABLE="uk"
XKEYBOARD="uk"
KDEKEYBOARD="gb"
CHARSET="iso8859-1"
# Additional KDE Keyboards
KDEKEYBOARDS="us"
TZ="Europe/London"
motd="Welcome to  kademar Linux"
;;
en|*)
# American version
LANG="en"
KEYTABLE="us"
XKEYBOARD="us"
KDEKEYBOARD="us"
CHARSET="iso8859-1"
# Additional KDE Keyboards
KDEKEYBOARDS="de,fr"
TZ="America/New_York"
motd="Welcome to  kademar Linux"
;;
esac

################ //  END OF LOCALE DEFINITION  \\  ####################

echo "LANG=$LANG$OPTIONAL"        	      > "$DESTI$locale_file"


cat > /etc/default/keyboard << EOF
# If you change it, restart HAL.
# Can have the same parameters /etc/X11/xorg.conf

XKBMODEL="pc105"
XKBLAYOUT="$XKEYBOARD"
XKBVARIANT=""
XKBOPTIONS=""
EOF

# Load Key definition
# [ ! -e /etc/console/ ] && mkdir -p /etc/console/
# [ -e "$DESTI/etc/console/boottime.kmap.gz" ] && rm -fr "$DESTI/etc/console/boottime.kmap.gz"
# [ -e "$DESTI/etc/boottime.kmap.gz" ] && rm -fr "$DESTI/etc/boottime.kmap.gz"
# cp "$DESTI/usr/share/keymaps/i386/qwerty/$KEYTABLE.kmap.gz" "$DESTI/etc/console/boottime.kmap.gz"
# cp "$DESTI/usr/share/keymaps/i386/qwerty/$KEYTABLE.kmap.gz" "$DESTI/etc/boottime.kmap.gz"

# loadkeys $KEYTABLE >/dev/null

#Actualitzacio del MOTD, si la variable no és nul·la
[ -n "$motd" ] && rm -f "$DESTI$motd_file" && echo "$motd" > "$DESTI$motd_file"
[ -n "$motd" ] && echo "$motd" > "$DESTI$issue_file"
