Document: squashfs-tools-xz
Title: Debian squashfs-tools-xz Manual
Author: <insert document author here>
Abstract: This manual describes what squashfs-tools-xz is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/squashfs-tools-xz/squashfs-tools-xz.sgml.gz

Format: postscript
Files: /usr/share/doc/squashfs-tools-xz/squashfs-tools-xz.ps.gz

Format: text
Files: /usr/share/doc/squashfs-tools-xz/squashfs-tools-xz.text.gz

Format: HTML
Index: /usr/share/doc/squashfs-tools-xz/html/index.html
Files: /usr/share/doc/squashfs-tools-xz/html/*.html
