Document: kademar-base-desktop
Title: Debian kademar-base-desktop Manual
Author: <insert document author here>
Abstract: This manual describes what kademar-base-desktop is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/kademar-base-desktop/kademar-base-desktop.sgml.gz

Format: postscript
Files: /usr/share/doc/kademar-base-desktop/kademar-base-desktop.ps.gz

Format: text
Files: /usr/share/doc/kademar-base-desktop/kademar-base-desktop.text.gz

Format: HTML
Index: /usr/share/doc/kademar-base-desktop/html/index.html
Files: /usr/share/doc/kademar-base-desktop/html/*.html


