#!/bin/sh
set -e
#Udev Stolen Function :-[
chrooted() {
  if [ "$(stat -c %d/%i /)" = "$(stat -Lc %d/%i /proc/1/root 2>/dev/null)" ];
  then
    # the devicenumber/inode pair of / is the same as that of /sbin/init's
    # root, so we're *not* in a chroot and hence return false.
    return 1
  fi
#   echo "Live-CD Creation environment detected. Creating links to Xsession."
  return 0
}

# Automatically added by dh_installmodules
if [ "$1" = "configure" ]; then
	
#     if [ ! -e /etc/splashy/themes/default ]; then
#         rm -fr /etc/splashy/themes/default 2>/dev/null
#       ln -s /etc/splashy/themes/kademar /etc/splashy/themes/default
#         cp -a /etc/splashy/themes/kademar /etc/splashy/themes/default
#     fi
    dpkg-divert --package kademar-base-desktop --add --divert /etc/splashy/config.xml.orig --rename /etc/splashy/config.xml
    [ ! -e /etc/splashy/config.xml ] && ln -s /etc/splashy/config.xml.kademar /etc/splashy/config.xml

    dpkg-divert --package kademar-base-desktop --add --divert /etc/splash/splash.orig --rename /etc/splash/splash
    [ ! -e /etc/splash/splash ] && ln -s /etc/splash/splash.kademar /etc/splash/splash

    dpkg-divert --package kademar-base-desktop --add --divert /etc/libao.conf.orig --rename /etc/libao.conf
    [ ! -e /etc/libao.conf ] && ln -s /etc/libao.conf.kademar /etc/libao.conf

    dpkg-divert --package kademar-base-desktop --add --divert /etc/iceweasel/iceweaselrc.orig --rename /etc/iceweasel/iceweaselrc
    [ ! -e /etc/iceweasel/iceweaselrc ] && ln -s /etc/iceweasel/iceweaselrc.kademar /etc/iceweasel/iceweaselrc

    #suport to audacious binary
    if [ -e /usr/bin/audacious2 -a ! -e /usr/bin/audacious ]; then
        ln -s /usr/bin/audacious2 /usr/bin/audacious
    fi

    if [ -z "`grep -i Xft.dpi /etc/X11/Xresources/x11-common 2>/dev/null`" ]; then
        echo "Configuring DPI for X server"
    	echo "Xft.antialias: 1
Xft.dpi:90
Xft.hinting: 1
Xft.hintstyle: hintfull
Xft.rgba: rgb" >> /etc/X11/Xresources/x11-common
    fi
fi
# End automatically added section
