#!/bin/bash 
#TODO Arreglar aquest script si el volem o suprimir-lo

echo  "This script is fux0rized."
echo  "Self destruction in 3 seconds, have a nice day. :-)"
exit 1

. /usr/lib/kademar-scripts/sourcables/load_config

cd $SOURCE_DIR

echo "# Montant initrd generic"
cp $INITRD_INC tmp/
cd tmp
mount -o loop $INITRD_INC ../initrd

cd ../initrd
bash -l || exit 1 
echo "# Ok desmuntant el initrd i tornant a comprimir..."
cat /dev/zero > zero 2> /dev/null
rm zero
cd ..
umount initrd &&
mv tmp/geninitrd $INITRD_INC

echo "# Acabat"

