#!/bin/bash

##He tret el  -no-bak \ perque sino s'endú per devant
## els fitxers espa~nol.aff espa~nol.hash per la ~ que porta.
#swapon /dev/evms/swap_provi  -pri=1 
mkisofs -R -U -V "cloop filesystem" \
	-P "burnix" \
	-hide-rr-moved \
	-cache-inodes \
	-pad ../source/KNOPPIX | nice -n -5 create_compressed_fs - 65536 > ../master/KNOPPIX/KNOPPIX #\
	#&& swapoff /dev/evms/swap_provi

