#!/bin/bash -x

nice -n -5 bin/gzipd 3000 &
nice -n -5 bin/gzipd 3001 &
#nice -n -5 bin/gzipd 3002 &
#nice -n -5 bin/gzipd 3003 &

sleep 1

time nice -n -5 bin/gzip ../isos/tmpcloop.iso ../master/KNOPPIX/KNOPPIX \
	3000 \
	localhost:3000 \
	localhost:3001 || exit 1 
	#localhost:3002 \
	#localhost:3003 &&
	#192.168.1.248 \
	#192.168.1.5

#rm ../isos/tmpcloop.iso

killall gzipd
