#!/bin/bash 

###Carrego variables de config
. burnix.conf 


./mkclean.sh || exit 98

./update-boot.sh || exit 12

#./mkcloop.sh || exit 99
./mksquash.sh || exit 99
#./mkloopiso.sh || exit 1
#./mkdistcloop.sh || exit 2
./mkmd5.sh || exit 3
./mkiso.sh || exit 4
echo tot correcte || echo error

