#!/bin/bash 

. burnix.conf

cd $BURNIX_BOOT

echo montant initrd
cp minirt26.gz ../tmp
cd ../tmp
gunzip minirt26.gz
mount -o loop minirt26 ../initrd
cd ../initrd
echo obrint un shell per a editar coses del initrd
#export PS1="initrd>"
bash -l
echo ok desmuntant el initrd i tornant a comprimir....
cd ..
umount initrd/
cd tmp/
gzip minirt26

##afegim el bootsplash...

splash -s -f /etc/bootsplash/themes/current/config/bootsplash-1024x768.cfg >> minirt26.gz


mv minirt26.gz ../boot
echo el initrd 26 ja ha sigut posat al seu lloc.

echo "imatge d'arrencada modificada, desmontant"
cd ..
#umount loopboot
pwd
cp -fvr boot/* $MASTER_BOOT 
