#!/bin/bash 

cd ../source/boot/isolinux

#echo montant imatge 24

#mount boot288.img loopboot -o loop -t vfat
#cd loopboot/

echo canviant logo

pngtopnm \
	< ../../../artwork/logo-splash-livecd.png \
	> /tmp/logo.pnm
	
ppmtolss16 \
	< /tmp/logo.pnm \
	> logo.16

echo logo canviat

vi isolinux.cfg boot.msg f2 f3 f4 f5 f6 f7

echo montant initrd
cp minirt24.gz ../../tmp
cd ../../tmp
gunzip minirt24.gz
mount -o loop minirt24 ../initrd
cd ../initrd
echo obrint un shell per a editar coses del initrd
bash -l
echo ok desmuntant el initrd i tornant a comprimir....
cd ..
umount initrd/
cd tmp/
gzip minirt24
mv minirt24.gz ../boot/isolinux/
echo el initrd 24 ja ha sigut posat al seu lloc.

echo "imatge d'arrencada modificada"
#cd ..
#umount loopboot
#cp -fv boot/isolinux/* ../../master/boot/isolinux/
